Simpler mempool configuration
raspibolt/raspibolt pull request #1060
Opened 2022-08-10 13:13 UTC by RooSoft

#### What

Completely removed NGINX config, should allow for easier node restarts and mempool app upgrades

### Why

The app needed a refresh and NGINX configure had some potential DNS issues on node restarts

#### How

Run the frontend according to the [official documentation](https://github.com/mempool/mempool/tree/master/frontend)

#### Scope

- [X] guide simplification

#### Test & maintenance

Restart the raspibolt and make sure the mempool site works at https://raspibolt:4200

#### Animated GIF (optional)

![blabla](https://media.giphy.com/media/XSVyi8jXJcv4ZEvOas/giphy-downsized.gif)

2022-08-10 13:52 UTC, RooSoft commented
The frontend should be using the backend provided in the same guilde... at the moment, I can't guarantee it's the case. Can someone inspect the network to make sure it's not calling the public mempool API?

2022-09-06 07:47 UTC, sig-noi requested changes
latest version appears to be 2.4.0 - should line 90 be updated? 
`$ git checkout v2.4.0`

2022-09-14 12:25 UTC, RooSoft commented
@sig-noi the code literally gets the latest version

```bash
git checkout $latestrelease
```

2022-10-05 12:15 UTC, twofaktor approved these changes
Few suggestions

2022-10-05 12:15 UTC, twofaktor commented on guide/bonus/bitcoin/mempool.md
> -  HiddenServicePort 443 127.0.0.1:4081
The correct line following your modifications is: `HiddenServicePort 80 127.0.0.1:4081`

Tor network has encrypted communications by design, this would be redundant

2022-10-05 12:15 UTC, twofaktor commented on guide/bonus/bitcoin/mempool.md
>    # Mempool Hidden Service
Add in the line before:
`############### This section is just for location-hidden services ###`

ref e.g: https://raspibolt.org/guide/bitcoin/blockchain-explorer.html#remote-access-over-tor-optional

to standardize with the rest of the guide

2022-11-06 12:09 UTC, twofaktor requested changes
Add: `"USE_ONION": true,`
Between: 195-196

2022-11-07 12:47 UTC, VajraOfIndra commented
> Add: `"USE_ONION": true,` Between: 195-196

This has already been merged with #1121

2022-11-25 09:01 UTC, VajraOfIndra commented
I don't think removing the nginx reverse proxy is desired as this is a core security feature of our guides. 

I didn't seem to have an issue with Mempool lately so maybe things have changed with the latest verisons of Mempool. Otherwise, I think working with the various service files (bitcoind, mempool, nginx) and playing with various options (Wants, PartOf etc) might solve any remaining issues.

I propose we close this PR for now.

2022-11-25 12:01 UTC, twofaktor commented
> I don't think removing the nginx reverse proxy is desired as this is a core security feature of our guides.
> 
> I didn't seem to have an issue with Mempool lately so maybe things have changed with the latest verisons of Mempool. Otherwise, I think working with the various service files (bitcoind, mempool, nginx) and playing with various options (Wants, PartOf etc) might solve any remaining issues.
> 
> I propose we close this PR for now.

- What about creating frontend autoboot? 
- We don't use `rpcuser/rpcpassword` auth on `bitcoin.conf``, instead we use rpcauth (cookie file), was tested this guide on RaspiBolt v3? 
```
  "CORE_RPC": {
    "HOST": "127.0.0.1",
    "PORT": 8332,
    "USERNAME": "raspibolt",
    "PASSWORD": "Password[B]"
```
- What about using an SSL connection through Tor? We know Tor is encrypted by design. I'm wrong if I think that with this configuration mempool is listening directly on the SSL port.

2023-05-09 09:33 UTC, closed without merging