New bonus guide: Safu Ninja, a DIY steel mnenomics backup solution
raspibolt/raspibolt pull request #1072
Opened 2022-08-26 06:34 UTC by VajraOfIndra

#### What

- A guide on how to make a cool DIY steel backup for mnemonics with washers and a stamping set.

### Why

- This off-the-shelf DIY backup solution so a perfect match with the whole RaspiBolt ethos. It's not _directly_ related to the node but very close to it so i think it has its place as a bonus guide. Wdyt?

#### How

- Wrote a brand new guide but gave it the name Safu Ninja and acknowlegde them as the inventor of the technique (their Reddit post of June 2020 is the oldest reference to the tehcnique I could find and also Jameson Lopp in his stress test page refers to this technique under the Safu Ninja name).

#### Scope

- [ ] significant change to core configuration
- [x] independent bonus guide
- [ ] simple bug fix

Fixes non-resilient paper storage!

#### Test & maintenance

Review instructions and links.

#### Ideas for improvements (before merging or later on)

- Improve technical recommendations for washers, bolt and stamping set selection. The sizes of them all is critical and the choice is so large and a bit confusing. There might be some differences between US vs Europe vs other parts of the world etc.. So maybe adding a picture of a table with washer size could help.
- Add images to illustrate the process

#### Animated GIF (optional)

![This is fine](https://media.giphy.com/media/NTur7XlVDUdqM/giphy.gif)

2022-08-26 07:38 UTC, Stadicus requested changes
Great guide, with nice pictures. I added a few nits about naming specific brands.

One important change we should consider: NEVER enter your recovery words on an online device unless it's an emergency. I think the guide should strongly advise recovery using a hardware wallet so that the cold storage security is not lost and the recovery words are not put at risk.

2022-08-26 07:38 UTC, Stadicus commented on guide/bonus/bitcoin/safu-ninja.md
> +![Stress test](../../../images/safu-ninja-stress-test-result.png)
The actual image files name uses an UPPER CASE file extension, so this image is not displayed here.

2022-08-26 07:38 UTC, Stadicus commented on guide/bonus/bitcoin/safu-ninja.md
> +* (Optional) Punch the name of the wallet on a washer (e.g. "MY COLDCARD" or "LND"). It might come handy in a few years to remember what wallet was associated with this backup and also because some w
I think we should avoid mentioning specific brands if not really relevant. I also try to keep the BitBox out of it so that it's a neutral guide. 

How about this?
`s/MY COLDCARD/WALLET XY/`

2022-08-26 07:38 UTC, Stadicus commented on guide/bonus/bitcoin/safu-ninja.md
> +* Enter a wallet name (e.g., "Recovered Seedsigner")
Same here, the wallet name doesn't add any real value

`s/Recovered Seedsigner/Recovered Wallet XY/`

2022-08-26 07:38 UTC, Stadicus commented on guide/bonus/bitcoin/safu-ninja.md
> +Below are a few pointers in case you need to use your backup to recover funds from one of your wallet.
In general, I would refrain from advising people to restore their recovery words into a hot software wallet, unless it's an emergency. All cold storage security is immediately lost and funds are at risk of remote attacks.

Best practice is to NEVER enter your 24 recovery words on an online device unless it's just a few hundred bucks (which is unlikely if you go to great lengths to create the most private and secure steel backup)

The recovery process should STRONGLY advise using a hardware wallet. The recovery words can then be entered into the dedicated and secure offline device without putting them at risk.

2022-08-26 08:48 UTC, VajraOfIndra commented on guide/bonus/bitcoin/safu-ninja.md
> +![Stress test](../../../images/safu-ninja-stress-test-result.png)
Fixed

2022-08-26 08:49 UTC, VajraOfIndra commented on guide/bonus/bitcoin/safu-ninja.md
> +* (Optional) Punch the name of the wallet on a washer (e.g. "MY COLDCARD" or "LND"). It might come handy in a few years to remember what wallet was associated with this backup and also because some w
Good point, fixed.

2022-08-26 08:49 UTC, VajraOfIndra commented on guide/bonus/bitcoin/safu-ninja.md
> +* Enter a wallet name (e.g., "Recovered Seedsigner")
Addressed in comment below

2022-08-26 08:56 UTC, VajraOfIndra commented on guide/bonus/bitcoin/safu-ninja.md
> +Below are a few pointers in case you need to use your backup to recover funds from one of your wallet.
Very true, didn't thunk of that. I reworded the Recovery section, PTAL.

2022-08-28 11:41 UTC, sutterseba commented on guide/bonus/bitcoin/safu-ninja.md
> +* (Optional) Punch the date of creation of your wallet, known as the "birth date". This could help you quicken the search for your UTXOs when reconstructing the wallet in a few years. The wallet soft
Maybe you could add something to distinct between classic BIP-39 mnemonic phrases and the aezeed cipher scheme. Normally this wouldn't be that important, but most users reading this bonus guide will both have "normal" cold/hot storage and the on-chain wallet of their LND client, using aezeed.  

Users punching an aezeed cipher should know about limited recovery options and, for example, that the birth date is already encoded in the cipher (and punching it is not necessary).

2022-09-02 23:16 UTC, VajraOfIndra commented on guide/bonus/bitcoin/safu-ninja.md
> +* (Optional) Punch the date of creation of your wallet, known as the "birth date". This could help you quicken the search for your UTXOs when reconstructing the wallet in a few years. The wallet soft
Good idea, I added a reference to the azeed cypher scheme and the contained birth date.

2022-09-14 06:36 UTC, Stadicus approved these changes
LGTM! :)

2022-09-14 08:31 UTC, merged