[UPDATE BONUS GUIDE] Minor update of the Fulcrum bonus guide
raspibolt/raspibolt pull request #1076
Opened 2022-08-29 11:54 UTC by twofaktor

#### What

Improvement of `fulcrum.conf` configuration file and minor fix of redirect link wrong 

### Why

Why is this change important?

#### How

- Fixed wrong redirect link to Desktop Wallet core section
- Fixed `announce = false` parameter redundancy in `fulcrum.conf`

Following developer example-config:
https://github.com/cculianu/Fulcrum/blob/master/doc/fulcrum-example-config.conf#L427-L435

#### Scope

- [ ] significant change to core configuration
- [X] independent bonus guide
- [ ] simple bug fix

#### Evidences

```sh
# Peering: announce self - 'announce' - DEFAULT: true if hostname and *peering
#                                                are set*, false otherwise
#
# You must enable `peering` above and also define a `hostname` for this to have
# an effect. If set to true and the above conditions are met, then your server
# will announce itself to peers and likely appear in their server lists. Setting
# this to true ensures you get more clients connecting to your server.
#
#announce = true
```
DEFAULT: true if hostname and *peering are set*, false otherwise

https://raspibolt.org/guide/bonus/bitcoin/fulcrum.html#configuration
```sh
peering = false
```

2022-09-05 21:53 UTC, VajraOfIndra requested changes

2022-09-05 21:53 UTC, VajraOfIndra commented on guide/bonus/bitcoin/fulcrum.md
> +💡 Fulcrum must first fully index the blockchain and compact its database before you can connect to it with your wallets. This can take up until ~3.5 - 4 days. Only proceed with the [Desktop Wallet Se
```suggestion
💡 Fulcrum must first fully index the blockchain and compact its database before you can connect to it with your wallets. This can take up to ~3.5 - 4 days. Only proceed with the [Desktop Wallet Section](../../bitcoin/desktop-wallet.md) once Fulcrum is ready.
```

2022-09-05 21:53 UTC, VajraOfIndra commented on guide/bonus/bitcoin/fulcrum.md
> +Because the sync can take ~3.5 to 4 days, it is recommended to have at least any backup of the database. It doesn't need to be the latest one and you can backup only once. It is still better to sync
I think this paragraph would benefit from a rewording.
Below is a suggestion
```suggestion
If the database gets corrupted and you don't have a backup, you will have to resync it from scratch, which takes several days. This is why we recommend to make backups of the database once in a while, on an external drive. Like this, if something happens, you'll only have to resync since the date of your latest backup. Before doing the backup, remember to stop Fulcrum with `sudo systemctl stop fulcrum`
```

Later on, we could maybe add a few commands that explain how to create the backup folder, and how to do such backup with rsync, wdyt? Just a tought.

2022-09-05 21:59 UTC, DanielPX1 commented on guide/bonus/bitcoin/fulcrum.md
> +Because the sync can take ~3.5 to 4 days, it is recommended to have at least any backup of the database. It doesn't need to be the latest one and you can backup only once. It is still better to sync
Did not notice the announce etc. is not neccessary, however I think its great idea to include backup section (y).

2022-09-05 22:00 UTC, twofaktor commented on guide/bonus/bitcoin/fulcrum.md
> +Because the sync can take ~3.5 to 4 days, it is recommended to have at least any backup of the database. It doesn't need to be the latest one and you can backup only once. It is still better to sync
I think backup section should be a exclusive & independent bonus guide, because this could be applied to blockchain mainnet & testnet and electrs/Fulcrum indexes, not only to Fulcrum index

2022-09-07 23:33 UTC, VajraOfIndra approved these changes
LGTM, utACK 👍

2022-09-07 23:47 UTC, VajraOfIndra commented on guide/bonus/bitcoin/fulcrum.md
> +Because the sync can take ~3.5 to 4 days, it is recommended to have at least any backup of the database. It doesn't need to be the latest one and you can backup only once. It is still better to sync
> Do you think that adding additional commands to the guide could make it too long? 

Maybe, but there are some long guides, I don't think it's an issue personally, particulalry as it is an optional section. Just my 2 sats.

2022-09-07 23:47 UTC, merged