update to 1.8.1
raspibolt/raspibolt pull request #1097
Opened 2022-09-18 21:11 UTC by DanielPX1

2022-09-18 21:27 UTC, twofaktor requested changes
Compare with your results, utACK in arm64

2022-09-18 21:27 UTC, twofaktor commented on guide/bonus/bitcoin/fulcrum.md
> +> Fulcrum 1.8.1 (Release 4ee413a)
->> Fulcrum 1.8.1 (Release c80bf1b)

2022-09-18 21:27 UTC, twofaktor commented on guide/bonus/bitcoin/fulcrum.md
>  compiled: gcc 7.5.0
->> compiled: gcc 8.4.0

2022-09-18 21:27 UTC, twofaktor commented on guide/bonus/bitcoin/fulcrum.md
> +Jul 28 12:20:13 rasp Fulcrum[181811]: [2022-07-28 12:20:13.064] Fulcrum 1.8.1 (Release 4ee413a) - Thu Jul 28, 2022 12:20:13.064 CEST - starting up ...
Same of line 212

2022-09-18 21:54 UTC, DanielPX1 commented
> Compare with your results, utACK in arm64

For some reason cant see that, no number follows after "Release" for me. Put your values in there instead.
Fulcrum 1.8.1 (Release )
compiled: gcc 8.4.0

2022-09-18 22:06 UTC, twofaktor approved these changes
utACK in arm64! LGTM 👍

2022-09-18 22:57 UTC, DanielPX1 commented
> utACK in arm64! LGTM 👍

Glad to hear! Can we ask for a review @VajraOfIndra @Stadicus @kristapsk ?

2022-09-24 09:31 UTC, twofaktor commented
Change line [248](https://github.com/raspibolt/raspibolt/pull/1097/files#diff-730f9901c4e7cac9c3b645e8bbe633d5e208fa99886bbee3fc28d2c873c3b8a0R248) to:

`* Change to fulcrum data folder and generate cert and key files for SSL. Press `Enter` until the prompt is shows again`

2022-09-26 11:07 UTC, twofaktor requested changes
Suggested redaction improvement

2022-09-26 11:07 UTC, twofaktor commented on guide/bonus/bitcoin/fulcrum.md
> +* Exit the `btcrpcexplorer` user exiting and open `btcrpcexplorer` service
Change to --> * Return to `admin` user exiting and open `btcrpcexplorer` service

2022-09-26 12:58 UTC, DanielPX1 commented on guide/bonus/bitcoin/fulcrum.md
> +* Exit the `btcrpcexplorer` user exiting and open `btcrpcexplorer` service
Changed to suggested text

2022-09-26 13:01 UTC, twofaktor commented
LGTM again! tACK is ready to merge!

2022-09-26 13:11 UTC, DanielPX1 commented
Great!

2022-09-28 15:05 UTC, twofaktor requested changes
A minor fix

2022-09-28 15:05 UTC, twofaktor commented on guide/bonus/bitcoin/fulcrum.md
> +  $ sudo journalctl -fu fulcrum.service
Change to -->

`sudo journalctl -f -u fulcrum`

to standardize with the rest of the guide

2022-09-28 18:08 UTC, DanielPX1 commented on guide/bonus/bitcoin/fulcrum.md
> +  $ sudo journalctl -fu fulcrum.service
done!

2022-09-28 21:57 UTC, twofaktor approved these changes
LGTM again! uACK!

2022-09-28 23:35 UTC, DanielPX1 commented
> LGTM again! uACK!

Great! looks ready 2 merge

2022-10-05 10:18 UTC, twofaktor approved these changes
tACK

2022-10-06 09:43 UTC, twofaktor commented
> @twofaktor could you provide the version string? Sadly I cant access my node remotely, there have to be some issue

Fulcrum 1.8.2 ---> (Release d330248)

It's the only thing different

2022-10-09 09:50 UTC, DanielPX1 commented
> > @twofaktor could you provide the version string? Sadly I cant access my node remotely, there have to be some issue
> 
> Fulcrum 1.8.2 ---> (Release d330248)
> 
> It's the only thing different

Sorry I took some time, its done now

2022-10-10 19:47 UTC, twofaktor approved these changes
A minor suggestion

2022-10-10 19:47 UTC, twofaktor commented on guide/bonus/bitcoin/fulcrum.md
> +  Wants=bitcoind.service
Change to ---> `PartOf=bitcoind.service`

ref PR: #1118

2022-10-11 12:04 UTC, DanielPX1 commented on guide/bonus/bitcoin/fulcrum.md
> +  Wants=bitcoind.service
Good suggestion. Added

2022-10-22 13:06 UTC, twofaktor approved these changes
LGTM! some maintainer would review this PR?? @VajraOfIndra please, this PR was opened a month ago and has no comments...

2022-10-25 08:16 UTC, merged