Several Electrs upgrades based on #747 + a few bug fixes
raspibolt/raspibolt pull request #1102
Opened 2022-09-24 10:10 UTC by VajraOfIndra

#### What

This PR aims at addressing several improvement suggestions made by @Kixunil in #747:

- Use **dynamic linking** when compiling Electrs. The advantages of dynamic linking seem to be better than the ones for static linking, [see details here](https://github.com/romanz/electrs/blob/master/doc/install.md)
- Adding `git clean -x -f d` to the update instructions -> Removes untracked files from the working tree [(source)](https://git-scm.com/docs/git-clean)
- Harden systemd service by adding `ProtectSystem=full`
- Harden systemd service by adding `ProtectHome` option. To do this, I had to add the `--skip-default-conf-files `argument to the `ExecStart` command of the service file. I also add to add `cookie_file= "/data/bitcoin/.cookie"` to the Electrs conf file as otherwise I would get the following permissions error:
> Sep 24 10:00:23 raspibolt electrs[1173697]:     0: failed to open bitcoind cookie file: /home/bitcoin/.bitcoin/.cookie
> Sep 24 10:00:23 raspibolt electrs[1173697]:     1: Permission denied (os error 13)

@Kixunil Is that (the point above) the correct way to do it?
- Prepending `cargo build` command with `CARGO_NET_GIT_FETCH_WITH_CLI=true` which will workaround the bug on Debian systems with broken cargo
- Adding `git verify-tag` upgrade instructions to verify the release
- Changing "# Start electrs" in upgrade instructions to more accurate "# Restart electrs"

Several suggestions in #747 are not addressed in this PR and should be discussed in #747 (I'll list them there).

The PR also:
- Fixes a typo in the intro: removing extra text #prepare-nginx-reverse-proxy
- Fixes the language of the Electrs conf file from ini to toml
- As /home is protected with `ProtectHome`, replaced path to Bitcoin core daemon from "/home/bitcoin/.bitcoin" to "/data/bitcoin"

#### Scope

- [x] significant change to core configuration
- [ ] independent bonus guide
- [ ] simple bug fix

#### Test & maintenance

Install Electrs from scratch using the new dynamic linking, and test that the systemd service file runs fine.

![todo](https://media.giphy.com/media/dWOKEQ5ewh94RJLemj/giphy.gif)

2022-09-24 17:49 UTC, twofaktor commented
Take the opportunity to put in line 284/291 the name of the hidden service:

`# Hidden Service Electrs SSL`

2022-09-24 22:01 UTC, kristapsk commented on guide/bitcoin/electrum-server.md
> +  $ sudo apt install cargo clang cmake build-essential librocksdb-dev
https://github.com/romanz/electrs/blob/master/doc/install.md says 6.11.4 release of rocksdb is required. Not specifying version on my system (bullseye) installs 5.17.2-3. When it's not available, that guide suggests building manually.

2022-09-24 22:13 UTC, VajraOfIndra commented
> Take the opportunity to put in line 284/291 the name of the hidden service:
> 
> `# Hidden Service Electrs SSL`

Done :+1: 

_(sorry I edited your comment by mistake while trying to reply)_

2022-09-24 22:16 UTC, VajraOfIndra commented on guide/bitcoin/electrum-server.md
> +  $ sudo apt install cargo clang cmake build-essential librocksdb-dev
Using `librocksdb-dev=6.11.4-3` should work on RasPiOS, right? If so we could simply use that command.

2022-09-24 22:29 UTC, kristapsk commented on guide/bitcoin/electrum-server.md
> +  $ sudo apt install cargo clang cmake build-essential librocksdb-dev
Not sure, I'm running Odroid HC4, for which default is Ubuntu Server.

2022-09-25 17:34 UTC, VajraOfIndra commented on guide/bitcoin/electrum-server.md
> +  $ sudo apt install cargo clang cmake build-essential librocksdb-dev
On my Raspberry Pi 4 with Raspberry Pi OS Lite 64-bit I get:
> admin@raspibolt:~ $ sudo apt list --all-versions librocksdb-dev 
> Listing... Done
> librocksdb-dev/stable 6.11.4-3+deb11u1 arm64

So this should work for the users that follow the default guide.

I am out of my depths here about what would be best for the guide.. We have 3 options I believe:

1. Static linking (existing method)
2. Dynamic linking, using `apt` to install `librocksdb`
3. Dynamic linking, manually building `librocksdb`

Which one would be the most robust and cross-OS compatible option..?

2022-09-27 16:40 UTC, twofaktor commented
hello guys, is possible to change lines 101-102 to using the `/temp` folder?

I watched this dev video installing and it made me think:

[![asciicast](https://asciinema.org/a/XKznxilP4O7lCZiVZ9vZNd5vx.svg)](https://asciinema.org/a/XKznxilP4O7lCZiVZ9vZNd5vx)

Then in line 123 we make it persistent and It should work. Wdyt?

2022-09-27 20:52 UTC, VajraOfIndra commented
> hello guys, is possible to change lines 101-102 to using the `/temp` folder?

You mean _/tmp_? The issue I think is that the GitHub repo would be deleted at the next reboot and Electrs couldn't be simply updated, right?

However, I was wondering why do we use `/home/admin/rust/` to host the Electrs GitHub repo and not the home directory of the Electrs user `/home/electrs` ..?

2022-09-27 22:56 UTC, twofaktor commented
> > hello guys, is possible to change lines 101-102 to using the `/temp` folder?
> 
> You mean `/tmp`? The issue I think is that the GitHub repo would be deleted at the next reboot and Electrs couldn't be simply updated, right?

https://github.com/romanz/electrs/blob/master/doc/upgrading.md#upgrading-manual-installation

`1. Enter your electrs source directory, usually in ~/ but some people like to put it in something like ~/sources. **If you've deleted it, you need to git clone again**.` 

I think we just need to re-clone the git repository in the upgrade process

> 
> However, I was wondering why do we use `/home/admin/rust/` to host the Electrs GitHub repo and not the home directory of the Electrs user `/home/electrs` ..?

I don't know either, maybe due to permissions, and why "rust" as the subfolder name?

2022-09-27 23:57 UTC, twofaktor requested changes
what do you think about this?

2022-09-27 23:57 UTC, twofaktor commented on guide/bitcoin/electrum-server.md
>    $ sudo cp ./target/release/electrs /usr/local/bin/
do you think is better to use this command instead? `sudo install -m 0755 -o root -g root -t /usr/local/bin ./target/release/electrs`

2022-09-28 15:45 UTC, Kixunil commented on guide/bitcoin/electrum-server.md
> +  $ sudo apt install cargo clang cmake build-essential librocksdb-dev
@kristapsk that's really surprising, bullseye is supposed to have 6.11.4. Are you really sure you have bullseye and not a messed up OS? (presumably something wrong with `/etc/apt/sources.list*`)

@VajraOfIndra Unless Raspibolt has something else using the same version of rocksdb 3 is definitely worse than 1. If you can't do 2, do 1.

2022-09-28 15:48 UTC, Kixunil commented
> just need to re-clone the git repository in the upgrade process

Unless there is a lack of storage space to motivate deletion you will save some resources by not re-cloning. If you don't have enough space to store electrs source code you have much bigger problems.

2022-09-28 15:49 UTC, Kixunil commented on guide/bitcoin/electrum-server.md
>    $ sudo cp ./target/release/electrs /usr/local/bin/
`install` is indeed more explicit, which is nice. In practice they do the same thing here.

2022-09-28 16:03 UTC, Kixunil reviewed
Looks mostly good. I definitely recommend double checking the paths though.

2022-09-28 16:03 UTC, Kixunil commented on guide/bitcoin/electrum-server.md
> +  $ git verify-tag v0.9.9
Ideally people Would verify through independent channels (twitter?) that this is indeed the latest version. Otherwise if there is a vulnerable version an attacker could supply that one instead. (OTOH TBF practically exploitable bug is unlikely in `electrs` since it normally doesn't have published RPC. It could go through chain but that'd be very visible.)

2022-10-05 11:34 UTC, twofaktor approved these changes
Some suggestions

2022-10-05 11:34 UTC, twofaktor commented on guide/bitcoin/electrum-server.md
> -  ############### This section is just for location-hidden services ###
Recover this line to standardize with the rest of the guide
Ref: e.g https://raspibolt.org/guide/raspberry-pi/privacy.html#ssh-server

2022-10-05 11:34 UTC, twofaktor commented on guide/bitcoin/electrum-server.md
>    $ sudo cp ./target/release/electrs /usr/local/bin/
Change to: `$ sudo install -m 0755 -o root -g root -t /usr/local/bin ./target/release/electrs`

2022-10-05 11:36 UTC, twofaktor commented on guide/bitcoin/electrum-server.md
>    HiddenServicePort 50002 127.0.0.1:50002
Some wallets like Electrum Wallet Mobile only support TLS connection type with Electrum Servers, It's only to maintain compatibility with these wallets

2022-10-26 16:42 UTC, VajraOfIndra commented on guide/bitcoin/electrum-server.md
>    $ sudo cp ./target/release/electrs /usr/local/bin/
Fixed!
I updated the OP to add it to the list of changes.

2022-10-26 16:44 UTC, VajraOfIndra commented on guide/bitcoin/electrum-server.md
> -  ############### This section is just for location-hidden services ###
Fixed. I find it weird we always include that line though, as the user does not need to add that to the config file.

2022-10-26 16:45 UTC, VajraOfIndra commented
> Some suggestions
Applied your suggestions, PTAL and resolve the conversations if you're happy with teh changes.

2022-10-26 16:49 UTC, VajraOfIndra commented on guide/bitcoin/electrum-server.md
> +  $ sudo apt install cargo clang cmake build-essential librocksdb-dev
I'd go for #2 as it seems to work fine with RasPiOS Lite 64-bit..

@Stadicus wdyt? #2 is recommended but could there be too many version issues and therefore #1 is safer?

2022-10-26 16:50 UTC, VajraOfIndra commented on guide/bitcoin/electrum-server.md
>    $ sudo cp ./target/release/electrs /usr/local/bin/
Thanks both, I replaced `cp` by this `install` command, see below.

2022-10-26 16:54 UTC, VajraOfIndra commented on guide/bitcoin/electrum-server.md
>    HiddenServicePort 50002 127.0.0.1:50002
> Some wallets like Electrum Wallet Mobile only support TLS connection type with Electrum Servers, It's only to maintain compatibility with these wallets

Are you sure?

In their [documentation](https://electrum.readthedocs.io/en/latest/tor.html), they give this example launch command:
`./electrum -1 -s electrums3lojbuj.onion:50001:t -p socks5:localhost:9050`

This is using Tor without TLS connection, right?

2022-10-26 16:58 UTC, VajraOfIndra commented on guide/bitcoin/electrum-server.md
> +  $ git verify-tag v0.9.9
> Ideally people Would verify through independent channels (twitter?) that this is indeed the latest version.

What's the best independent channel that the Electrs dev use to announce their latest release?

2022-10-26 17:04 UTC, VajraOfIndra commented on guide/bitcoin/electrum-server.md
> +  cookie_file= "/data/bitcoin/.cookie"
> Unless the other guides changed the directories this would break `electrs`. To fix permissions problems you can set `ReadOnlyPaths=/home/bitcoin/.bitcoin` in the service file.

How would it break electrs? aren't these options meant to be used to give the absolute paths of the daemon and cookie file?

I added that together with the `--skip-default-conf-files` flag in the service file in order for us to enable the `ProtectHome` option... I'm a bit confused now by what's the best way to reconcile all this. Would love some suggestions.

2022-10-26 17:09 UTC, VajraOfIndra commented
@Stadicus @twofaktor @Kixunil @kristapsk 

Following the latest [feedback ](https://github.com/raspibolt/raspibolt/issues/747#issuecomment-1291646191) from @Stadicus, I updated this PR accordingly. 
The complete and updated list of changes is in the OP.

The remaining unresolved topics are:
- Runtime directory permissions (and why it remains empty even after Electrs is launched)
- How to enable `ProtectHome` in service file while not breaking up Electrs
- (minor) What channel to use to independently verify version of latest release 

I'll try to continue testing these changes on my node buy having an aready installed Electrs i'm not sure I can identify all issues. Would be great to have someone test it from a virgin node.

If you think this PR contains too many changes at once, I could break it down in several PRs to make it easier to test and merge (but I hope it won;t be necesarry! :P)

2022-11-02 20:06 UTC, twofaktor reviewed
Question about no-SSL connection incompatibility throught Tor

2022-11-02 20:06 UTC, twofaktor commented on guide/bitcoin/electrum-server.md
> +  HiddenServicePort 50001 127.0.0.1:50001
Why this change? Some wallets are incompatible with no-SSL connections pairing

2022-11-03 08:50 UTC, Kixunil commented on guide/bitcoin/electrum-server.md
> +  cookie_file= "/data/bitcoin/.cookie"
Is `bitcoind` storing its data in `/data/bitcoin` when configured according to Raspibolt? If not then the path is invalid.

2022-11-03 08:52 UTC, Kixunil commented on guide/bitcoin/electrum-server.md
> +  $ git verify-tag v0.9.9
@romanz what do you think is best here?

2022-11-03 09:00 UTC, Kixunil commented
> Runtime directory permissions (and why it remains empty even after Electrs is launched)

I think you have to specify `ReadWritePaths=/data/electrs`. Or put it into the standardized location `/var/lib/electrs` and set `RuntimeDir=electrs`.

> How to enable `ProtectHome` in service file while not breaking up Electrs

Add `--skip-default-conf-files` to `electrs` invocation and IFF there are any paths in `/home` that electrs **should** access add them to `ReadOnlyPaths`

2022-11-03 09:05 UTC, twofaktor commented on guide/bitcoin/electrum-server.md
>    HiddenServicePort 50002 127.0.0.1:50002
"Electrum Wallet Mobile"

2022-11-03 09:15 UTC, twofaktor commented
> > just need to re-clone the git repository in the upgrade process
> 
> Unless there is a lack of storage space to motivate deletion you will save some resources by not re-cloning. If you don't have enough space to store electrs source code you have much bigger problems.

I highly doubt we don't have enough space to store 1.87MB. In either case, the contents of the /temp folder are removed on every reboot or may be removed after installation.

2022-11-07 12:46 UTC, VajraOfIndra commented
Closing this large PR as lack of feedback on some points/questions.
Will reopen a couple of smaller PR for the agreed-upon changes for Electrs.

2022-11-07 12:46 UTC, closed without merging