V3 testing complete
raspibolt/raspibolt pull request #1103
Opened 2022-09-26 21:25 UTC by Mynima

### What
Made a few simple updates and tested for compatibility with v3.

- Swapped cd /home/admin/download for cd /tmp/
- Minor text updates
- Confirmed testing complete and status updated

### Why
Having a go at contributing

2022-09-26 21:46 UTC, kristapsk approved these changes
utACK

2022-09-27 09:34 UTC, twofaktor approved these changes
tACK --> All tested and worked well for me, but I have the next suggestion in the comment below

2022-09-27 09:44 UTC, twofaktor requested changes
I think that is better drop-out $ nano /home/admin/.bashrc and put it in a different line

2022-09-27 09:44 UTC, twofaktor commented on guide/bonus/raspberry-pi/command-line.md
>    `$ nano /home/admin/.bashrc`
I think that is better drop-out `$ nano /home/admin/.bashrc` and put it in a different line, it would stay like this:

* Open and edit `.bashrc` as shown below, save and exit
  ```sh
  $ nano /home/admin/.bashrc
  ```
  ```bash
  # enable color prompt (uncomment)
  # enable color prompt (uncomment, if commented out)
  force_color_prompt=yes
  # pimp prompt (replace the PS1 line)
  # pimp prompt (comment/replace the PS1 line)
  PS1="${debian_chroot:+($debian_chroot)}\[\e[33m\]\u \[\033[01;34m\]\w\[\e[33;40m\] ₿\[\e[m\] "
  # set "ls" to always use the -la option (insert at the end of the file)
  # set "ls" to always use the -la option, to list details of all files (including hidden), as default
  # simply insert the following line at the end of the file, or replace existing "alias ls='ls --color=auto'" if already 
  present 
  in the "enable color support of ls" section
  alias ls='ls -la --color=always'
  ```

2022-09-27 10:01 UTC, Mynima commented on guide/bonus/raspberry-pi/command-line.md
>    `$ nano /home/admin/.bashrc`
Agreed, that would def look cleaner. 

Now you've got me trying to learn how to use Github to collaborate, only really used it for solo work so far, haha!

2022-09-27 10:06 UTC, Mynima reviewed
Agreed, makes it cleaner to read/execute

2022-09-27 16:56 UTC, twofaktor approved these changes
tACK

2022-09-27 20:28 UTC, VajraOfIndra reviewed
Thanks for your first contribution and upgrading this outdated guide to v3! 👏 

Just a nit, could we also have the `source` command in its own block of code..? :) 

> * Reload configuration
> 
>   ```sh
>   $ source /home/admin/.bashrc
>   ```

2022-09-27 20:34 UTC, twofaktor commented
Line 49/52:
````sh
$ source /home/admin/.bashrc
````

2022-09-28 06:32 UTC, Mynima commented
Agreed, more consistent moving reload of .bashrc to a separate code block.

2022-09-29 09:34 UTC, VajraOfIndra commented
I think it's ready for the Merge! 🎉 

Thanks a lot for your first contribution, awesome work!

2022-09-29 09:34 UTC, merged