[BUG] Fix LNBits installation bug + misc. improvements
raspibolt/raspibolt pull request #1113
Opened 2022-10-02 21:14 UTC by VajraOfIndra

#### What

The main goal of this PR is to fix a bug in the installation of LNBits. The guide is currently missing the following command: `./venv/bin/python build.py` as is shown in the [LNBits installation guidelines](https://github.com/lnbits/lnbits/blob/main/docs/guide/installation.md#option-3-venv).

I also removed the installation command `./venv/bin/pip install pylightning` because it is not mentionned in the instructions.. is it still needed?

This PR adds this comamnd after editing the configuration file.

This PR contains also the followinh minor edits:
- Replaces the LNBits data folder name from `/data/LNBits` to `/data/lnbits` -> to follow naming convention so far (only small letters)
- Switching from creating a config file from scratch to copying and editing the existing example file -> it allows for all the configuration options to be present for the user in case they want to tweak it.
- Added a selection of the colour theme with an illustration of the what the colours are -> because the names of the themes are meaningless
- Switched from NGINX to nginx -> for uniformity between guides
- Added a "LNBits in action" section -> a short section to explain the first steps of creating a wallet and pointing to useful resources for the user to learn more about the extensions and LNBit wallets
- Updated the Upgrade section to find the latest version

### Why

The guide is NOT working as it is at the moment.

#### Scope

- [ ] significant change to core configuration
- [ ] independent bonus guide
- [x] simple bug fix

#### Test & maintenance

To be tested with a new installation of LNBits from scratch.

2022-10-03 10:26 UTC, twofaktor requested changes
some suggestions!

2022-10-03 10:26 UTC, twofaktor commented on guide/bonus/lightning/lnbits.md
>    $ python3 -m venv venv
Line 111-112 why this? official guide installation says this:
```
git clone https://github.com/lnbits/lnbits-legend.git
cd lnbits-legend/
```
https://github.com/lnbits/lnbits/blob/main/docs/guide/installation.md#option-3-venv

2022-10-03 10:26 UTC, twofaktor commented on guide/bonus/lightning/lnbits.md
> +  $ cp .env.example .env
Why this? official guide installation says this:
`mkdir data && cp .env.example .env`

2022-10-03 10:35 UTC, VajraOfIndra commented on guide/bonus/lightning/lnbits.md
>    $ python3 -m venv venv
I think it was originally for ease of use, i.e. a shorter GitHub local repo name. But happy to use the official (if very confusing) name. Fixed.

2022-10-03 10:43 UTC, VajraOfIndra commented on guide/bonus/lightning/lnbits.md
> +  $ cp .env.example .env
The second part of the command is identical.

The first part of the command (making the data directory) is made earlier in the guide when we create the `/data/lnbits` dirctory and its symlink in the "lnbits" user home folder.

The default LNBits installation guidelines create the data directory within the GitHub local repository. For us it would be at: `/home/lnbits/lnbits-legend/data` Instead we have it at `/data/lnbits` and have a symlink to it.

2022-10-03 10:46 UTC, VajraOfIndra commented
I forgot to mention that I added the `PartOf=lnd.service` option in the systemd unit file.

This option will automatically shut down LNBits if LND is shut down. But if LNBits is stopped, LND is NOT stopped. And if LNBits is started but LND is not, it does NOT ask LND to start (to avoid unwanted start of LND), contrary to `Wants=` which I removed for this reason.

2022-10-03 11:24 UTC, twofaktor commented
> I forgot to mention that I added the `PartOf=lnd.service` option in the systemd unit file.
> 
> This option will automatically shut down LNBits if LND is shut down. But if LNBits is stopped, LND is NOT stopped. And if LNBits is started but LND is not, it does NOT ask LND to start (to avoid unwanted start of LND), contrary to `Wants=` which I removed for this reason.

Amazing very helpful! Could we apply this parameter in BTC RPC Explorer, Fulcrum/Electrs, and other services that depend on the other services? eg. BTC RPC Explorer depends on Bitcoind + Electrs/Fulcrum, Fulcrum/Electrs depend on bitcoind, etc...

2022-10-03 14:01 UTC, VajraOfIndra commented
> Amazing very useful! Could we apply this parameter too in BTC RPC Explorer, Fulcrum/Electrs, and other services that depend on the other services? eg. BTC RPC Explorer depends on Bitcoind + Electrs/Fulcrum, Fulcrum/Electrs depend on bitcoind, etc...

Yes, I think it'd make more sense. It would also fix the BTC RPC Explorer mishandling of the cookie file, see [comment here in #848](https://github.com/raspibolt/raspibolt/issues/848#issuecomment-1256046700).

2022-10-04 13:47 UTC, blckbx commented on guide/bonus/lightning/lnbits.md
>    $ python3 -m venv venv
they recently renamed the repo: `https://github.com/lnbits/lnbits.git` so we can just clone without renaming.

2022-10-04 14:10 UTC, blckbx reviewed
LGTM, few nits and changes due to gh repo renaming

2022-10-04 14:10 UTC, blckbx commented on guide/bonus/lightning/lnbits.md
> +  LND_REST_MACAROON="/home/bob/.config/Zap/lnd/bitcoin/mainnet/wallet-1/data/chai>
paths seems cut off

2022-10-04 14:10 UTC, blckbx commented on guide/bonus/lightning/lnbits.md
> +  $ chmod 600 /home/lnbits/lnbits-legend/.env
path adjustment 
```suggestion
  $ chmod 600 /home/lnbits/lnbits/.env
```

2022-10-04 14:10 UTC, blckbx commented on guide/bonus/lightning/lnbits.md
> +  $ cd ~/lnbits-legend
```suggestion
  $ cd ~/lnbits
```

2022-10-04 14:10 UTC, blckbx commented on guide/bonus/lightning/lnbits.md
> +  WorkingDirectory=/home/lnbits/lnbits-legend
```suggestion
  WorkingDirectory=/home/lnbits/lnbits
```

2022-10-04 14:10 UTC, blckbx commented on guide/bonus/lightning/lnbits.md
> +  ExecStart=/bin/sh -c 'cd /home/lnbits/lnbits-legend && ./venv/bin/uvicorn lnbits.__main__:app --port 5000'
```suggestion
  ExecStart=/home/lnbits/lnbits/venv/bin/uvicorn lnbits.__main__:app --port 5000
```

2022-10-04 14:10 UTC, blckbx commented on guide/bonus/lightning/lnbits.md
> +  $ cd /home/lnbits/lnbits-legend
```suggestion
  $ cd /home/lnbits/lnbits
```

2022-10-04 14:10 UTC, blckbx commented on guide/bonus/lightning/lnbits.md
> +  $ cd lnbits-legend
```suggestion
  $ git clone --branch 0.9.4 https://github.com/lnbits/lnbits
  $ cd lnbits
```

2022-10-04 14:10 UTC, blckbx commented on guide/bonus/lightning/lnbits.md
>    LND_REST_CERT=/home/lnbits/.lnd/tls.cert
```suggestion
  LND_REST_CERT="/home/lnbits/.lnd/tls.cert"
```

2022-10-04 18:42 UTC, twofaktor commented on guide/bonus/lightning/lnbits.md
> +  LND_REST_MACAROON="/home/bob/.config/Zap/lnd/bitcoin/mainnet/wallet-1/data/chai>
```
LND_REST_CERT="/home/bob/.config/Zap/lnd/bitcoin/mainnet/wallet-1/data/chain/bitcoin/mainnet/tls.cert"
LND_REST_MACAROON="/home/bob/.config/Zap/lnd/bitcoin/mainnet/wallet-1/data/chain/bitcoin/mainnet/admin.macaroon or HEXSTRING"
```

2022-10-05 07:19 UTC, VajraOfIndra commented on guide/bonus/lightning/lnbits.md
> +  LND_REST_MACAROON="/home/bob/.config/Zap/lnd/bitcoin/mainnet/wallet-1/data/chai>
Fixed

2022-10-05 07:19 UTC, VajraOfIndra commented
> LGTM, few nits and changes due to gh repo renaming

Thanks, all fixed, PTAL

2022-10-05 07:49 UTC, blckbx approved these changes
utACK 🔥

2022-10-05 09:40 UTC, merged