[UPDATED BONUS GUIDE] Electrum Wallet guide updated to Raspibolt v3 & other fixes
raspibolt/raspibolt pull request #1123
Opened 2022-10-13 15:31 UTC by twofaktor

#### What

The existing Electrum Wallet guide is deprecated and wrong

### Why

This can lead to significant improvements in the correct running of the Raspibolt nodes.

#### How

- Fixed images embedded and delete old images
- Simplified and clarified complete guide and Tor connection
- Updated to the v3 Raspibolt

#### Scope

- [ ] significant change to core configuration
- [X] independent bonus guide
- [ ] simple bug fix

#### Test & maintenance

I tested all and is working fine for me:

#### Animated GIF

![giphy](https://user-images.githubusercontent.com/89636253/195639431-3c66ac45-1250-4aa9-a0e1-42c2d6be187b.gif)

2022-10-22 17:31 UTC, sig-noi reviewed
Changes suggested primarily to improve readability and Mac instructions. Similar config file modification instructions could be added for Windows and Tor connection, or user could be instructed to make Tor changes with GUI after modifying config to work over LAN.

2022-10-22 17:31 UTC, sig-noi commented on guide/bonus/bitcoin/electrum-wallet-desktop.md
> +* For **macOS** follow the next [instructions](https://deepdarkweb.github.io/how-to-install-tor-on-macos-tutorial/){:target="_blank"}
* Mac OS

  * Open the Tor Browser
  * In the Terminal application, run the following command

  ```sh
  /Applications/Electrum.app/Contents/MacOS/run_electrum -1 -s ab...yz.onion:50002:s -p socks5:localhost:9050

2022-10-22 17:31 UTC, sig-noi commented on guide/bonus/bitcoin/electrum-wallet-desktop.md
> +If you start Electrum, after create your wallet, show the blue LED in the bottom right indicating an active connection to your server through Tor.
After creating opening a wallet or creating a new one, Electrum will indicate an active connection to a Tor server with a blue dot in the bottom right corner of the screen.

2022-10-23 08:49 UTC, twofaktor commented on guide/bonus/bitcoin/electrum-wallet-desktop.md
> +* For **macOS** follow the next [instructions](https://deepdarkweb.github.io/how-to-install-tor-on-macos-tutorial/){:target="_blank"}
Normally when you use Tor browser the `9150` port is listening, I don't know if macOS works in the same way 

should it be like that?:

`/Applications/Electrum.app/Contents/MacOS/run_electrum -1 -s ab...yz.onion:50002:s -p socks5:localhost:9150`

2022-10-23 18:18 UTC, twofaktor reviewed
All fixed!

2022-10-23 18:18 UTC, twofaktor commented on guide/bonus/bitcoin/electrum-wallet-desktop.md
> +
Fixed!

2022-10-23 18:18 UTC, twofaktor commented on guide/bonus/bitcoin/electrum-wallet-desktop.md
> +### Connect the Electrum wallet to our own Electrum server by forcing the connection to only one server
Fixed!

2022-10-23 18:18 UTC, twofaktor commented on guide/bonus/bitcoin/electrum-wallet-desktop.md
> +If you use Electrum only within your own home network, you can use the local connection details.
Fixed!

2022-10-23 18:19 UTC, twofaktor commented on guide/bonus/bitcoin/electrum-wallet-desktop.md
> +  * With your new shortcut created after installation in desktop, right-click it and go to "Properties", click shortcut tab at the top bar, in the box named target, put `"-1 -s raspibolt.local:50002:
Fixed!

2022-10-23 18:19 UTC, twofaktor commented on guide/bonus/bitcoin/electrum-wallet-desktop.md
> +There are two options depending on your OS:
Fixed!

2022-10-23 18:19 UTC, twofaktor commented on guide/bonus/bitcoin/electrum-wallet-desktop.md
> +* For **macOS** follow the next [instructions](https://deepdarkweb.github.io/how-to-install-tor-on-macos-tutorial/){:target="_blank"}
Fixed with 9150 port modified!

2022-10-23 18:19 UTC, twofaktor commented on guide/bonus/bitcoin/electrum-wallet-desktop.md
> +If you start Electrum, after create your wallet, show the blue LED in the bottom right indicating an active connection to your server through Tor.
Fixed!

2022-10-23 18:20 UTC, twofaktor commented on guide/bonus/bitcoin/electrum-wallet-desktop.md
> +  * Execute the next command in your Linux terminal
Fixed!

2022-10-23 18:20 UTC, twofaktor commented on guide/bonus/bitcoin/electrum-wallet-desktop.md
> +To make sure Electrum only uses your own server and does not connect to any other public server the first time by accident, we use different methods depending if you are connecting locally or remotel
Fixed!

2022-10-23 18:20 UTC, twofaktor commented on guide/bonus/bitcoin/electrum-wallet-desktop.md
> +If you connect over Tor, make sure that Tor is installed on your regular computer.
Fixed!

2022-10-23 18:20 UTC, twofaktor commented on guide/bonus/bitcoin/electrum-wallet-desktop.md
> +* For **macOS** follow the next [instructions](https://deepdarkweb.github.io/how-to-install-tor-on-macos-tutorial/){:target="_blank"}
Fixed!

2022-10-23 18:20 UTC, twofaktor commented on guide/bonus/bitcoin/electrum-wallet-desktop.md
> +To connect from outside your network over Tor, skip to the next section.
Fixed!

2022-10-23 18:20 UTC, twofaktor commented on guide/bonus/bitcoin/electrum-wallet-desktop.md
> +If you start Electrum, after create your wallet, show the green LED in the bottom right indicating an active connection to your server.
Fixed!

2022-10-24 03:44 UTC, sig-noi commented on guide/bonus/bitcoin/electrum-wallet-desktop.md
> +  nano /Users/<YOUR_PERSONAL_COMPUTER_USERNAME>/.electrum config
nano /Users/<YOUR_PERSONAL_COMPUTER_USERNAME>/.electrum/config

2022-10-24 03:48 UTC, sig-noi approved these changes
ptACK (tested macOS parts, but not linux or windows)

2022-10-24 03:48 UTC, sig-noi commented on guide/bonus/bitcoin/electrum-wallet-desktop.md
> +After creating opening a wallet or creating a new one, Electrum will indicate an active connection to a local server with a green dot in the bottom right corner of the screen.
After opening a wallet or creating a new one, Electrum will indicate an active connection to a local server with a green dot in the bottom right corner of the screen.

2022-10-24 03:48 UTC, sig-noi commented on guide/bonus/bitcoin/electrum-wallet-desktop.md
> +After creating opening a wallet or creating a new one, Electrum will indicate an active connection to a Tor server with a blue dot in the bottom right corner of the screen.
After opening a wallet or creating a new one, Electrum will indicate an active connection to a Tor server with a blue dot in the bottom right corner of the screen.

2022-10-24 09:10 UTC, twofaktor commented on guide/bonus/bitcoin/electrum-wallet-desktop.md
> +After creating opening a wallet or creating a new one, Electrum will indicate an active connection to a local server with a green dot in the bottom right corner of the screen.
Fixed!

2022-10-24 09:10 UTC, twofaktor commented on guide/bonus/bitcoin/electrum-wallet-desktop.md
> +After creating opening a wallet or creating a new one, Electrum will indicate an active connection to a Tor server with a blue dot in the bottom right corner of the screen.
Fixed!

2022-10-24 10:36 UTC, twofaktor commented
All fixed! is ready?

2022-10-24 19:36 UTC, VajraOfIndra commented on guide/bonus/bitcoin/electrum-wallet-desktop.md
> +To preserve privacy, we will constrain Electrum to only connect to a single server (RaspiBolt). How to do this depends on whether you are connecting via Local Area Network or via Tor and the operatin
```suggestion
To preserve privacy, we will constrain Electrum to only connect to a single server (your RaspiBolt). How to do this depends on whether you are connecting via Local Area Network or via Tor and the operating system that you use on your regular computer.
```

2022-10-24 20:02 UTC, VajraOfIndra requested changes
Nice upgrade!

Tested it on Windows, a few comments below.

2022-10-24 20:11 UTC, VajraOfIndra commented on guide/bonus/bitcoin/electrum-wallet-desktop.md
> +🚨 Ensure you have put check `"Use Tor proxy at port 9050"` or `"Use Tor proxy at port 9150"` in `"Proxy"` settings tab
Is this needed? I could connect to the server without ticking this..

2022-10-24 22:03 UTC, twofaktor commented on guide/bonus/bitcoin/electrum-wallet-desktop.md
> +  * and modify the file to include the following lines:
Modifying the configuration file after startup does not prevent it from first connecting to public servers and sharing information with them about our wallet, so it must be started with the appropriate flags

2022-10-24 22:09 UTC, twofaktor commented on guide/bonus/bitcoin/electrum-wallet-desktop.md
> +🚨 Ensure you have put check `"Use Tor proxy at port 9050"` or `"Use Tor proxy at port 9150"` in `"Proxy"` settings tab
Not in my case.

2022-10-24 22:11 UTC, twofaktor commented on guide/bonus/bitcoin/electrum-wallet-desktop.md
> +To preserve privacy, we will constrain Electrum to only connect to a single server (RaspiBolt). How to do this depends on whether you are connecting via Local Area Network or via Tor and the operatin
Fixed!

2022-10-24 22:11 UTC, twofaktor commented on guide/bonus/bitcoin/electrum-wallet-desktop.md
> +
Fixed!

2022-10-24 22:12 UTC, twofaktor commented on guide/bonus/bitcoin/electrum-wallet-desktop.md
> +  ```sh
Not changed

2022-10-24 22:12 UTC, twofaktor commented on guide/bonus/bitcoin/electrum-wallet-desktop.md
> +  * After using this command for the first run, close Electrum, and open the Electrum config file with the following customized command:
Fixed!

2022-10-24 22:12 UTC, twofaktor commented on guide/bonus/bitcoin/electrum-wallet-desktop.md
> +  C:\Program Files (x86)\Electrum\electrum.exe -1 -s raspibolt.local:50002:s
Fixed!

2022-10-24 22:12 UTC, twofaktor commented on guide/bonus/bitcoin/electrum-wallet-desktop.md
> +To connect over Tor, you will need to have Tor installed on the client computer running Electrum.
Fixed!

2022-10-24 22:12 UTC, twofaktor commented on guide/bonus/bitcoin/electrum-wallet-desktop.md
> +Now, execute Electrum Wallet choosing the correct way depending on your OS
Fixed!

2022-10-24 22:14 UTC, twofaktor commented on guide/bonus/bitcoin/electrum-wallet-desktop.md
> +  * Find the new Electrum desktop shortcut, right-click it and go to "Properties", click shortcut tab at the top bar, in the box named target, put "-1 -s raspibolt.local:50002:s" after "electrum.exe"
Fixed!

2022-10-24 22:16 UTC, twofaktor commented on guide/bonus/bitcoin/electrum-wallet-desktop.md
> +  nano /Users/<YOUR_PERSONAL_COMPUTER_USERNAME>/.electrum/config
I don't know, I couldn't test in macOS, maybe @sig-noi could help us

2022-10-25 00:59 UTC, sig-noi commented on guide/bonus/bitcoin/electrum-wallet-desktop.md
> +  nano /Users/<YOUR_PERSONAL_COMPUTER_USERNAME>/.electrum/config
This command is specifically for macOS.

2022-10-25 03:20 UTC, sig-noi reviewed
Config mods work fine for constraining Electrum to Raspibolt on my mac.

2022-10-25 03:20 UTC, sig-noi commented on guide/bonus/bitcoin/electrum-wallet-desktop.md
> +  * and modify the file to include the following lines:
It doesn't? Config mods seem to do that fine on my mac.
<img width="612" alt="Screen Shot 2022-10-24 at 8 16 09 PM" src="https://user-images.githubusercontent.com/94819106/197674187-adcfce24-021e-4e3d-a0c3-97d696a92e5c.png">

2022-10-25 08:00 UTC, VajraOfIndra commented on guide/bonus/bitcoin/electrum-wallet-desktop.md
> +  nano /Users/<YOUR_PERSONAL_COMPUTER_USERNAME>/.electrum/config
It works as well for Windows. But in Windows, we have to tell teh user to then delete the flags that they added earlier in the shortcut path (otherwise they override whatever is in the config file).

It's all a bit confusing, particulalry as we then have the Tor section where we don't mention the config file at all.

Not sure what 's the clearest approach is here! :)

2022-10-25 08:25 UTC, twofaktor commented on guide/bonus/bitcoin/electrum-wallet-desktop.md
> +  nano /Users/<YOUR_PERSONAL_COMPUTER_USERNAME>/.electrum/config
> It works as well for Windows. But in Windows, we have to tell teh user to then delete the flags that they added earlier in the shortcut path (otherwise they override whatever is in the config file).
> 
> It's all a bit confusing, particulalry as we then have the Tor section where we don't mention the config file at all.
> 
> Not sure what 's the clearest approach is here! :)

It is the only way that it does not connect to public servers apart from yours after creating your wallet. If you start the first time the GUI connects you with your node and 9 public servers as well and your public key is shared if you modify the config file after the first install the pubkey has already been shared. The only way around this is by indicating these parameters in the startup command in Linux or in the shortcut target in Windows

2022-10-25 09:40 UTC, twofaktor commented on guide/bonus/bitcoin/electrum-wallet-desktop.md
> +  nano /Users/<YOUR_PERSONAL_COMPUTER_USERNAME>/.electrum/config
> > It is the only way that it does not connect to public servers apart from yours after creating your wallet.
> 
> Yes, that part is great. First time we launch we use the flags in the shortcut path or in the terminal command.
> 
> > So configuring the conf file is never necessary if you want to prevent your Electrum from connecting to public servers
> 
> This is the part I don't know how we should handle, i.e. for the next launches of Electrum (not the first one). Either we:
> 
> 1. Do NOT mention the possibility of modifying the conf file. PROS: guide is clearer, less risks of confusion. CONS: the terminal command users (for Linuc and Mac) always have to remember to use the flags)
> 2. We DO mention the possibility to modify the conf file. CONS: we have to explain how to do it for each OS (different paths, different text editors), and we have to remove the flags from the shortcut path (for Windows) and from the terminal commands (for Linux and Mac) as they would override the newly added config file options

For the next launches, you can reuse the custom shortcut or not, modifying the config file is still irrelevant as it will only be modified with the configuration through the interface for the next settings you want.

- First launch: you start by generating and modifying the config file so that it connects only to your server through shortout (configuration of the config file through the shortout)

- During the use: configuration of the config file through the interface (configuration of the config file through the interface)

- Next launches: launch reiterating your own server configuration through the shortcout or use the original shourtcut since the config file is already generated and preconfigured above to connect with your own server

if you realize, you never need to configure the config file using an editor

> My point is that presently, the section about modifying the config file is a bit confusing (why is it for Mac only?).

I don't know about the Mac option, was @sig-noi who proposed it

> I'd prefer option 1 for sake of simplicity but fine with option 2 as well.
> 
> I'll rest my case as we seem to not understand each other. Happy to merge as is if you want.

2022-10-25 09:43 UTC, VajraOfIndra approved these changes
LGTM, tACK

2022-10-25 09:44 UTC, VajraOfIndra commented on guide/bonus/bitcoin/electrum-wallet-desktop.md
> +![Electrum Wallet Tor](../../../images/electrum-wallet-tor.PNG)
```suggestion
![Electrum Wallet Tor](../../../images/electrum-wallet-tor.png)
```

Broken image path

2022-10-25 09:48 UTC, VajraOfIndra commented on guide/bonus/bitcoin/electrum-wallet-desktop.md
> +![Electrum Wallet Tor](../../../images/electrum-wallet-tor.PNG)
@twofaktor ready to merge but just remebered that broken picture.. double check but I believe there is a typo in the path, I suggested a fix. Once fixed, I'll merge your PR.

2022-10-25 09:56 UTC, merged