[NEW BONUS GUIDE]  Amboss.space heartbeat pings without Thunderhub
raspibolt/raspibolt pull request #1135
Opened 2022-10-27 17:10 UTC by satsHIVE

#### What

Easy to use script to send heartbeat pings to the amboss.space monitoring service

### Why

After that recent [announcement](https://twitter.com/ambosstech/status/1585290480769650690?s=61&t=wgPBC4NzIohyPoOJ-TlNkA) from amboss.space, people started questioning the need for Thunderhub. If TH is not available, the only remaining option is a "manual" ping to be sent to the amboss monitoring service.

#### How

Simple bash script executed on predefined intervals via cronjob.

#### Scope

- [ ] significant change to core configuration
- [x] independent bonus guide
- [ ] simple bug fix

Fixes # (link issue)

#### Test & maintenance

Following the instructions, check if the status in the amboss health dashboard is being updated. One should disable the Thunderhub pings if they are activated from there.

#### Animated GIF (optional)

n/a

2022-10-27 17:22 UTC, twofaktor commented
If not enable channel balance sending info in ThunderHub, ThunderHub does not send this info to Amboss by default. We shouldn't worry about this, this works the same as health checks and backups options, so I think is not a privacy risk to the RaspiBolt nodes

Don't trust, verify: https://github.com/apotdevin/thunderhub/blob/master/src/client/src/views/amboss/Balances.tsx#L26-L30

2022-10-27 17:30 UTC, satsHIVE commented
Can confirm what you say. Checked with my installation of 0.13.16. 
On the other hand, though, I found reporting via the script way more reliable than TH. Used this script for the recent weeks and the false-positives in the reporting fell by 90% at least. From ~10x10min reported outages per day in the past (while my nod is actually routing) I fell to 1-2 a week.

2022-10-27 17:32 UTC, twofaktor commented
This is not necessary. If you do not enable the sending of channel balance information in ThunderHub, ThunderHub does not send this information to Amboss by default. We shouldn't worry about this, it works the same as the health check and backup options, so I think it's not a privacy risk for the RaspiBolt nodes if we don't enable it.

https://github.com/apotdevin/thunderhub/blob/master/src/client/src/views/boss/Balances.tsx#L26-L30

Maybe we could add a notice in the Thunderhub extras section: https://raspibolt.org/guide/bonus/lightning/thunderhub.html#extras

2022-10-27 17:39 UTC, satsHIVE commented
Ok, the "why" become a bit misleading, but the point of this at the end is still to provide the ability to use the hatcheck status without TH.

2022-10-27 17:45 UTC, twofaktor commented
> Can confirm what you say. Checked with my installation of 0.13.16. On the other hand, though, I found reporting via the script way more reliable than TH. Used this script for the recent weeks and the false-positives in the reporting fell by 90% at least. From ~10x10min reported outages per day in the past (while my nod is actually routing) I fell to 1-2 a week.

I agree with you, I usually get a lot of false-positives with Thunderhub -> Amboss health check method.

I'll try to leave you a review. First I think I can see, is it necessary to create a unique user for this use? In other similar guides, this step was not included

refs: https://raspibolt.org/guide/lightning/channel-backup.html
https://raspibolt.org/guide/bonus/lightning/lntop.html

2022-10-27 17:55 UTC, satsHIVE commented
I consider it more cleaner approach. If we set up a user, it is way easier to uninstall by only deleting the user. We basically set the files and the cron in the user, so therefore no leftovers after the “uninstallation”.

2022-10-27 18:09 UTC, satsHIVE commented on guide/bonus/lightning/ambossping.md
> +  $ userdel -r ambossping
It is executed with the “root” user.

2022-10-27 18:11 UTC, twofaktor commented
I think the Thunderhub -> Amboss method issue may be due to issues with Tor, as we have this line configured for the Thunderhub config:

`TOR_PROXY_SERVER=socks://127.0.0.1:9050`

It usually fails me at the time I've had problems with Tor. 

BTW: Is Tor used in this guide for the communication of our node with Amboss?

2022-10-27 18:17 UTC, twofaktor requested changes
a suggestion in code

2022-10-27 18:17 UTC, twofaktor commented on guide/bonus/lightning/ambossping.md
> +
add: 

`exit`

to return to the "admin" user

2022-10-27 18:24 UTC, satsHIVE commented on guide/bonus/lightning/ambossping.md
> +
Fixed. Doesn't need to exit the current session, so adapted the next paragraph.

2022-10-27 18:24 UTC, satsHIVE commented on guide/bonus/lightning/ambossping.md
> +  $ userdel -r ambossping
fixed

2022-10-28 08:42 UTC, blckbx commented on guide/bonus/lightning/ambossping.md
> +  JSON="{\"query\": \"mutation HealthCheck(\$signature: String!, \$timestamp: String!) { healthCheck(signature: \$signature, timestamp: \$timestamp) }\", \"variables\": {\"signature\": \"$SIGNATURE\"
JSON string is cut off after `\"ti`

2022-10-28 08:45 UTC, blckbx reviewed
incomplete JSON string

2022-10-28 08:47 UTC, satsHIVE commented on guide/bonus/lightning/ambossping.md
> +  JSON="{\"query\": \"mutation HealthCheck(\$signature: String!, \$timestamp: String!) { healthCheck(signature: \$signature, timestamp: \$timestamp) }\", \"variables\": {\"signature\": \"$SIGNATURE\"
Thanks, found it. Should be OK now.

2022-10-29 19:43 UTC, VajraOfIndra commented
> Ok, the "why" become a bit misleading, but the point of this at the end is still to provide the ability to use the hatcheck status without TH.

Good point.. as I don't use ThunderHub, I was not even aware that there was such a thing as a Amboss monitoring service.. this is definitely a useful bonus guide 💯

2022-10-30 19:20 UTC, kristapsk commented on guide/bonus/lightning/ambossping.md
> +  echo "$JSON" | curl -s -f --data-binary @- -H "Content-Type: application/json" -X POST --output /dev/null $URL
Can and should use Tor here.
```suggestion
  echo "$JSON" | torsocks curl -s -f --data-binary @- -H "Content-Type: application/json" -X POST --output /dev/null $URL
```

2022-10-30 19:20 UTC, kristapsk commented on guide/bonus/lightning/ambossping.md
> +  ```ini
This is a shell script.
```suggestion
  ```sh
```

2022-10-30 19:20 UTC, kristapsk commented on guide/bonus/lightning/ambossping.md
> +
Should add `chmod +x /home/ambossping/ping.sh` somewhere here, otherwise `./ping.sh` below will not work.

2022-10-30 19:30 UTC, satsHIVE commented on guide/bonus/lightning/ambossping.md
> +  echo "$JSON" | curl -s -f --data-binary @- -H "Content-Type: application/json" -X POST --output /dev/null $URL
I think I could add it as an option. Some may find it unnecessary - either not really concerned by revealing to amboss or when behind a VPN for example. wdyt?

2022-10-30 19:43 UTC, kristapsk commented on guide/bonus/lightning/ambossping.md
> +  echo "$JSON" | curl -s -f --data-binary @- -H "Content-Type: application/json" -X POST --output /dev/null $URL
RaspiBolt guide defaults to LND being Tor only. No other guides should reveal it's true IP address to other guides by default.

2022-10-30 19:51 UTC, satsHIVE commented on guide/bonus/lightning/ambossping.md
> +  echo "$JSON" | curl -s -f --data-binary @- -H "Content-Type: application/json" -X POST --output /dev/null $URL
Fair enough, but I will have to test it before I change it here. Thanks for the review.

2022-10-30 20:06 UTC, kristapsk commented on guide/bonus/lightning/ambossping.md
> +  echo "$JSON" | curl -s -f --data-binary @- -H "Content-Type: application/json" -X POST --output /dev/null $URL
Of course, you should verify, not trust! :)

2022-10-30 20:27 UTC, satsHIVE commented on guide/bonus/lightning/ambossping.md
> +
fixed

2022-10-30 20:30 UTC, VajraOfIndra commented on guide/bonus/lightning/ambossping.md
> +  chmod chmod +x /home/ambossping/ping.sh
```suggestion
  $ chmod chmod +x /home/ambossping/ping.sh
```

2022-11-01 08:48 UTC, satsHIVE commented on guide/bonus/lightning/ambossping.md
> +  echo "$JSON" | curl -s -f --data-binary @- -H "Content-Type: application/json" -X POST --output /dev/null $URL
Ok, I have tested it as suggested but I have to say that results are expected. The service turns into TOR service monitoring rather than node monitoring - quite a lot of false-positives where an OFFLINE status is reported, but the node is running just fine doing RBs and FWs. I will maybe append a notification about that to the guide.

2022-11-01 09:08 UTC, kristapsk commented on guide/bonus/lightning/ambossping.md
> +  echo "$JSON" | curl -s -f --data-binary @- -H "Content-Type: application/json" -X POST --output /dev/null $URL
Ok, then keep it as clearnet, with note about that. If user still wants to use Tor here, alternative approach is to add `torsocks /home/ambossping/ping.sh` to cron instead of `/home/ambossping/ping.sh`.

2022-11-01 14:48 UTC, satsHIVE commented on guide/bonus/lightning/ambossping.md
> +  echo "$JSON" | curl -s -f --data-binary @- -H "Content-Type: application/json" -X POST --output /dev/null $URL
Updated.

2022-11-01 16:47 UTC, VajraOfIndra commented on guide/bonus/lightning/ambossping.md
> +  🚨 Setting up the cronjob like this will send the pings via clearnet - meaning amboss.space will know where the ping comes from. You can prevent revealing this information by either tunneling all tr
```suggestion
  🚨 Setting up the cronjob like this will send the pings via clearnet - meaning amboss.space will know where the ping comes from. You can prevent revealing this information by either tunneling all traffic of your node via VPN or setup your cronjob to use Tor. Be aware that running the ping via Tor will cause some false-positives depending on the health of the Tor network status and availability, which will not represent the availability of your node.
```

[juts a nit](https://support.torproject.org/about/why-is-it-called-tor/) ;D

2022-11-01 20:44 UTC, kristapsk commented
ACK

2022-11-04 09:54 UTC, VajraOfIndra commented on guide/bonus/lightning/ambossping.md
> +  $ ./ping.sh
The warning about revealing one's IP address to Amboss is placed later on for the cron job. But this step here would have already leaked the IP, right?

Is it possible to torify this step?

2022-11-04 10:00 UTC, blckbx commented on guide/bonus/lightning/ambossping.md
> +  * * * * * torsocks /home/ambossping/ping.sh >> /home/ambossping/ping.log
```suggestion
  * * * * * /usr/bin/torsocks /home/ambossping/ping.sh >> /home/ambossping/ping.log
```
I think this needs to be specified.

2022-11-04 10:03 UTC, satsHIVE commented on guide/bonus/lightning/ambossping.md
> +  * * * * * torsocks /home/ambossping/ping.sh >> /home/ambossping/ping.log
Worked for me even without it, but let's keep it that way. Thanks.

2022-11-04 10:11 UTC, satsHIVE commented on guide/bonus/lightning/ambossping.md
> +  $ ./ping.sh
fixed

2022-11-04 10:24 UTC, blckbx commented on guide/bonus/lightning/ambossping.md
> +  $ /usr/bin/torsocks /home/ambossping/ping.sh
This is not necessary, only cron has no user-context and requires exact paths. 
You could leave this at `./ping.sh`.

2022-11-04 10:28 UTC, satsHIVE commented on guide/bonus/lightning/ambossping.md
> +  $ /usr/bin/torsocks /home/ambossping/ping.sh
fixed

2022-11-04 11:22 UTC, blckbx approved these changes
LGTM

2022-11-04 11:41 UTC, merged