[NEW BONUS GUIDE] Install / Update / Uninstall common languages
raspibolt/raspibolt pull request #1150
Opened 2022-11-04 16:25 UTC by satsHIVE

#### What

As discussed with @VajraOfIndra, this is a section in the guides to collect all the installations of common prerequisites across the other guides. 

### Why

Central management of the guides will allow easier maintenance without the need to adapt individual application and tools guides.

#### How

Prepare guides for the common languages across the guides and collect them into one section.

#### Scope

- [ ] significant change to core configuration
- [x] independent bonus guide
- [ ] simple bug fix

Fixes # (link issue)

#### Test & maintenance

Only the language guides will be updated on new versions of the languages or changes in the overall process. Tools and app guides shall not be touched.

#### Animated GIF (optional)

n/a

2022-11-06 15:10 UTC, blckbx commented
@VajraOfIndra @kristapsk 

Just a thought for every guide in which checksums are NOT verified automatically, so you have to manually verify the checksum char by char. Instead of doing so, can we do something like this?
```sh
$ echo "99de2fe112a52ab748fb175edea64b313a0c8d51d6157dba683a6be163fd5eab go1.19.3.linux-arm64.tar.gz" | sha256sum --check
go1.19.3.linux-arm64.tar.gz: OK
```
Example is taken from this PR.

2022-11-06 22:18 UTC, VajraOfIndra requested changes
I really like the idea of starting to provide these languages guides 💯 
I think they might help us make the other guides clearer and reduce the number of issues users might encounter with outdated language versions or confusions with the various ways of installing or updating a language.

_In term of this specific Go PR:_
LGTM, maybe a couple of needed changes (the sudo afaik) + a few nits below (feel free to keep the ones you like and ignore the ones you don't).

2022-11-06 22:18 UTC, VajraOfIndra commented on guide/bonus/lightning/regolancer.md
>  ## Install GO
```suggestion
## Install Go
```

2022-11-06 22:59 UTC, VajraOfIndra approved these changes
LGTM, tACK!

2022-11-06 23:06 UTC, VajraOfIndra commented
> Just a thought for every guide in which checksums are NOT verified automatically, so you have to manually verify the checksum char by char. Instead of doing so, can we do something like this?
> 
> ```shell
> $ echo "99de2fe112a52ab748fb175edea64b313a0c8d51d6157dba683a6be163fd5eab go1.19.3.linux-arm64.tar.gz" | sha256sum --check
> go1.19.3.linux-arm64.tar.gz: OK
> ```

Sounds like a nice solution yes..

@satsHIVE would you like to implement that change in your guide before we merge it..?

2022-11-06 23:10 UTC, satsHIVE commented
Yes, will do. But can in a few hours if not an issue.

2022-11-07 08:08 UTC, satsHIVE commented
sha256sum aligned to suggestion. @VajraOfIndra @blckbx

2022-11-07 08:33 UTC, VajraOfIndra commented on guide/bonus/raspberry-pi/golang.md
> +  $ $ echo "99de2fe112a52ab748fb175edea64b313a0c8d51d6157dba683a6be163fd5eab go1.19.3.linux-arm64.tar.gz" | sha256sum --check
```suggestion
  $ echo "99de2fe112a52ab748fb175edea64b313a0c8d51d6157dba683a6be163fd5eab go1.19.3.linux-arm64.tar.gz" | sha256sum --check
```

2022-11-07 08:37 UTC, VajraOfIndra commented on guide/bonus/lightning/circuit-breaker.md
> +* To [install Go](https://raspibolt.org/guide/bonus/raspberry-pi/golang.html#install-go) follow the instructions provided in the bonus guide.
```suggestion
* To [install Go](../raspberry-pi/golang.md#install-go) follow the instructions provided in the bonus guide.
```

2022-11-07 08:39 UTC, VajraOfIndra commented on guide/bonus/lightning/regolancer.md
> +* To [install Go](https://raspibolt.org/guide/bonus/raspberry-pi/golang.html#install-go) follow the instructions provided in the bonus guide.
```suggestion
* To install Go follow the instructions provided in the [bonus guide](../raspberry-pi/golang.md#install-go).
```

2022-11-07 08:47 UTC, VajraOfIndra commented
Let's go to master! 🎉

2022-11-07 08:47 UTC, merged