Add banner support
raspibolt/raspibolt pull request #1155
Opened 2022-11-06 14:27 UTC by DanielPX1

#### What

Add custom banner option for Fulcrum users:)

### Why

To have fun and be creative with own server

#### How

By adding following steps stated in the guide

#### Scope

- [ ] test & review

#### Test & maintenance

By following the guide and testing on own device

2022-11-06 14:48 UTC, twofaktor requested changes
Only one bug

2022-11-06 14:48 UTC, twofaktor commented on guide/bonus/bitcoin/fulcrum.md
> +banner = /data/fulcrum/banner/banner.txt
change to:

`banner = /data/fulcrum/banner.txt`

2022-11-06 14:54 UTC, twofaktor reviewed
Comments and suggestion of changes

2022-11-06 14:54 UTC, twofaktor commented on guide/bonus/bitcoin/fulcrum.md
> +
is that extra final space necessary?

2022-11-06 14:54 UTC, twofaktor commented on guide/bonus/bitcoin/fulcrum.md
> +<img src="../../../images/Fulcrum_Banner.png" width=50% height=50%>
Change to:
`![Fulcrum banner](../../../images/Fulcrum_Banner.png)`

2022-11-06 15:01 UTC, DanielPX1 commented on guide/bonus/bitcoin/fulcrum.md
> +banner = /data/fulcrum/banner/banner.txt
Updated (y)

2022-11-06 15:01 UTC, DanielPX1 commented on guide/bonus/bitcoin/fulcrum.md
> +
Yeah, you are right, its deleted now. But its just demonstration:)

2022-11-06 15:02 UTC, DanielPX1 commented on guide/bonus/bitcoin/fulcrum.md
> +<img src="../../../images/Fulcrum_Banner.png" width=50% height=50%>
![]() Format does not support resizing, will have to resize outside GitHub

2022-11-06 15:50 UTC, DanielPX1 commented
It is a very small improvement with only several commands, ready 4 test/review:)

2022-11-06 20:53 UTC, VajraOfIndra requested changes
Great fun addition! love it ❤️ 

LGTM, just a couple of nits.

Also, could you maybe add the 2 spaces in front of the code blocks that are below the bullet points..? (couldn't do it in the review as the three back ticks messes up with the GitHub comment formatting)

2022-11-06 20:53 UTC, VajraOfIndra commented on guide/bonus/bitcoin/fulcrum.md
> +* Create and open "banner.txt" file inside Fulcrum directory
```suggestion
* Create and open `banner.txt` file inside Fulcrum directory
```

Afaik, I think we usually use code formattting for file names, same as what you did for fulcrum.conf at line 471

2022-11-06 20:53 UTC, VajraOfIndra commented on guide/bonus/bitcoin/fulcrum.md
> +* Paste your own creation into "banner.txt". Save and exit
```suggestion
* Paste your own creation into `banner.txt`. Save and exit
```

2022-11-07 10:57 UTC, DanielPX1 commented
> Great fun addition! love it ❤️
> 
> LGTM, just a couple of nits.
> 
> Also, could you maybe add the 2 spaces in front of the code blocks that are below the bullet points..? (couldn't do it in the review as the three back ticks messes up with the GitHub comment formatting)

Glad to hear! changed the " to `, sorry however I am not sure I understand with the spaces?

2022-11-07 12:36 UTC, VajraOfIndra commented
> Sorry, I am not sure I understand the one with the spaces?

Like here, in front of all the lines that form a code block, we usually put two blank spaces to align with the start of the text in the bullet point above (like in the rest of the Fulcrum guide for example)
![image](https://user-images.githubusercontent.com/86242283/200310862-9eee463e-abd5-467c-a10a-008240a68131.png)

> PS: Just found out my Fulcrum.service did not start only with Electrs service being disabled, because it was also necessary to remove Electrs Nginx config. Should I add this info to the guide? Or will we count that user runs only one Electrs implementation?

Disable alone is not enough afail, it simply stops Electrs to be started when booting/rebooting... If a user has Electrs running, they would also need to stop the service. So both stop and disable are needed. 

Regarding the nginx reverse proxy, are you using it for Fulcrum? if not, why not? (just curious) I'm not sure to understand why removing the nginx reverse proxy config file is ncessary for Fulcrum to start.

2022-11-07 14:38 UTC, DanielPX1 commented
> > Sorry, I am not sure I understand the one with the spaces?
> 
> Like here, in front of all the lines that form a code block, we usually put two blank spaces to align with the start of the text in the bullet point above (like in the rest of the Fulcrum guide for example) ![image](https://user-images.githubusercontent.com/86242283/200310862-9eee463e-abd5-467c-a10a-008240a68131.png)
> 
> > PS: Just found out my Fulcrum.service did not start only with Electrs service being disabled, because it was also necessary to remove Electrs Nginx config. Should I add this info to the guide? Or will we count that user runs only one Electrs implementation?
> 
> Disable alone is not enough afail, it simply stops Electrs to be started when booting/rebooting... If a user has Electrs running, they would also need to stop the service. So both stop and disable are needed.
> 
> Regarding the nginx reverse proxy, are you using it for Fulcrum? if not, why not? (just curious) I'm not sure to understand why removing the nginx reverse proxy config file is ncessary for Fulcrum to start.

ok should be fixed!

Fulcrum has it integrated If I am aware, so it is not necessary to use it with Fulcrum. But my service could not start until I removed nginx config for electrs... Not sure why it was issue, maybe would need to inspect it more

2022-11-07 14:48 UTC, VajraOfIndra commented
> ok should be fixed!

👍 
 
> Fulcrum has it integrated If I am aware, so it is not necessary to use it with Fulcrum. But my service could not start until I removed nginx config for electrs... Not sure why it was issue, maybe would need to inspect it more

Hum.. so if Fulcrum wanted to use port 50002 and it was still being used by the nginx reverse proxy for Electrs.. maybe there was a conflict that prevented Fulcrum to start.

Adding a section for Electrs user at the start might be helpful yes.. like stop and disable the Electrs service and delete (or simply backup, changing the .conf to .conf.bak would be enough to disable the reverse proxy) the nginx Electrs conf file and reload nginx.

2022-11-07 14:49 UTC, VajraOfIndra approved these changes

2022-11-07 17:57 UTC, VajraOfIndra commented
Let's go to master 🎉

2022-11-07 17:57 UTC, merged