[UPDATE GUIDE] Sparrow: add Sparrow Server
raspibolt/raspibolt pull request #1169
Opened 2022-11-11 16:39 UTC by DanielPX1

#### What

Additional way to run sparrow on your node using headless implementation for servers

### Why

More ways to run sparrow and mixing on your node

#### How

Adding necessary steps to install Sparrow

#### Scope

- [ ] reviews

#### Test & maintenance

Can be tested by following guide and reporting issues, improvements etc.

2022-11-18 10:02 UTC, VajraOfIndra requested changes
Lovely guide, very clear ❤️ 

See a few comments and questions below! And sorry in advance fo rmy nitpicking on some points 😄 

Also, it might be worth updating it to[ latest Sparrow version 1.7.1](https://github.com/sparrowwallet/sparrow/releases/tag/1.7.1).

2022-11-18 10:02 UTC, VajraOfIndra commented on guide/bonus/bitcoin/index.md
> +* **[Sparrow Terminal](Sparrow-Terminal.md)** - a stripped down version of Sparrow that can be run on systems without displays
I think we should rework the headings as ST is not a desktop wallet but a CLI one.. We could maybe do like for the lighnting wallets e .g.:

## Wallets

### CLI
* **[Sparrow Terminal](Sparrow-Terminal.md)** - a stripped down version of Sparrow that can be run on systems without displays
	
### GUI -Desktop wallet
* **[BitBoxApp](bitboxapp.md)** - a beginner-friendly desktop wallet that pionneered hardware wallets support
* **[Electrum Wallet Desktop](electrum-wallet-desktop.md)** - a feature-rich desktop wallet for power-users
* **[Specter Desktop](specter-desktop.md)** - a convenient and user-friendly GUI around Bitcoin Core with a focus on multisignature setup with hardware wallets and airgapped devices


wdyt? could be other headings

2022-11-18 15:20 UTC, DanielPX1 commented on guide/bonus/bitcoin/Sparrow-Terminal.md
> +
To my understanding, if some user wants to use Sparrow Wallet, he has to type "cd /opt/sparrow-terminal/bin/; ./Sparrow". So i thought it might be nice to do a shortcut from home directory, this way you just log in and type "./Sparrow". Command basically does a shortcut to home dir

2022-11-18 15:25 UTC, DanielPX1 commented on guide/bonus/bitcoin/Sparrow-Terminal.md
> +  $ ./Sparrow
You are right, will fix. Works without

2022-11-18 15:28 UTC, DanielPX1 commented on guide/bonus/bitcoin/Sparrow-Terminal.md
> +  $ sudo ln -s /opt/sparrow-terminal/bin/Sparrow /usr/local/bin/Sparrow
yeah, thought about this as well, noticed sparrow uses "Sparrow" so I kept the syntax

2022-11-18 15:29 UTC, DanielPX1 commented on guide/bonus/bitcoin/index.md
> +* **[Sparrow Terminal](Sparrow-Terminal.md)** - a stripped down version of Sparrow that can be run on systems without displays
Cool! Like that, as its not destkop wallet I think it is necessary. Will fix

2022-11-18 15:33 UTC, DanielPX1 commented
Thanks for review @VajraOfIndra, except the rest of the things, maybe we could expand the guide? Like "Sparrow Terminal in action", similiar to desktop version. Will demand some screenshots etc. wdyt? Or its something user will figure out himself? Its not that different from normal wallet after all... 

Also will change the Fulcrum banner, I deleted Electrs on my node and cant test its connection. Or just can delete the banner and fake it as a "electrum"

2022-11-18 17:10 UTC, VajraOfIndra commented on guide/bonus/bitcoin/Sparrow-Terminal.md
> +
Since we created a symlink in /usr/local/bin to the Sparrow executable, we can launch Sparrow from anywhere by simply typing `Sparrow`. Afaik, we don't need to create a symlink in /home/admin.

2022-11-18 17:14 UTC, VajraOfIndra commented
> Thanks for review @VajraOfIndra, except the rest of the things, maybe we could expand the guide? Like "Sparrow Terminal in action", similiar to desktop version. Will demand some screenshots etc. wdyt? Or its something user will figure out himself? Its not that different from normal wallet after all...

💯  Expanding it with a Sparrow ina ction section would be fantastic. Always better to provide a few pointers on how to use the app imho.

> Also will change the Fulcrum banner, I deleted Electrs on my node and cant test its connection. Or just can delete the banner and fake it as a "Electrs"

I think having Electrs as the default option in the command is best. But maybe having the Fulcrum banner in the pic could make the user wonder about it and try it out... so up to you. If it was in the main guide it would have to be Electrs to avoid confusion but since it's a bonus guide, it's up to you but this pic is great as it is I think.

2022-11-18 21:18 UTC, DanielPX1 commented on guide/bonus/bitcoin/Sparrow-Terminal.md
> +
wow new thing to me, thanks:)

2022-11-19 19:26 UTC, VajraOfIndra requested changes
A second review to update the guide to v1.7.1 + a couple of other ocmments

2022-11-19 19:26 UTC, VajraOfIndra commented on guide/bonus/bitcoin/Sparrow-Terminal.md
> +  $ wget https://github.com/sparrowwallet/sparrow/releases/download/1.7.0/sparrow-1.7.0-manifest.txt
```suggestion
  $ wget https://github.com/sparrowwallet/sparrow/releases/download/1.7.1/sparrow-server-1.7.1-aarch64.tar.gz
  $ wget https://github.com/sparrowwallet/sparrow/releases/download/1.7.1/sparrow-1.7.1-manifest.txt.asc
  $ wget https://github.com/sparrowwallet/sparrow/releases/download/1.7.1/sparrow-1.7.1-manifest.txt
```

2022-11-19 19:26 UTC, VajraOfIndra commented on guide/bonus/bitcoin/Sparrow-Terminal.md
> +  $ gpg --verify sparrow-1.7.0-manifest.txt.asc
```suggestion
  $ gpg --verify sparrow-1.7.1-manifest.txt.asc
```

2022-11-19 19:26 UTC, VajraOfIndra commented on guide/bonus/bitcoin/Sparrow-Terminal.md
> +  > gpg: Signature made Thu Oct 27 12:32:37 2022 CEST
```suggestion
  > gpg: assuming signed data in 'sparrow-1.7.1-manifest.txt'
  > gpg: Signature made Thu Nov 17 14:08:59 2022 GMT
```

2022-11-19 19:26 UTC, VajraOfIndra commented on guide/bonus/bitcoin/Sparrow-Terminal.md
> +  > sparrow-server-1.7.0-aarch64.tar.gz: OK
```suggestion
  $ sha256sum --check sparrow-1.7.1-manifest.txt --ignore-missing
  > sparrow-server-1.7.1-aarch64.tar.gz: OK
```

2022-11-19 19:26 UTC, VajraOfIndra commented on guide/bonus/bitcoin/Sparrow-Terminal.md
> +  $ tar -xvf sparrow-server-1.7.0-aarch64.tar.gz
```suggestion
  $ tar -xvf sparrow-server-1.7.1-aarch64.tar.gz
```

2022-11-19 19:26 UTC, VajraOfIndra commented on guide/bonus/bitcoin/Sparrow-Terminal.md
> +* Go to "preferences > server > private electrum > continue"
```suggestion
* Go to "Preferences > Server > Private Electrum > Continue"
```
adding capital letters to look like the options in the terminal menu

2022-11-19 19:26 UTC, VajraOfIndra commented on guide/bonus/bitcoin/Sparrow-Terminal.md
> +* Set values according to your electrum server implementation and test connection
did your remove the details of the different options? I think it'd be usefult to have.. but it could be a later PR and this PR could be focused on the installation section. Just a thought.

2022-11-19 19:26 UTC, VajraOfIndra commented on guide/bonus/bitcoin/Sparrow-Terminal.md
> +  $ sudo rm /home/admin/Sparrow
```suggestion
```

not exisiting anymore

2022-11-20 13:39 UTC, DanielPX1 commented
> 

OK

> > Thanks for review @VajraOfIndra, except the rest of the things, maybe we could expand the guide? Like "Sparrow Terminal in action", similiar to desktop version. Will demand some screenshots etc. wdyt? Or its something user will figure out himself? Its not that different from normal wallet after all...
> 
> 💯 Expanding it with a Sparrow ina ction section would be fantastic. Always better to provide a few pointers on how to use the app imho.
> 
> > Also will change the Fulcrum banner, I deleted Electrs on my node and cant test its connection. Or just can delete the banner and fake it as a "Electrs"
> 
> I think having Electrs as the default option in the command is best. But maybe having the Fulcrum banner in the pic could make the user wonder about it and try it out... so up to you. If it was in the main guide it would have to be Electrs to avoid confusion but since it's a bonus guide, it's up to you but this pic is great as it is I think.

Cool! I had busy weekend but shoudl get into it today/tommorow

2022-11-20 13:45 UTC, DanielPX1 commented on guide/bonus/bitcoin/Sparrow-Terminal.md
> +* Set values according to your electrum server implementation and test connection
Ill put them back, was not sure with Electrs as I do not have it. Is port 50001 used or 50002 as well?

I can see rpc address here being 127.0.0.1:50001
https://raspibolt.org/guide/bitcoin/electrum-server.html#configuration

50002 is used for hidden service w/ SSL, but cant verify if it works too

2022-11-20 13:48 UTC, DanielPX1 commented
> The new entry in the index looks great 🔥
> 
> A second review to update the guide to v1.7.1 + a couple of other ocmments
> 
> LGTM and tACK (with Raspberry Pi and Electrs + Tor proxy)

I like it too! Did the proposed changes to the latest version

Will we add then that "Sparrow in Action" improvement in another PR? It will take some work and time with screenshotting, so I am not sure If its better to merge this and then focus on that, or finish it? (I think this week I should have it done)

2022-11-20 14:48 UTC, VajraOfIndra commented
> > The new entry in the index looks great 🔥
> > A second review to update the guide to v1.7.1 + a couple of other ocmments
> > LGTM and tACK (with Raspberry Pi and Electrs + Tor proxy)
> 
> I like it too! Did the proposed changes to the latest version
> 
> Will we add then that "Sparrow in Action" improvement in another PR? It will take some work and time with screenshotting, so I am not sure If its better to merge this and then focus on that, or finish it?

Probably focus on that one first and then another PR for the "Sparrow in action", easier to reviewa and merge.

2022-11-20 14:49 UTC, VajraOfIndra commented on guide/bonus/bitcoin/Sparrow-Terminal.md
> +* Set values according to your electrum server implementation and test connection
since it's all localhost, is there a need to use SSL? probably not.. might as well use 50001 afaik.

2022-11-20 14:49 UTC, VajraOfIndra approved these changes

2022-11-20 14:54 UTC, DanielPX1 commented on guide/bonus/bitcoin/Sparrow-Terminal.md
> +* Set values according to your electrum server implementation and test connection
yeah, used 50001 w no SSL for Electrs. However Fulcrum guide uses SSL only, TCP is in review process, but only as optional addition... so I kept Fulcrum using SSL

2022-11-20 14:56 UTC, DanielPX1 commented
> > > The new entry in the index looks great 🔥
> > > A second review to update the guide to v1.7.1 + a couple of other ocmments
> > > LGTM and tACK (with Raspberry Pi and Electrs + Tor proxy)
> > 
> > 
> > I like it too! Did the proposed changes to the latest version
> > Will we add then that "Sparrow in Action" improvement in another PR? It will take some work and time with screenshotting, so I am not sure If its better to merge this and then focus on that, or finish it?
> 
> Probably focus on that one first and then another PR for the "Sparrow in action", easier to reviewa and merge.

Cool, I agree. I have this week a bit busy, so I would be able to finish it off by the end of the week, so I agree with another PR!

I dont think I have anything more to add/improve

2022-11-22 09:52 UTC, merged