Install OTS & add timestamp check for LND
raspibolt/raspibolt pull request #1175
Opened 2022-11-16 11:15 UTC by VajraOfIndra

#### What

Same as closed PR #1087 
Fixes #1043 

- [x] significant change to core configuration
- [ ] independent bonus guide
- [ ] simple bug fix

#### Test & maintenance

Follow new sections: 
- Install ots client
- Check latest LND checksum file timestamp

2022-11-16 11:27 UTC, twofaktor requested changes
A suggestion

2022-11-16 11:27 UTC, twofaktor commented on guide/lightning/lightning-client.md
> +  $ wget https://github.com/lightningnetwork/lnd/releases/download/v0.15.3-beta/manifest-roasbeef-v0.15.4-beta.sig.ots
Change to: `$ wget https://github.com/lightningnetwork/lnd/releases/download/v0.15.4-beta/manifest-guggero-v0.15.4-beta.sig.ots`

2022-11-16 11:29 UTC, kristapsk requested changes

2022-11-16 11:29 UTC, kristapsk commented on guide/lightning/lightning-client.md
> +  $ wget https://github.com/lightningnetwork/lnd/releases/download/v0.15.3-beta/manifest-roasbeef-v0.15.4-beta.sig.ots
```suggestion
  $ wget https://github.com/lightningnetwork/lnd/releases/download/v0.15.4-beta/manifest-guggero-v0.15.4-beta.sig.ots
```

2022-11-16 11:31 UTC, kristapsk commented
Starting from v0.9.8 release there is also OTS proofs for JoinMarket, so https://github.com/raspibolt/raspibolt/blob/master/guide/bonus/bitcoin/joinmarket.md could be updated too.

2022-11-16 11:55 UTC, VajraOfIndra commented on guide/lightning/lightning-client.md
> +  $ wget https://github.com/lightningnetwork/lnd/releases/download/v0.15.3-beta/manifest-roasbeef-v0.15.4-beta.sig.ots
done 👍

2022-11-16 12:05 UTC, VajraOfIndra commented
> Starting from v0.9.8 release there is also OTS proofs for JoinMarket, so https://github.com/raspibolt/raspibolt/blob/master/guide/bonus/bitcoin/joinmarket.md could be updated too.



> Starting from v0.9.8 release there is also OTS proofs for JoinMarket, so https://github.com/raspibolt/raspibolt/blob/master/guide/bonus/bitcoin/joinmarket.md could be updated too.

I added it. However I can't test it on my node so the block height is not right. could you check on your node and correct the output of ots verify?

2022-11-16 12:11 UTC, kristapsk commented
> > Starting from v0.9.8 release there is also OTS proofs for JoinMarket, so https://github.com/raspibolt/raspibolt/blob/master/guide/bonus/bitcoin/joinmarket.md could be updated too.
> 
> I added it. However I can't test it on my node so the block height is not right. could you check on your node and correct the output of ots verify?

It is correct (ok, different block), but there is another issue, joinmarket user does not have ~/.bitcoin symlink (because JM does not need it), so it will give error if ran from joinmarket user, as per guide.
```
joinmarket@odroid:/tmp$ ots verify joinmarket-clientserver-0.9.8.tar.gz.asc.ots -f joinmarket-clientserver-0.9.8.tar.gz.asc
Got 1 attestation(s) from https://finney.calendar.eternitywall.com
Got 1 attestation(s) from https://btc.calendar.catallaxy.com
Got 1 attestation(s) from https://alice.btc.calendar.opentimestamps.org
Got 1 attestation(s) from https://bob.btc.calendar.opentimestamps.org
Could not connect to Bitcoin node: Cookie file unusable ([Errno 2] No such file or directory: '/home/joinmarket/.bitcoin/.cookie') and rpcpassword not specified in the configuration file: '/home/joinmarket/.bitcoin/bitcoin.conf'
```
Works from admin user:
```
admin /tmp ₿ ots verify joinmarket-clientserver-0.9.8.tar.gz.asc.ots -f joinmarket-clientserver-0.9.8.tar.gz.asc
Got 1 attestation(s) from https://finney.calendar.eternitywall.com
Got 1 attestation(s) from https://btc.calendar.catallaxy.com
Got 1 attestation(s) from https://alice.btc.calendar.opentimestamps.org
Got 1 attestation(s) from https://bob.btc.calendar.opentimestamps.org
Success! Bitcoin block 754240 attests existence as of 2022-09-15 EEST
```
Not sure of best solution here. Adding that symlink just for OTS verification seems to be overkill, but probably is the only solution.

2022-11-16 12:39 UTC, VajraOfIndra commented
> > > Starting from v0.9.8 release there is also OTS proofs for JoinMarket, so https://github.com/raspibolt/raspibolt/blob/master/guide/bonus/bitcoin/joinmarket.md could be updated too.
> > 
> > 
> > I added it. However I can't test it on my node so the block height is not right. could you check on your node and correct the output of ots verify?
> 
> It is correct (ok, different block), but there is another issue, joinmarket user does not have ~/.bitcoin symlink (because JM does not need it), so it will give error if ran from joinmarket user, as per guide.
> 
> ```
> joinmarket@odroid:/tmp$ ots verify joinmarket-clientserver-0.9.8.tar.gz.asc.ots -f joinmarket-clientserver-0.9.8.tar.gz.asc
> Got 1 attestation(s) from https://finney.calendar.eternitywall.com
> Got 1 attestation(s) from https://btc.calendar.catallaxy.com
> Got 1 attestation(s) from https://alice.btc.calendar.opentimestamps.org
> Got 1 attestation(s) from https://bob.btc.calendar.opentimestamps.org
> Could not connect to Bitcoin node: Cookie file unusable ([Errno 2] No such file or directory: '/home/joinmarket/.bitcoin/.cookie') and rpcpassword not specified in the configuration file: '/home/joinmarket/.bitcoin/bitcoin.conf'
> ```
> 
> Works from admin user:
> 
> ```
> admin /tmp ₿ ots verify joinmarket-clientserver-0.9.8.tar.gz.asc.ots -f joinmarket-clientserver-0.9.8.tar.gz.asc
> Got 1 attestation(s) from https://finney.calendar.eternitywall.com
> Got 1 attestation(s) from https://btc.calendar.catallaxy.com
> Got 1 attestation(s) from https://alice.btc.calendar.opentimestamps.org
> Got 1 attestation(s) from https://bob.btc.calendar.opentimestamps.org
> Success! Bitcoin block 754240 attests existence as of 2022-09-15 EEST
> ```
> 
> Not sure of best solution here. Adding that symlink just for OTS verification seems to be overkill, but probably is the only solution.

What about doing all the download and check stespw ithadmin user and then switching to joinmarket user for unpacking the tarball and following commands?

Otherwise will create the symlink if you prefer, let me know.

2022-11-16 17:35 UTC, VajraOfIndra commented
> Not sure of best solution here. Adding that symlink just for OTS verification seems to be overkill, but probably is the only solution.

Added symlink, PTAL

2022-11-17 10:55 UTC, kristapsk commented on guide/bonus/bitcoin/joinmarket.md
> +* Create a symbolic link pointingto the Bitcoin data directory for the OTS client to verify the timestamp
```suggestion
* Create a symbolic link pointing to the Bitcoin data directory for the OTS client to verify the timestamp
```

2022-11-17 12:20 UTC, VajraOfIndra commented on guide/lightning/lightning-client.md
> +  $ wget https://github.com/lightningnetwork/lnd/releases/download/v0.15.3-beta/manifest-roasbeef-v0.15.4-beta.sig.ots
@twofaktor this is fixed, could you PTAL and approve the requested change?

2022-11-20 17:43 UTC, twofaktor requested changes

2022-11-20 17:43 UTC, twofaktor commented on guide/bonus/bitcoin/joinmarket.md
> +  $ ln -s /data/bitcoin /home/joinmarket/.bitcoin
Why use this symbolic link? `joinmarket-clientserver-0.9.8.tar.gz.asc` and `joinmarket-clientserver-0.9.8.tar.gz.asc.ots` are downloaded to the `/tmp` folder, in the same way as for the bitcoin and LND clients. Also, the OTS client will be installed for the admin user:

* With user "admin", globally install the OpenTimestamp client
  ```sh
  $ sudo pip3 install opentimestamps-client
  ```

2022-11-21 10:34 UTC, VajraOfIndra commented on guide/bonus/bitcoin/joinmarket.md
> +  $ ln -s /data/bitcoin /home/joinmarket/.bitcoin
See comments above: https://github.com/raspibolt/raspibolt/pull/1175#issuecomment-1316911353

2022-11-21 12:41 UTC, twofaktor commented on guide/bonus/bitcoin/joinmarket.md
> +  $ ln -s /data/bitcoin /home/joinmarket/.bitcoin
Will we do something different in this guide?

https://raspibolt.org/guide/bitcoin/bitcoin-client.html#preparations
https://raspibolt.org/guide/lightning/lightning-client.html#download

2022-11-21 12:43 UTC, twofaktor commented
> What about doing all the download and verification steps with the admin user and then switching to joinmarket user for unpacking the tarball and following commands?

I thought this was the standard RaspiBolt solution

2022-11-21 13:01 UTC, VajraOfIndra commented on guide/bonus/bitcoin/joinmarket.md
> +  $ ln -s /data/bitcoin /home/joinmarket/.bitcoin
No, because there we're using the admin user for these and there already is a bitcoin data directory symlink in the home directory of admin

2022-11-21 13:21 UTC, twofaktor commented
Should we merge this PR first? # 1179 is a small correction

2022-11-21 13:26 UTC, twofaktor commented
Invert the order of lines 94-95 of `bitcoin-client.md` file, to align with the correct verification progress on the website:

First .ots file:

![Capt1](https://user-images.githubusercontent.com/89636253/203066644-b86e8d84-d363-4987-b8d6-688901bb90e3.PNG)

FIFO

2022-11-21 17:09 UTC, VajraOfIndra commented
> Invert the order of lines 94-95 of `bitcoin-client.md` file, to align with the correct verification progress on the website:

done

2022-11-21 17:11 UTC, VajraOfIndra commented
> Should we merge this PR first? #1179 is a small correction

At the bottom of this thread, under Changes requested, could you approve the changes? 
I think we also need the approval of the requested changes by @kristapsk and then we'll be ready to merge this PR.

2022-11-21 17:33 UTC, twofaktor approved these changes

2022-11-22 20:55 UTC, kristapsk approved these changes

2022-11-22 21:09 UTC, merged