[UPDATE BONUS GUIDE] Samourai Dojo
raspibolt/raspibolt pull request #1180
Opened 2022-11-17 21:59 UTC by DanielPX1

#### What

Update Dojo to latest version 1.18, remove "sh" and add more detailed upgrade guide

### Why

Users will run latest version, upgrade guide is easier to follow to beginner and "sh" is removed due to new RaspiBolt standardization

#### How

Importing new download links and testing upgrade section

#### Scope

- [ ] Review

#### Test & maintenance

Can be tested by following guide and reporting issues

![pic](https://code.samourai.io/uploads/-/system/group/avatar/41/RoninDojo-01c.png)

2022-11-22 11:12 UTC, twofaktor commented on guide/bonus/bitcoin/dojo.md
>    zmqpubhashblock=tcp://0.0.0.0:8433  # For Dojo
Is this the same line for Fulcrum?

https://raspibolt.org/guide/bonus/bitcoin/fulcrum.html#configure-bitcoin-core

would this be confusing?

2022-11-22 11:27 UTC, DanielPX1 commented on guide/bonus/bitcoin/dojo.md
>    zmqpubhashblock=tcp://0.0.0.0:8433  # For Dojo
Yeah, wonder how to tackle it. That zmqpub is necessary to have in config for both Dojo & Fulcrum, no issues with Fulcrum but Electrs users need to add it

But thought "# Dojo" might be less confusing thab "# For Fulcrum", in the end it is Dojo guide and Electrs user does not use Fulcrum

So I thought about this, or doing "# For Dojo/Fulcrum". Or nothing at all, just plain line without that comment. Maybe would be best? wdyt?

2022-11-22 12:51 UTC, twofaktor requested changes

2022-11-22 12:51 UTC, twofaktor commented on guide/bonus/bitcoin/dojo.md
>    # Dojo hidden service
Change to -->
 
```
 ############### This section is just for location-hidden services ###
  # Hidden Service Dojo
  HiddenServiceDir /var/lib/tor/hidden_service_dojo/
```
to standardize with the rest of the guide

2022-11-22 14:54 UTC, DanielPX1 commented on guide/bonus/bitcoin/dojo.md
>    # Dojo hidden service
Thanks, fixed

2022-11-22 14:56 UTC, DanielPX1 commented on guide/bonus/bitcoin/dojo.md
>    zmqpubhashblock=tcp://0.0.0.0:8433  # For Dojo
Did it the simple way, should not be confusing now

2022-11-22 16:33 UTC, twofaktor commented on guide/bonus/bitcoin/dojo.md
>    zmqpubhashblock=tcp://0.0.0.0:8433  # For Dojo
LGTM!

2022-12-03 17:59 UTC, DanielPX1 commented
Can I ask 4 review? @twofaktor

2023-03-23 14:04 UTC, DanielPX1 commented
Made a few upgrades

2023-03-30 09:31 UTC, blckbx requested changes
Installation: tACK
utACK for connecting Samourai Wallet to Dojo
few nits

LGTM

2023-03-30 09:31 UTC, blckbx commented on guide/bonus/bitcoin/dojo.md
>  * Verify that the fingerprints file has actually been signed by that developper
```suggestion
* Verify that the fingerprints file has actually been signed by that developer
```
nit

2023-03-30 09:31 UTC, blckbx commented on guide/bonus/bitcoin/index.md
> +* **[Samourai Dojo](dojo.md){:target="_blank"}** - Personal backend for your Samourai Wallet
```suggestion
* **[Samourai Dojo](dojo.md)** - Personal backend for your Samourai Wallet
```
I don't think we open new tabs for other links in this section.

2023-03-30 10:15 UTC, blckbx approved these changes
LGTM

@twofaktor please approve/check your requested changes to merge this PR?

2023-04-03 20:53 UTC, twofaktor commented
Line 80: https://github.com/raspibolt/raspibolt/pull/1180/files#diff-7e19336506ee3c72ae982f879474abed1f329e0bd65baa069debad102d3491e8R80

NPM was ready installed on BTC RPC Explorer guide:
https://raspibolt.org/guide/bitcoin/blockchain-explorer.html#install-nodejs

2023-04-03 22:49 UTC, twofaktor requested changes

2023-04-03 22:49 UTC, twofaktor commented on guide/bonus/bitcoin/dojo.md
>    $ sudo systemctl restart tor
```suggestion
  $ sudo systemctl reload tor
```

2023-04-03 22:50 UTC, twofaktor requested changes

2023-04-03 22:50 UTC, twofaktor commented on guide/bonus/bitcoin/dojo.md
> -  ```
Restore this

2023-04-03 22:50 UTC, twofaktor commented on guide/bonus/bitcoin/dojo.md
> +$ sudo systemctl reload tor
Delete this

2023-04-04 09:00 UTC, DanielPX1 commented on guide/bonus/bitcoin/dojo.md
>  * Find and edit these lines inside "indexer" configuration to following values. Use port "50001" and "tcp" for Electrs
Guess its error I had very early on when testing the guide with my raspi. I could not connect electrs other way, but now it works for me. Guess it was some of my mistake when following Electrs guide, it is fixed

2023-04-04 09:06 UTC, DanielPX1 commented on guide/bonus/bitcoin/dojo.md
>  * Add following line preferably under "# Connections" or at the end of the file
not sure I understand, zmqpubhashblock=tcp://127.0.0.1:8433 is already present on this line?

2023-04-04 09:57 UTC, twofaktor commented on guide/bonus/bitcoin/dojo.md
>  * Add following line preferably under "# Connections" or at the end of the file
In this Fulcrum section: https://raspibolt.org/guide/bonus/bitcoin/fulcrum.html#configure-bitcoin-core

Was specified "zmqpubhashblock=tcp://0.0.0.0:8433" in this Dojo guide "zmqpubhashblock=tcp://127.0.0.1:8433". Can you see the difference?

2023-04-04 10:18 UTC, blckbx commented on guide/bonus/bitcoin/dojo.md
>  * Add following line preferably under "# Connections" or at the end of the file
That was my proposal (https://github.com/raspibolt/raspibolt/pull/1180#discussion_r1152976728) because other settings in bitcoin.conf also make use of 127.0.0.1

2023-04-04 10:26 UTC, twofaktor commented on guide/bonus/bitcoin/dojo.md
>  * Add following line preferably under "# Connections" or at the end of the file
Ok, I'm agree

Please review this comment, I think it is important ensure keeping compatibility with the rest of the services of RaspiBolt offer

https://github.com/raspibolt/raspibolt/pull/1180#discussion_r1156355255

2023-04-04 11:32 UTC, DanielPX1 commented on guide/bonus/bitcoin/dojo.md
>  * Add following line preferably under "# Connections" or at the end of the file
Ok, so we keepin 127. instead of the 0. ?

2023-04-04 11:50 UTC, twofaktor commented on guide/bonus/bitcoin/dojo.md
>  * Add following line preferably under "# Connections" or at the end of the file
> 127.0.0.1

Yes, keep 127.0.0.1

2023-04-04 15:08 UTC, DanielPX1 commented on guide/bonus/bitcoin/dojo.md
>  _Note:_ If you're running an app that also uses the nginx web server (_e.g._ Homer, Mempool etc), the http context is already present in `nginx.conf`. Simply edit it to match the options below.
I suggest this form of config, will test it out today. Perhaps you can too? If you run all these apps as well?

 ```
  http {

          # Additional line for Mempool
          tcp_nodelay on;
        
          # Additional lines for Samourai Dojo
          gzip_comp_level  1;
          gzip_disable  msie6;
          gzip_min_length  128;
          gzip_types  application/json;
          gzip_vary  on;
        
          # Shared lines between Mempool, Dojo, Homer
          gzip on;
          sendfile  on;
          tcp_nopush on;
          server_tokens off;
        
          keepalive_timeout  95;
          types_hash_max_size 2048;
        
          ssl_protocols TLSv1.3;
          ssl_prefer_server_ciphers on;
        
          access_log /var/log/nginx/access.log;
          error_log /var/log/nginx/error.log;
        
          default_type application/octet-stream;
        
          include /etc/nginx/mime.types;
          include /etc/nginx/conf.d/*.conf;
          include /etc/nginx/sites-enabled/*;

  }
  ```

2023-04-04 15:10 UTC, DanielPX1 commented
> Line 80: https://github.com/raspibolt/raspibolt/pull/1180/files#diff-7e19336506ee3c72ae982f879474abed1f329e0bd65baa069debad102d3491e8R80
> 
> NPM (on Node JS package) was ready installed on the BTC RPC Explorer guide: https://raspibolt.org/guide/bitcoin/blockchain-explorer.html#install-nodejs

Updated in the guide with reference to block explorer

2023-04-06 09:57 UTC, DanielPX1 commented
@twofaktor ok just found out there no necessary changes to nginx conf mempool... Mempool Nginx configuration is compatible with dojo. The additional Dojo lines are not necessary to add at all

2023-04-06 10:18 UTC, DanielPX1 commented
@twofaktor configuration tested an working!

2023-04-10 11:03 UTC, DanielPX1 commented on guide/bonus/bitcoin/dojo.md
>  _Note:_ If you're running an app that also uses the nginx web server (_e.g._ Homer, Mempool etc), the http context is already present in `nginx.conf`. Simply edit it to match the options below.
Tested Nginx.conf settings and mempool configuration is not broken

2023-04-27 13:50 UTC, twofaktor requested changes

2023-04-27 13:50 UTC, twofaktor commented on guide/bonus/bitcoin/dojo.md
>    // Port used by the API
Why change the existing default ports?

https://code.samourai.io/dojo/samourai-dojo/-/blob/develop/keys/index-example.js#L72

![imagen](https://user-images.githubusercontent.com/89636253/234882132-d434b876-be8d-4ae4-9627-b7d9128234c4.png)

2023-04-27 13:50 UTC, twofaktor commented on guide/bonus/bitcoin/dojo.md
>    [ H ] NODE API KEY 1, NODE API KEY 2
2 different passwords in the same one?

2023-04-27 13:52 UTC, twofaktor commented
Delete "with dojo user" https://github.com/raspibolt/raspibolt/pull/1180/files#diff-7e19336506ee3c72ae982f879474abed1f329e0bd65baa069debad102d3491e8R268
and https://github.com/raspibolt/raspibolt/pull/1180/files#diff-7e19336506ee3c72ae982f879474abed1f329e0bd65baa069debad102d3491e8R275 reiteration

2023-04-27 15:09 UTC, DanielPX1 commented on guide/bonus/bitcoin/dojo.md
>    [ H ] NODE API KEY 1, NODE API KEY 2
I guess 1 can be used, but in default config file there were values for 2 keys, will delete one in my setup and see if it works, but it should

2023-04-27 15:18 UTC, DanielPX1 commented on guide/bonus/bitcoin/dojo.md
>    // Port used by the API
I changed them but default can be used, should I return them back?

2023-04-27 17:09 UTC, twofaktor commented on guide/bonus/bitcoin/dojo.md
>    [ H ] NODE API KEY 1, NODE API KEY 2
No, this is correct:

![imagen](https://user-images.githubusercontent.com/89636253/234937390-20cfda5b-6103-48ba-b036-60528ce3a4ad.png)

my question was to confirm that because it's weird, and to improve the descriptions of the steps to indicate that they are two different passwords

2023-04-27 18:07 UTC, twofaktor requested changes

2023-04-27 18:07 UTC, twofaktor commented on guide/bonus/bitcoin/dojo.md
> +* Find and edit these lines inside "auth" configuration to following values. Delete second value of "apiKeys" to match format below (use only one apiKey)
Why?

2023-04-27 18:07 UTC, twofaktor commented on guide/bonus/bitcoin/dojo.md
> +  apiKeys: ['[ H ] NODE API KEY'],
Why?

2023-04-27 20:25 UTC, DanielPX1 commented on guide/bonus/bitcoin/dojo.md
> +  apiKeys: ['[ H ] NODE API KEY'],
sorry, misunderstood you. It is fixed now

2023-04-27 22:56 UTC, twofaktor requested changes

2023-04-27 22:56 UTC, twofaktor commented on guide/bonus/bitcoin/dojo.md
> +  $ VERSION=1.9.2
Add ```sh // ``` for indicate code

2023-04-27 23:04 UTC, DanielPX1 commented on guide/bonus/bitcoin/dojo.md
> +  $ VERSION=1.9.2
is it good now?

2023-04-27 23:26 UTC, twofaktor requested changes

2023-04-27 23:26 UTC, twofaktor commented on guide/bonus/bitcoin/dojo.md
>    $ VERSION=1.9.2
```suggestion
  $ VERSION=1.19.2
```

2023-05-03 21:27 UTC, twofaktor approved these changes
utACK, let's go to the master 🚀

2023-05-03 21:27 UTC, merged