[NEW BONUS GUIDE] JoinMarket-webui (Jam)
raspibolt/raspibolt pull request #1185
Opened 2022-11-21 03:07 UTC by nu5h4ckle

#### What

- Created JoinMarket-webui (Jam) bonus guide

### Why

- Jam enables a simple UX for interacting with JoinMarket-clientserver

#### How

- Reviewing and conforming to existing bonus guides

#### Scope

- [ ] significant change to core configuration
- [x] independent bonus guide
- [ ] simple bug fix

Fixes #1098 

#### Test & maintenance

How can the changes be tested? Is there ongoing maintenance effort? If this is a bonus guide: are you willing to update it from time to time?

- Test by following guide and reporting issues.  I will make an effort to keep the guide up-to-date.

#### Animated GIF (optional)

![Add some snazz if you feel like it :)](https://jamapp.org/images/wallet.png)

2022-11-21 23:09 UTC, Buttafuoco commented
i've just installed but do not able to connect. see this issue

https://github.com/joinmarket-webui/jam/issues/571

someone say where i can dig deeper to find the solution?

2022-11-23 08:35 UTC, theborakompanioni commented on guide/bonus/Jam.md
> +$ sudo rm /etc/nginx/sites-enabled/dojo.conf
Should this be
```suggestion
$ sudo rm /etc/nginx/streams-enabled/jam-reverse-proxy.conf
```
?

2022-11-23 21:04 UTC, Buttafuoco commented on guide/bonus/Jam.md
> +* Generate self-signed certificate in JoinMarket's working directory
cd /home/joinmarket/.joinmarket (it's not clear what folder is this)

2022-11-23 21:06 UTC, Buttafuoco approved these changes

2022-12-12 10:25 UTC, greenart7c3 requested changes

2022-12-30 02:34 UTC, kristapsk commented on guide/bonus/bitcoin/Jam.md
> +  -subj "/C=US/ST=Utah/L=Lehi/O=Your Company, Inc./OU=IT/CN=example.com"
```suggestion
  -subj "/C=US/ST=Utah/L=Lehi/O=Your Company, Inc./OU=IT/CN=example.com"
$ exit
```

Need to switch back to admin user for next commands.

2022-12-30 02:34 UTC, kristapsk commented on guide/bonus/bitcoin/Jam.md
> +$ nano joinmarket.cfg
```suggestion
$ nano ~/.joinmarket/joinmarket.cfg
```

2022-12-30 02:34 UTC, kristapsk commented on guide/bonus/bitcoin/Jam.md
> +max_cj_fee_abs = 500
I would increase these values. 0.00002 and 500 are yield generator configuration defaults, but with 0.1 (10%) variance. Would suggest increasing to at least 0.00003 and 600. Lower values means you may save some satoshis, but it potentially lowers your anonymity set, as there will be less makers to choose from when doing coinjoins as a taker.

2022-12-30 02:34 UTC, kristapsk commented on guide/bonus/bitcoin/Jam.md
> +$ git clone https://github.com/joinmarket-webui/jam.git --branch v0.1.3 --depth=1
There have been new release.
```suggestion
$ git clone https://github.com/joinmarket-webui/jam.git --branch v0.1.4 --depth=1
```

2022-12-30 02:34 UTC, kristapsk commented on guide/bonus/bitcoin/Jam.md
> +$ git verify-tag v0.1.3
There have been new release.
```suggestion
$ git verify-tag v0.1.4
```

2022-12-30 02:34 UTC, kristapsk commented on guide/bonus/bitcoin/Jam.md
> +> Good signature...
It's a good idea to show key fingerprint here, so user can compare, does it match.
```suggestion
...
> gpg: Good signature from "Gigi <dergigi@pm.me>" [unknown]
> gpg: WARNING: This key is not certified with a trusted signature!
> gpg:          There is no indication that the signature belongs to the owner.
> Primary key fingerprint: 8198 A185 30A5 22A0 9561  2439 89C4 A25E 69A5 DE7F
```

2022-12-30 03:08 UTC, kristapsk commented
Link needs to be added to https://github.com/raspibolt/raspibolt/blob/master/guide/bonus/bitcoin/index.md.

2023-01-07 10:32 UTC, kristapsk approved these changes
ACK b088b71755ebd1553746cadbbf48a5f0486134ba. I think it's good for merging now.

2023-01-07 10:33 UTC, merged

2023-02-25 10:17 UTC, SpartanBit commented
Trying to run it but without success, due to this issue: 
https://github.com/joinmarket-webui/jam/issues/608
Any advice on how to solve it?