Bitcoin guide update w/ ots verification
raspibolt/raspibolt pull request #1191
Opened 2022-11-25 06:23 UTC by sig-noi

#### What

Update bitcoin-client.md to Bitcoin version 24.0
Add streamlined upgrade section to bottom of guide
Include .ots verification in upgrade section

### Why

Makes upgrading easier
Adds .ots verification for upgrades

#### How

as above

#### Scope

- [ ] significant change to core configuration
- [ ] independent bonus guide
- [ ] simple bug fix
- [x] mostly clerical update to core guide

Fixes # 1190
https://github.com/raspibolt/raspibolt/issues/1190

2022-11-25 07:55 UTC, Bitcoinite requested changes

2022-11-25 07:55 UTC, Bitcoinite commented on guide/bitcoin/bitcoin-client.md
> +  $ tar -xvf bitcoin-23.0-aarch64-linux-gnu.tar.gz
Still using bitcoin-23.0 here

2022-11-25 07:55 UTC, Bitcoinite commented on guide/bitcoin/bitcoin-client.md
> +  $ sudo install -m 0755 -o root -g root -t /usr/local/bin bitcoin-23.0/bin/*
Still using bitcoin-23.0 here

2022-11-25 08:10 UTC, sig-noi commented on guide/bitcoin/bitcoin-client.md
> +  $ sudo install -m 0755 -o root -g root -t /usr/local/bin bitcoin-23.0/bin/*
fixed

2022-11-25 08:10 UTC, sutterseba requested changes

2022-11-25 08:10 UTC, sutterseba commented on guide/bitcoin/bitcoin-client.md
>    $ sudo install -m 0755 -o root -g root -t /usr/local/bin bitcoin-23.0/bin/*
Still using `bitcoin-23.0' here

2022-11-25 08:10 UTC, sutterseba commented on guide/bitcoin/bitcoin-client.md
>  * In the next box, drop or upload the SHA256SUMS file
Two more bumps missing in line 99 below

2022-11-25 08:10 UTC, sig-noi commented on guide/bitcoin/bitcoin-client.md
> +  $ tar -xvf bitcoin-23.0-aarch64-linux-gnu.tar.gz
fixed thanks.

2022-11-25 08:11 UTC, sig-noi commented on guide/bitcoin/bitcoin-client.md
>  * In the next box, drop or upload the SHA256SUMS file
fixed thanks.

2022-11-25 08:13 UTC, sig-noi commented on guide/bitcoin/bitcoin-client.md
>    $ sudo install -m 0755 -o root -g root -t /usr/local/bin bitcoin-23.0/bin/*
fixed, thanks.

2022-11-25 08:40 UTC, sutterseba requested changes

2022-11-25 08:40 UTC, sutterseba commented on guide/bitcoin/bitcoin-client.md
> +  $ ots verify SHA256SUMS.ots -f SHA256SUMS
The OpenTimestamps command line tool is not installed on a RaspiBolt. The main installation guide above instructs the user to download and verify on their local system and I would suggest sticking to that to keep things simple. 

The user would have to e.g. install Python, install opentimestamps-client via PyPi and do a reboot for this to work. At least that's what I had to do just now.

2022-11-25 08:43 UTC, VajraOfIndra approved these changes
LGTM!

Update section: tACK
Main section: utACK

Lovely addition the gpg key refresh commands ❤️ 

I also like that the update section is now fully laid out 💯

2022-11-25 08:47 UTC, VajraOfIndra commented on guide/bitcoin/bitcoin-client.md
> +  $ ots verify SHA256SUMS.ots -f SHA256SUMS
The client is already installed at this stage of the guide. The installation is actually done in the previous section, just before the "For the future..." section: https://raspibolt.org/guide/bitcoin/bitcoin-client.html#opentimestamps-client

Python 3 is already part of RasPiOS Lite 64-bit. Installing the OTS client is a simple one-liner using the pip3 package manager.

2022-11-25 08:54 UTC, sutterseba commented on guide/bitcoin/bitcoin-client.md
> +  $ ots verify SHA256SUMS.ots -f SHA256SUMS
Ohh, gotcha!

In that case it's a nice shortcut. Completely missed that OpenTimestamps client section... And my RaspiBolt obviously didn't know about it either... 😉

2022-11-25 08:56 UTC, sutterseba approved these changes
tACK

2022-11-25 09:23 UTC, VajraOfIndra commented
Should we wait a few days before merging maybe or not? (just to make sure there is no big bugs taht are found..)

2022-11-25 09:31 UTC, kristapsk commented on guide/bitcoin/bitcoin-client.md
> +  $ ots verify SHA256SUMS.ots -f SHA256SUMS
> The user would have to e.g. install Python, install opentimestamps-client via PyPi and do a reboot for this to work.

Reboot should not be required, even if you haven't had it before.

2022-11-25 09:35 UTC, kristapsk commented
> Should we wait a few days before merging maybe or not?

I think we definitely should. Besides, update to Bitcoin Core v24 seems controversial to some people (becase of having `-mempoolfullrbf`off by default configuration option).

2022-11-25 09:45 UTC, twofaktor requested changes

2022-11-25 09:45 UTC, twofaktor commented on guide/bitcoin/bitcoin-client.md
> +  $ gpg --keyserver hkps://keys.openpgp.org --refresh-keys
This command does not realize new contributors' signatures and only has an effect if any signature was changed compared with your database where you have old previously downloaded keys and the keyserver database keys.

We should continue to use these commands to upgrade:

```
$ wget https://raw.githubusercontent.com/bitcoin/bitcoin/master/contrib/builder-keys/keys.txt -O keys.txt
$ while read fingerprint keyholder_name; do gpg --keyserver hkps://keyserver.ubuntu.com --recv-keys ${fingerprint}; done < ./keys.txt
```

I think that we should redirect to the [Bitcoin section](bitcoin-client.md#installation) section and include timestamp verification in this upgrade section and nothing more.

![Capt](https://user-images.githubusercontent.com/89636253/203949451-ecf24910-5ea4-454f-8e8e-cfea63258098.PNG)

PS: realize the new argument added to overwrite the old keys.txt file ` -O keys.txt` on `wget https://raw.githubusercontent.com/bitcoin/bitcoin/master/contrib/builder-keys/keys.txt -O keys.txt` command

2022-11-25 09:56 UTC, twofaktor commented
> > Should we wait a few days before merging maybe or not?
> 
> I think we definitely should. Besides, update to Bitcoin Core v24 seems controversial to some people (becase of having `-mempoolfullrbf`off by default configuration option).

How about adding a new section to give the option to enable `mempoolfullrbf=1` in `bitcoin.conf`` with some explanation of what it means?

2022-11-25 18:06 UTC, fabiolucidi commented on guide/bitcoin/bitcoin-client.md
> +  $ ots verify SHA256SUMS.ots -f SHA256SUMS
> 

Hi everyone, my very first comment on this repo :) 
I'm not entirely sure about pip3 being part of RasPiOs Lite 64-bit. I had to give a good 'sudo apt install python3-pip' before being able to run the onliner to install ots. Can somoene doublecheck it?

2022-11-25 18:14 UTC, VajraOfIndra commented on guide/bitcoin/bitcoin-client.md
> +  $ ots verify SHA256SUMS.ots -f SHA256SUMS
Welcome! :)

So Python 3 is definitely part of Raspberry Pi OS Lite 64-bit: https://downloads.raspberrypi.org/raspios_lite_armhf/images/raspios_lite_armhf-2022-09-26/2022-09-22-raspios-bullseye-armhf-lite.info

There is no pip3 package in that list but I don't know if it means that it's part of Python 3 or if it means it has to be installed..

We could add the pip3 install/update command anyways just in case. It wouldn;t hurt if it's already installed I suppose.

2022-11-25 23:04 UTC, sig-noi commented
> > Should we wait a few days before merging maybe or not?
> 
> I think we definitely should. Besides, update to Bitcoin Core v24 seems controversial to some people (becase of having `-mempoolfullrbf`off by default configuration option).

Of course no problem with waiting a few days, but I have a feeling this will not shake out very soon. Regarding the best default setting for mempoolfullrbf, I'd try to base my decision on functional rather than moral implications but my expertise is limited. Based on the github conversation, it is quite difficult to determine a best answer or a reliable sense of consensus. I left the setting out of this update for that very reason.

https://github.com/bitcoin/bitcoin/pull/26525

2022-11-25 23:34 UTC, sig-noi commented on guide/bitcoin/bitcoin-client.md
> +  $ gpg --keyserver hkps://keys.openpgp.org --refresh-keys
I think a streamlined update section is better than mixing directions between the update section and the main guide.

The reason for the update signatures command was that the bitcoincore downloads site recommends, though your suggestion to retrieve and re-import keys.txt seems to have merit and resulted in some updates for me. Not sure what disadvantages there might be to your commands vs the update, but the update makes no updates after running your commands so it feels like they are better. Changing to incorporate.

2022-11-26 16:18 UTC, fabiolucidi approved these changes

2022-12-12 13:25 UTC, kristapsk commented
Note that 24.0.1 was just released, so we should upgrade directly to 24.0.1, not 24.0. https://github.com/bitcoin/bitcoin/releases/tag/v24.0.1

2022-12-12 18:42 UTC, blckbx commented on guide/bitcoin/bitcoin-client.md
> +){:target="_blank"} of Bitcoin Core v24.0.1.
```suggestion
* If the timestamps is verified, you should see the following message. The timestamp proves that the checksums file existed on the [release date](https://github.com/bitcoin/bitcoin/releases/tag/v24.0.1){:target="_blank"} of Bitcoin Core v24.0.1.
```

2022-12-12 18:43 UTC, blckbx reviewed
one link fix

2022-12-13 08:18 UTC, blckbx approved these changes
tACK

for the `mempoolfullrbf` option, I'd leave this up to the user to make an educated choice whether to switch it on or off. Advanced configuration options are usually not part of RaspiBolt guides.

2022-12-15 16:26 UTC, twofaktor commented
There is an error on OpenTimestamp client installation, @VajraOfIndra guessed that if Python 3 is the default version in Raspberry Pi OS 64-bit Lite, so pip3 is also default: https://github.com/raspibolt/raspibolt/pull/1087#discussion_r987423189, don't trust, verify:

![Captura3957349785](https://user-images.githubusercontent.com/89636253/207913189-c86cae20-025d-424a-bc03-385db3237912.PNG)
![Captura87657634645](https://user-images.githubusercontent.com/89636253/207913272-3a9f9808-1714-447c-879d-6f6ee4dcb241.PNG)

Following [official docs devs](https://github.com/opentimestamps/opentimestamps-client#installation), I suggest installing dependencies, by adding this command:

`sudo apt-get install python3-dev python3-pip python3-setuptools python3-wheel`

Under line 481

2022-12-15 23:23 UTC, sig-noi commented
Thanks to @twofaktor & @fabiolucidi for sussing out the OTS install error that I must have gotten and forgotten. Dependencies install line added.

2022-12-16 11:52 UTC, twofaktor approved these changes

2022-12-16 11:53 UTC, twofaktor approved these changes
tACK! Let's go to the master!

2022-12-16 11:53 UTC, merged