[UPDATE BONUS GUIDE] Fulcrum: Add TCP
raspibolt/raspibolt pull request #1197
Opened 2022-11-28 16:54 UTC by DanielPX1

#### What

Add TCP as default for Fulcrum users

### Why

More ways to connect to Fulcrum server. Issues have been found for example on BlueWallet, when using SLL + Tor. 

#### How

Updating guide

#### Scope

- [ ] review

2022-11-29 16:51 UTC, twofaktor requested changes

2022-11-29 16:51 UTC, twofaktor commented on guide/bonus/bitcoin/fulcrum.md
> +Fulcrum is a replacement for an Electrs, these two services cannot be run at the same time (due to the same standard ports used). Performance issues have been found on Raspberry Pi 4GB, it is recomme
Change to -> 

Fulcrum is a replacement for an Electrs, these two services cannot be run at the same time (due to the same standard ports used), remember to stop Electrs doing "sudo systemctl stop electrs". Performance issues have been found on Raspberry Pi 4GB, it is recommended to install Fulcrum on 8GB RAM version.

2022-11-29 17:00 UTC, twofaktor commented
Recover comment about TCP connection in this [line](https://github.com/raspibolt/raspibolt/pull/1197/files#diff-730f9901c4e7cac9c3b645e8bbe633d5e208fa99886bbee3fc28d2c873c3b8a0R260): 

`RaspiBolt uses SSL as default for Fulcrum, but some wallets like [BlueWallet](https://bluewallet.io/) do not support SSL over Tor. You may as well need to use TCP for other reasons.`

2022-11-29 17:31 UTC, DanielPX1 commented on guide/bonus/bitcoin/fulcrum.md
> +Fulcrum is a replacement for an Electrs, these two services cannot be run at the same time (due to the same standard ports used). Performance issues have been found on Raspberry Pi 4GB, it is recomme
Resolved

2022-11-30 12:10 UTC, DanielPX1 commented
Not sure I understood what line you mean, but I have put it at the start of a guide @twofaktor 

> Recover comment about TCP connection in this [line](https://github.com/raspibolt/raspibolt/pull/1197/files#diff-730f9901c4e7cac9c3b645e8bbe633d5e208fa99886bbee3fc28d2c873c3b8a0R260):
> 
> `RaspiBolt uses SSL as default for Fulcrum, but some wallets like [BlueWallet](https://bluewallet.io/) do not support SSL over Tor. You may as well need to use TCP for other reasons.`

2022-11-30 17:25 UTC, twofaktor commented
> Not sure I understood what line you mean, but I have put it at the start of a guide @twofaktor
> 
> > Recover comment about TCP connection in this [line](https://github.com/raspibolt/raspibolt/pull/1197/files#diff-730f9901c4e7cac9c3b645e8bbe633d5e208fa99886bbee3fc28d2c873c3b8a0R260):
> > `RaspiBolt uses SSL as default for Fulcrum, but some wallets like [BlueWallet](https://bluewallet.io/) do not support SSL over Tor. You may as well need to use TCP for other reasons.`

Line 262, but is fine anyway

tACK!

2022-11-30 17:26 UTC, twofaktor approved these changes

2022-11-30 21:26 UTC, DanielPX1 commented
Great!

2022-12-01 13:52 UTC, DanielPX1 commented
Did the line 262 in the end, it looks much better. I added one more sentence as well. 

@twofaktor

2022-12-02 10:53 UTC, twofaktor approved these changes
tACK! Does some other maintainer want to review this?

2022-12-04 17:45 UTC, twofaktor commented
Let's go to the master! 🚀

2022-12-04 17:45 UTC, merged