Update lightning-client.md
raspibolt/raspibolt pull request #1200
Opened 2022-12-02 14:27 UTC by Swissnode

#### What

Added two variables $VERSION and $DISTRO so that users upgrading to a version that is not already mirrored in the documentation only have to change the VERSION variable once and can merely copy-paste the other lines

### Why

Helps users to upgrade quicker. Very simple change too!

#### How

Code change to add the two variables mentioned above

#### Scope

- [ ] significant change to core configuration
- [ ] independent bonus guide
- [ ] simple bug fix

Fixes # (link issue)
N/A - not a fix

#### Test & maintenance

Can be tested by merely updating a future lnd upgrade using it

2022-12-02 19:03 UTC, kristapsk commented on guide/lightning/lightning-client.md
> +  $ VERSION="v0.15.5-beta"
It creates variable and assigns value to it. Works the same way in interactive bash shell and bash scripts.

2022-12-02 19:04 UTC, kristapsk commented
Concept ACK. Will be able to look at it more carefully and test in a few days.

2022-12-02 23:50 UTC, vicariousdrama commented on guide/lightning/lightning-client.md
> +  $ gpg --verify manifest-roasbeef-$VERSION.sig manifest-v0.15.5-beta.txt
Need the $VERSION reference to be used in the manifest filename as well.

2022-12-04 21:40 UTC, kristapsk commented on guide/lightning/lightning-client.md
> +  $ wget https://github.com/lightningnetwork/lnd/releases/download/$VERSION/$DISTRO-$VERSION.tar.gz
I think this makes more sense.
```suggestion
  $ DISTRO="linux-arm64"
  $ wget https://github.com/lightningnetwork/lnd/releases/download/$VERSION/lnd-$DISTRO-$VERSION.tar.gz
```

2022-12-04 21:40 UTC, kristapsk commented on guide/lightning/lightning-client.md
> +  > lnd-linux-arm64-$VERSION.tar.gz: OK
You will not have `$VERSION` but actual version in output here.
```suggestion
  > lnd-linux-arm64-v0.15.5-beta.tar.gz: OK
```

2022-12-05 08:26 UTC, twofaktor commented
Good add-on! This will go to agility the updating process of the services a lot. BTW: Could apply this to other services installation e.g to the Bitcoin client as well?

2023-01-09 17:08 UTC, twofaktor requested changes

2023-01-09 17:08 UTC, twofaktor commented on guide/lightning/lightning-client.md
> +  $ VERSION="v0.15.5-beta"
Should we call this `LNDVERSION="v0.15.5-beta"` to can use different variables for each service in the future?

2023-01-09 17:08 UTC, twofaktor commented on guide/lightning/lightning-client.md
> +  $ DISTRO="lnd-linux-arm64"
Should we call this `LNDDISTRO="v0.15.5-beta"` to can use different variables for each service in the future? 

i.e: BTCVERSION / BTCDISTRO

2023-01-31 17:53 UTC, Mynima commented
> Good add-on! This will go to agility the updating process of the services a lot. BTW: Could apply this to other services installation e.g to the Bitcoin client as well?

yeah I was wondering the same thing. It would be great to add this same methodology with the other sections. Def think Bitcoin Client is a good place to start.

2023-01-31 18:11 UTC, Mynima reviewed
ACK Couple of minor comments to be resolved. Have tested throughout without issue.

2023-01-31 18:11 UTC, Mynima commented on guide/lightning/lightning-client.md
> +  > lnd-linux-arm64-$VERSION.tar.gz: OK
@Swissnode this minor update still outstanding

2023-01-31 18:11 UTC, Mynima commented on guide/lightning/lightning-client.md
> +  $ gpg --verify manifest-roasbeef-$VERSION.sig manifest-v0.15.5-beta.txt
@Swissnode this minor update still outstanding

2023-01-31 21:22 UTC, twofaktor commented on guide/lightning/lightning-client.md
> +  $ wget https://github.com/lightningnetwork/lnd/releases/download/$VERSION/$DISTRO-$VERSION.tar.gz
DISTRO variable is not necessary, RaspiBolt will be always for arm64

2023-01-31 21:24 UTC, twofaktor commented
> $ BVERSION="24.0.1" 

Why "BVERSION" and not "VERSION" ??

2023-01-31 22:16 UTC, Mynima commented
> > $ BVERSION="24.0.1"
> 
> Why "BVERSION" and not "VERSION" ??

Absolutely no reason to not be VERSION and probably should be for consistency.

2023-02-01 10:29 UTC, twofaktor commented
> > > $ BVERSION="24.0.1"
> > 
> > 
> > Why "BVERSION" and not "VERSION" ??
> 
> Absolutely no reason to not be VERSION and probably should be for consistency.

Environment variables are temporal definitions, these only keep in an current session

2023-02-01 10:32 UTC, twofaktor commented
@Swissnode are you available to do modifications? do you prefer we close this PR and I open a new one so I can take charge

2023-04-27 06:36 UTC, Mynima commented
yo @Swissnode would you have time to update this one for the new LND release [lnd v0.16.1-beta](https://github.com/lightningnetwork/lnd/releases/tag/v0.16.1-beta), I'm happy to do the testing when I upgrade at the weekend. Be great to get this PR closed out.

2023-06-02 06:10 UTC, Swissnode commented on guide/lightning/lightning-client.md
> +  $ gpg --verify manifest-roasbeef-$VERSION.sig manifest-v0.15.5-beta.txt
oh shit sorry, didn't see that, as I hardly ever log on to Github.

Will get on it...

2023-06-02 06:12 UTC, Swissnode commented on guide/lightning/lightning-client.md
> +  > lnd-linux-arm64-$VERSION.tar.gz: OK
yeah i didn't realise... on it... (my first ever PR)

2023-06-02 06:21 UTC, Swissnode commented
Hey guys,

Really sorry for the delay - I will try and get on my account more often.

I implemented the changes in my fork. Can you have a look?

@twofaktor thanks

2023-06-03 07:22 UTC, Mynima commented
> Could we add Bitcoin Core and other possible services to this PR too?
> 
> I already integrated that on MiniBolt guide, we could get references of there if you agree

Yeah I think this could be a good idea to get them done at the same time. Will you be able to do that @Swissnode?

2023-06-13 21:24 UTC, Swissnode commented
> > Could we add Bitcoin Core and other possible services to this PR too?
> > I already integrated that on MiniBolt guide, we could get references of there if you agree
> 
> Yeah I think this could be a good idea to get them done at the same time. Will you be able to do that @Swissnode?

Yeah I guess I can do that!!

Excuse my Github noobishness on this front. I assume I go into my own SwissNode repository and do the changes there correct? Do I somehow have to tag WHICH files are included or will Github assume that ALL changes i make to my repository will be taken into account for this PR?

2023-06-13 21:47 UTC, Swissnode commented
ok @Mynima and @twofaktor 

I see it does pick up all the files I changed so I am now fairly sure I got the changes correctly made. Wanna review and pull them in?

Updated bitcoin-client.md and lightning-client.md

2023-06-14 09:28 UTC, twofaktor requested changes

2023-06-14 09:28 UTC, twofaktor commented on guide/bitcoin/bitcoin-client.md
> +  $ wget https://bitcoincore.org/bin/$VERSION_CORE/$VERSION-aarch64-linux-gnu.tar.gz
```suggestion
  $ wget https://bitcoincore.org/bin/bitcoin-core-$VERSION/bitcoin-$VERSION-aarch64-linux-gnu.tar.gz
```

2023-06-14 09:28 UTC, twofaktor commented on guide/bitcoin/bitcoin-client.md
> +  $ VERSION="bitcoin-25.0"
```suggestion
  $ VERSION="25.0"
```

2023-06-14 09:28 UTC, twofaktor commented on guide/bitcoin/bitcoin-client.md
> +  $ wget https://bitcoincore.org/bin/$VERSION_CORE/SHA256SUMS
```suggestion
  $ wget https://bitcoincore.org/bin/bitcoin-core-$VERSION/SHA256SUMS
```

2023-06-14 09:28 UTC, twofaktor commented on guide/bitcoin/bitcoin-client.md
> +  $ wget https://bitcoincore.org/bin/$VERSION_CORE/SHA256SUMS.asc
```suggestion
  $ wget https://bitcoincore.org/bin/bitcoin-core-$VERSION/SHA256SUMS.asc
```

2023-06-14 09:28 UTC, twofaktor commented on guide/bitcoin/bitcoin-client.md
> +  *  https://bitcoincore.org/bin/bitcoin-25.0/SHA256SUMS.ots
```suggestion
  *  https://bitcoincore.org/bin/bitcoin-core-25.0/SHA256SUMS.ots
```

2023-06-14 09:28 UTC, twofaktor commented on guide/bitcoin/bitcoin-client.md
> +  *  https://bitcoincore.org/bin/bitcoin-25.0/SHA256SUMS
```suggestion
  *  https://bitcoincore.org/bin/bitcoin-core-25.0/SHA256SUMS
```

2023-06-14 09:28 UTC, twofaktor commented on guide/bitcoin/bitcoin-client.md
> +  $ tar -xvf $VERSION-aarch64-linux-gnu.tar.gz
```suggestion
  $ tar -xvf bitcoin-$VERSION-aarch64-linux-gnu.tar.gz
```

2023-06-14 09:28 UTC, twofaktor commented on guide/bitcoin/bitcoin-client.md
> +  $ sudo install -m 0755 -o root -g root -t /usr/local/bin $VERSION/bin/*
```suggestion
  $ sudo install -m 0755 -o root -g root -t /usr/local/bin bitcoin-$VERSION/bin/*
```

2023-06-14 09:28 UTC, twofaktor commented on guide/lightning/lightning-client.md
> +  $ VERSION="v0.15.5-beta"
```suggestion
  $ VERSION="0.16.3"
```

2023-06-14 09:28 UTC, twofaktor commented on guide/lightning/lightning-client.md
> +  $ wget https://github.com/lightningnetwork/lnd/releases/download/$VERSION/lnd-linux-arm64-$VERSION.tar.gz
```suggestion
  $ wget https://github.com/lightningnetwork/lnd/releases/download/v$VERSION-beta/lnd-linux-arm64-v$VERSION-beta.tar.gz
```

2023-06-14 09:28 UTC, twofaktor commented on guide/lightning/lightning-client.md
> +  $ wget https://github.com/lightningnetwork/lnd/releases/download/$VERSION/manifest-$VERSION.txt
```suggestion
  $ wget https://github.com/lightningnetwork/lnd/releases/download/v$VERSION-beta/manifest-v$VERSION-beta.txt
```

2023-06-14 09:28 UTC, twofaktor commented on guide/lightning/lightning-client.md
> +  $ wget https://github.com/lightningnetwork/lnd/releases/download/$VERSION/manifest-roasbeef-$VERSION.sig
```suggestion
  $ wget https://github.com/lightningnetwork/lnd/releases/download/v$VERSION-beta/manifest-roasbeef-v$VERSION-beta.sig
```

2023-06-14 09:28 UTC, twofaktor commented on guide/lightning/lightning-client.md
> +  $ wget https://github.com/lightningnetwork/lnd/releases/download/$VERSION/manifest-roasbeef-$VERSION.sig.ots
```suggestion
  $ wget https://github.com/lightningnetwork/lnd/releases/download/v$VERSION-beta/manifest-roasbeef-v$VERSION-beta.sig.ots
```

2023-06-14 09:28 UTC, twofaktor commented on guide/lightning/lightning-client.md
> +  $ sha256sum --check manifest-$VERSION.txt --ignore-missing
```suggestion
  $ sha256sum --check manifest-v$VERSION-beta.txt --ignore-missing
```

2023-06-14 09:28 UTC, twofaktor commented on guide/lightning/lightning-client.md
> +  > lnd-linux-arm64-$VERSION.tar.gz: OK
```suggestion
  > lnd-linux-arm64-v$VERSION-beta.tar.gz: OK
```

2023-06-14 09:28 UTC, twofaktor commented on guide/lightning/lightning-client.md
> +  $ gpg --verify manifest-roasbeef-$VERSION.sig manifest-$VERSION.txt
```suggestion
  $ gpg --verify manifest-roasbeef-v$VERSION-beta.sig manifest-v$VERSION-beta.txt
```

2023-06-14 09:28 UTC, twofaktor commented on guide/lightning/lightning-client.md
> +  $ ots verify manifest-roasbeef-$VERSION.sig.ots -f manifest-roasbeef-$VERSION.sig
```suggestion
  $ ots --no-cache verify manifest-roasbeef-v$VERSION-beta.sig.ots -f manifest-roasbeef-v$VERSION-beta.sig
```

2023-06-14 09:28 UTC, twofaktor commented on guide/lightning/lightning-client.md
> +  $ tar -xzf lnd-linux-arm64-$VERSION.tar.gz
```suggestion
  $ tar -xvf lnd-linux-arm64-v$VERSION-beta.tar.gz
```

2023-06-14 09:28 UTC, twofaktor commented on guide/lightning/lightning-client.md
> +  $ sudo install -m 0755 -o root -g root -t /usr/local/bin lnd-linux-arm64-$VERSION/*
```suggestion
  $ sudo install -m 0755 -o root -g root -t /usr/local/bin lnd-linux-arm64-v$VERSION-beta/*
```

2023-06-14 09:28 UTC, twofaktor commented on guide/lightning/lightning-client.md
>    > lnd version 0.15.5-beta commit=v0.15.5-beta
```suggestion
  > lnd version $VERSION-beta commit=v$VERSION-beta
```

2023-06-14 11:08 UTC, Swissnode commented on guide/lightning/lightning-client.md
> +  > lnd-linux-arm64-$VERSION.tar.gz: OK
I think this change is taken care of in a later suggestion... (was getting conflicting lines) - i think we can ignore this suggestion from December...

2023-06-14 11:25 UTC, Swissnode commented
@twofaktor thanks for the help, I think it was more useful for my Github skills than the changes themselves. You are right, was better to have just the numbers in the version and not the word "version". I checked your changes and they all checked out fine...

Think it's good to go - am ignoring the December changes as I think there are superceded

2023-06-14 11:43 UTC, Swissnode commented
I seem to have some "branch conflicts" but tbh i don't understand why it says this. Can you have a look?

2023-06-14 13:07 UTC, twofaktor approved these changes
tACK!

2023-06-14 16:38 UTC, Mynima requested changes
Please update the follow lines of code in the "Future Update for Bitcoin Core" section.

Before this bit add ' VERSION = "25.0"
![image](https://github.com/raspibolt/raspibolt/assets/62206239/870834c4-59c8-45e8-918f-f863981be480)

Then correct the above 4 lines to use "$VERSION"

![image](https://github.com/raspibolt/raspibolt/assets/62206239/24af2439-e3a9-42fc-9ff2-74e0a420b060)

Then correct the above 2 lines to use "$VERSION"

2023-06-14 16:40 UTC, Mynima commented
> ok @Mynima and @twofaktor
> 
> I see it does pick up all the files I changed so I am now fairly sure I got the changes correctly made. Wanna review and pull them in?
> 
> Updated bitcoin-client.md and lightning-client.md

Some minor comments added. Thanks for all the work on this! Last push and we should get it across the line!!

2023-06-14 17:19 UTC, twofaktor commented on guide/lightning/lightning-client.md
> +  $ VERSION="0.16.3"
```suggestion
  $ VERSION="0.16.3"
```
Add before this line:
$ VERSION="25.0"

@Swissnode

2023-06-14 17:20 UTC, twofaktor requested changes
Add before this line: https://github.com/raspibolt/raspibolt/pull/1200/files#diff-1dad6164a6192352aaa1591ee62dc908f604c7df9cdae29a83ba0a0585b91539L528

`$ VERSION=25.0`

2023-06-14 20:02 UTC, Mynima commented
> Add instead of this line: https://github.com/raspibolt/raspibolt/pull/1200/files#diff-1dad6164a6192352aaa1591ee62dc908f604c7df9cdae29a83ba0a0585b91539L528
> 
> `$ VERSION=25.0`
> 
> @Swissnode, please

Both should work tbh

2023-06-14 20:03 UTC, Mynima approved these changes
tACK - LND

Bitcoin guide just needs a few bits added to the "Future Update for Bitcoin Core" section

2023-06-15 11:43 UTC, twofaktor commented
All ready, does someone want to do a final review?

2023-06-15 20:38 UTC, Mynima approved these changes
LGTM 
Bitcoin Core - utACK
LND - tACK

2023-06-16 11:22 UTC, twofaktor approved these changes

2023-06-16 13:50 UTC, twofaktor approved these changes
OK! All ready! Let's go to the master! 🚀

2023-06-16 13:50 UTC, merged

2023-06-19 21:45 UTC, Swissnode commented
exciting! it might be rather banal but it was my first ever PR, so I won't forget it! :D