[NEW BONUS GUIDE] BTCPay Server
raspibolt/raspibolt pull request #1201
Opened 2022-12-02 14:29 UTC by nicheosala

#### What

This guide allows to install BTCPay Server on our Raspibolt.

### Why

BTCPay Server allows to manage Bitcoin and Lightning payments.
It can be useful, for example, to receive donations on a blog.

#### How

The installation of BTCPay Server is possible thanks to the detailed installation guide of this pull request.

#### Scope

- [ ] significant change to core configuration
- [x] independent bonus guide
- [ ] simple bug fix

#### Test & maintenance

Any testing of the following guide, along with bug reporting, would be really appreciated.

2022-12-02 14:59 UTC, ericsupreme commented
i 'd like to test this out on my raspibolt, you can send me the guide!!

2022-12-02 15:50 UTC, satsHIVE commented
Awesome! This has been asked a few times in the Telegram group as well. You can probably find testers of the guide there as well. :)
Can you add a header image/screenshot as the other guides have? Just above TOC.

2022-12-02 19:09 UTC, kristapsk commented
Looks it's time for me to finally look into writing [SatSale](https://github.com/SatSale/SatSale) guide for RaspiBolt. :) BTCPay Server has a lot more features (it's great!), but SatSale is more lightweight alternative, which might be even more important on less powerful hardware, like Raspberry Pi.

2022-12-02 19:10 UTC, kristapsk commented
P.S. Will try to test this in a few days.

2022-12-03 18:17 UTC, ericsupreme commented on guide/bonus/lightning/btcpayserver.md
> +  $ nano /home/btcpay/.nbxplorer/Main/settings.config
hmmmm not sure if this is the place but following the guide up to this point and running "nano /home/btcpay/.nbxplorer/Main/settings.config" says directory does not exist. i confirmed running ls -la i don't have a .nbxplorer directory. any ideas? again sorry if this is the wrong place.

2022-12-03 18:36 UTC, nicheosala commented on guide/bonus/lightning/btcpayserver.md
> +  $ nano /home/btcpay/.nbxplorer/Main/settings.config
Thank you for your feedback! I've just updated the guide: at the beginning, I forgot to make a directory called "src" where to place all the source code. This may be the problem. Please, try following the guide from scratch and let me know.

2022-12-04 21:58 UTC, kristapsk commented on guide/bonus/lightning/btcpayserver.md
> +  $ chmod +x ./dotnet-install.sh
This will not work, `curl` will not download to a file by default. Simplest way would be to just use `wget` here instead.

2022-12-19 18:56 UTC, BoyvdR commented on guide/bonus/lightning/btcpayserver.md
> +  $ nano /home/btcpay/.nbxplorer/Main/settings.config
I've followed the steps and had the same issue. As an experiment I run the run.sh script, it made the config file and exited with an error. After adding the configuration as in the guide it NBXplorer workt... 
Had the same issue with btcpayserver later on, running the run.sh script fixed the issue there aswell

2022-12-20 16:48 UTC, nicheosala commented on guide/bonus/lightning/btcpayserver.md
> +  $ nano /home/btcpay/.nbxplorer/Main/settings.config
A thousand thanks! I forgot to point out that both NBXplorer and BTCPay Server need to be run once, in order to generate the default configuration files. I've just pushed a commit that should fix this issue.

2022-12-21 14:55 UTC, hdlslm commented on guide/bonus/lightning/btcpayserver.md
> +  $ nano /home/btcpay/.nbxplorer/Main/settings.config
@BoyvdR thank you. i will give it another try later on. @nicheosala again great work!!

2022-12-21 15:33 UTC, hdlslm commented on guide/bonus/lightning/btcpayserver.md
> +  $ nano /home/btcpay/.nbxplorer/Main/settings.config
running the run.sh worked for me as well!!! thanks

2022-12-23 14:49 UTC, hdlslm reviewed
ok made it to the btcpay server login page and succesfully logged in.  i had to run run.sh for nbxplorer as well as btcpay per @BoyvdR above. i just  had to add reverse proxy via nginx but after i login i get an warning message that says "BTCPay is expecting you to access this website from http://192. blah.blah.blah/. If you use a reverse proxy, please set the X-Forwarded-Proto header to http" with this link : https://docs.btcpayserver.org/FAQ/Deployment/#cause-3-btcpay-is-expecting-you-to-access-this-website-from
but it didn't seem to work work. i added it to the nginx.conf so still working on it. doesn't seem to effect anything. i can just x out the warning.

2023-01-04 18:34 UTC, jtymoszczuk commented
This is great! not that its advisable, but would this setup work with a neutrino supported node? I'm just looking to test it out first on a neutrino node.

2023-01-04 19:28 UTC, jtymoszczuk commented on guide/bonus/lightning/btcpayserver.md
> +  $ sudo -u postgres psql
i can't sudo. I don't believe user btcpay was ever given sudo privileges?

2023-01-05 00:13 UTC, hdlslm commented on guide/bonus/lightning/btcpayserver.md
> +  $ sudo -u postgres psql
> i can't sudo. I don't believe user btcpay was ever given sudo privileges?

install btcpay as admin. that was the step "prior" to creating btcpay user per guide

2023-01-06 14:46 UTC, kristapsk commented on guide/bonus/lightning/btcpayserver.md
> +  $ ./dotnet-install.sh --channel 6.0
Is this the right way to do .Net install? Gives warning:
```
dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where:
dotnet-install: - The SDK needs to be installed without user interaction and without admin rights.
dotnet-install: - The SDK installation doesn't need to persist across multiple CI runs.
dotnet-install: To set up a development environment or to run apps, use installers rather than this script. Visit https://dotnet.microsoft.com/download to get the installer.
```
There are alternative [manual install](https://learn.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual#manual-install) instructions from Microsoft.

Also, probably we want system wide install of .Net runtime, so that potentially other .Net apps can be ran in the future.

2023-01-08 09:44 UTC, nicheosala commented on guide/bonus/lightning/btcpayserver.md
> +  $ ./dotnet-install.sh --channel 6.0
BTCPay requires dotnet sdk 6.x. Installing dotnet via apt, using the Debian repository, I wasn't able to install it.
I totally agree that a system-wide installation via apt would be much better, but I couldn't figure out how to achieve this on the Raspberry Pi, so I decided to publish the "manual" installation guide for dotnet.
If you can install dotnet sdk 6.0 system-wide using apt, please, create a pull request.

2023-01-08 11:53 UTC, kristapsk commented on guide/bonus/lightning/btcpayserver.md
> +  $ ./dotnet-install.sh --channel 6.0
Haven't tested with Raspbian (don't have working RPi with me now), but with Microsoft package repository works like a charm on Ubuntu Server. And you can even have dotnet 6.0 and 7.0 in parallel. Somebody should try Debian link I posted above.

2023-01-20 12:27 UTC, greenart7c3 requested changes

2023-01-20 12:27 UTC, greenart7c3 commented on guide/bonus/lightning/btcpayserver.md
> +  $ sudo cat /var/lib/tor/hidden_service_rtl/hostname
Should be /var/lib/tor/hidden_service_btcpay/hostname

2023-01-21 07:52 UTC, nicheosala commented on guide/bonus/lightning/btcpayserver.md
> +  $ sudo cat /var/lib/tor/hidden_service_rtl/hostname
Fixed. Thank you!

2023-01-30 21:39 UTC, Mynima commented
I realise this has been open a while. Just wondering if you mind adding an uninstall section at the end?

2023-02-03 19:05 UTC, hdlslm commented
![btcpay](https://user-images.githubusercontent.com/38678012/216685630-82ee2600-1532-46dd-b0fc-53a153aa97c4.png)

so again i am stumped. i was able to get to login page for like a week and then i get the: " This page isn’t working
didn’t send any data. ERR_EMPTY_RESPONSE. "error i tried multiple browsers , tried another computer. everything seems to be running (see attached pic) i setup ngnix  reverse proxy the same as the other installs i.e. electrum etc. i tried removing it and still nothing. any suggestions?

2023-02-24 16:05 UTC, hdlslm commented
> ![btcpay](https://user-images.githubusercontent.com/38678012/216685630-82ee2600-1532-46dd-b0fc-53a153aa97c4.png)
> 
> so again i am stumped. i was able to get to login page for like a week and now i get: " This page isn’t working didn’t send any data. ERR_EMPTY_RESPONSE. "error i tried multiple browsers , tried another computer. everything seems to be running (see attached pic) i setup ngnix reverse proxy the same as the other installs i.e. electrum etc. i tried removing it and still nothing. any suggestions?

i am able to get o the login page via tor not sure why i can't via https anymore.

2023-02-25 07:31 UTC, nicheosala commented
> > ![btcpay](https://user-images.githubusercontent.com/38678012/216685630-82ee2600-1532-46dd-b0fc-53a153aa97c4.png)
> > so again i am stumped. i was able to get to login page for like a week and now i get: " This page isn’t working didn’t send any data. ERR_EMPTY_RESPONSE. "error i tried multiple browsers , tried another computer. everything seems to be running (see attached pic) i setup ngnix reverse proxy the same as the other installs i.e. electrum etc. i tried removing it and still nothing. any suggestions?
> 
> i am able to get o the login page via tor not sure why i can't via https anymore.

@hdlslm The errors you are reporting are not related to the guide. Please, post them elsewhere (Reddit), so as not to cause confusion in this thread.

2023-02-25 07:40 UTC, nicheosala commented on guide/bonus/lightning/btcpayserver.md
> +  $ nano /home/btcpay/src/NBxplorer/run.sh
The command I wrote specifies the absolute path to the file, so it shouldn't be wrong. Could you please check that the `run.sh` file actually exists in the directory? Did you build NBXplorer with the command just above?

2023-03-13 16:39 UTC, greenart7c3 requested changes

2023-03-13 16:39 UTC, greenart7c3 commented on guide/bonus/lightning/btcpayserver.md
> +  WantedBy=multi-user.target
If you restart the service its not killing the proccess.
The service file should be something like (same applies to the nbxexplorer service):

[Unit]
Description=BTCPay Server
Requires=nbxplorer.service
After=nbxplorer.service

[Service]
WorkingDirectory=/home/btcpay/src/btcpayserver
ExecStart=/home/btcpay/src/btcpayserver/run.sh
User=btcpay

Type=simple
PIDFile=/run/btcpayserver/btcpayserver.pid
TimeoutSec=120
RestartSec=30

[Install]
WantedBy=multi-user.target

2023-05-02 17:25 UTC, hdlslm commented
ok now how do we connect our lightning node to btcpay? the use internal node is greyed out!! thanks in advance

2023-06-06 18:27 UTC, jesusangelm commented on guide/bonus/lightning/btcpayserver.md
> +  $ ./dotnet-install.sh --channel 6.0
I'm currently trying this in Raspberry Pi OS and the package manager method doesn't work.


notice the important info on [Microsoft page](https://learn.microsoft.com/en-us/dotnet/core/install/linux-debian):
> Package manager installs are only supported on the x64 architecture. Other architectures, such as Arm, must install .NET by some other means such as with Snap, an installer script, or through a manual binary installation.


The reason the package manager method works for @kristapsk  is probably because he is using Ubuntu, which has the snap package manager with dotnet runtime available.

2023-06-06 22:13 UTC, kristapsk commented on guide/bonus/lightning/btcpayserver.md
> +  $ ./dotnet-install.sh --channel 6.0
I don't use snap, just Ubuntu apt packages from Microsoft.

2023-10-04 22:32 UTC, closed without merging