Update lightning-client.md
raspibolt/raspibolt pull request #1204
Opened 2022-12-02 23:59 UTC by vicariousdrama

Set tlsautorefresh=true.
Fixes #1115

#### What

Add setting to auto refresh TLS cert

### Why

Certs expire (I think setting is 1 year after creation).  And when they do remote queries and RPC calls like unlock wallet can fail.

#### How

Configuration change added to lnd.conf

#### Scope

- [ ] significant change to core configuration
- [ ] independent bonus guide
- [ ] simple bug fix

Fixes #1115

#### Test & maintenance

To test this issue requires running LND for some time and waiting for cert expiration and then check if recreated.

2022-12-04 18:35 UTC, twofaktor approved these changes
tACK! TLS certificates were automatically regenerated! good addon! thanks!

![Captura98723747242983](https://user-images.githubusercontent.com/89636253/205508996-4e29f020-17db-4f53-b57e-3002a6f99175.PNG)
![Captura98723747242](https://user-images.githubusercontent.com/89636253/205509016-e7972aa6-f4ac-42d2-b27b-0663f49f791b.PNG)

2022-12-04 18:48 UTC, twofaktor requested changes

2022-12-04 18:48 UTC, twofaktor commented on guide/lightning/lightning-client.md
> +  tlsautorefresh=1
Change to `tlsautorefresh=true` to standardize with the rest of the guide

Should we add `tlsdisableautofill=true` as well??
```sh
# Do not include the interface IPs or the system hostname in TLS certificate, use first --tlsextradomain as Common Name instead, if set.
tlsdisableautofill=true
 ```

2022-12-04 22:43 UTC, vicariousdrama commented on guide/lightning/lightning-client.md
> +  tlsautorefresh=1
I'm not opposed to that and will make the adjustment.  Here's some context for posterity for anyone curious.

Doing this will default to only using 127.0.0.1 and ::1 in the cert that is created.

This means it'll exclude external facing ipv4 and ipv6 addresses on your local network, along with the hostname (the default operation).  I make use of the auto stuff for my own needs on some, and explicitly declare on others.

Overall, setting `tlsdisableautofill=true` is a greater security posture since it avoids leaking data, and anything essential should be explicitly defined anyways.

For those that want to see what their current certificate has, you can run the following command and review the X509v3 Subject Alternative Name field
```sh
openssl x509 -in /data/lnd/tls.cert -text -noout
```

2022-12-05 08:14 UTC, twofaktor commented
in which case do we use this parameter? could you give an example?

```
# Explicitly define any additional domain names for the certificate that will be created.
# tlsextradomain=raspibolt.local
# tlsextradomain=raspibolt.public.domainname.com
```

2022-12-05 08:19 UTC, twofaktor commented on guide/lightning/lightning-client.md
> +  tlsautorefresh=1
Good!

![Capturaet54t45676u5](https://user-images.githubusercontent.com/89636253/205587553-13ec2a53-cea2-482d-8500-d165de35fac2.PNG)

2022-12-09 20:51 UTC, vicariousdrama commented
> in which case do we use this parameter? could you give an example?
> 
> ```
> # Explicitly define any additional domain names for the certificate that will be created.
> # tlsextradomain=raspibolt.local
> # tlsextradomain=raspibolt.public.domainname.com
> ```

Yes. If you want to use REST access to your node remotely, then you need to have the certificate created to support the addressable point, whether that is by IP address or domain name.  One case for this could be BTCPay server on a different system linking to the Lightning service.  Another scenario is accessing the node via a wallet, like Zeus or BlueWallet.  You can create the certificate and also include the onion address as an extra domain, though specifics on how that is setup may or may not need SSL with Tor etc..

2023-01-06 18:07 UTC, twofaktor approved these changes
Tested ACK!

2023-01-09 09:04 UTC, blckbx approved these changes
tACK

2023-01-09 09:04 UTC, merged