[UPDATE BONUS GUIDE] Sparrow Terminal: Add mixing section
raspibolt/raspibolt pull request #1207
Opened 2022-12-07 17:21 UTC by DanielPX1

#### What

Add steps for user to mix using Sparrow Terminal

### Why

Improvement of the guide as general. Adding a important and requested feature

#### How

Adding following steps

#### Scope

- [ ] review

#### Test & maintenance

Following the guide and reporting errors

2022-12-16 12:26 UTC, twofaktor requested changes

2022-12-16 12:26 UTC, twofaktor commented on guide/bonus/bitcoin/sparrow-terminal.md
> +* Connect Sparrow Terminal to your own Electrs implementation according to steps above
Change to-> Connect Sparrow Terminal to your own Electrum server implementation according to steps above

2022-12-16 12:26 UTC, twofaktor commented on guide/bonus/bitcoin/sparrow-terminal.md
> +  $ sudo apt install tmux
Why install tmux? why is useful in this case of use?

2022-12-16 15:07 UTC, DanielPX1 commented on guide/bonus/bitcoin/sparrow-terminal.md
> +  $ sudo apt install tmux
> Why install tmux? why is useful in this case of use?

AFAIK to run sparrow mixing, wallet needs to stay open in order to work. ST mixing client cannot be run as a service yet - wallet needs to be opened on a boot -> unencrypted + if passphrase present, confirmed by user by typing. Then wallet is kept open and mixing happens. 

Using ctrl + C wallet is closed, so installing TMUX and keeping wallet open on a separate session is necessary. If there is any way without installing tmux / additional software and run sparrow on a background, then that could be preferably used instead of tmux

2022-12-16 18:41 UTC, twofaktor commented on guide/bonus/bitcoin/sparrow-terminal.md
> +  $ sudo apt install tmux
Screen could be the solution --> https://linuxize.com/post/how-to-use-linux-screen/

2022-12-17 13:42 UTC, DanielPX1 commented on guide/bonus/bitcoin/sparrow-terminal.md
> +  $ sudo apt install tmux
looks great, will test

2022-12-19 16:26 UTC, DanielPX1 commented on guide/bonus/bitcoin/sparrow-terminal.md
> +  $ sudo apt install tmux
> Screen could be the solution --> https://linuxize.com/post/how-to-use-linux-screen/

screen does not show the ST GUI properly, the screen is broken. Trying to find solution but no success yet

2023-01-17 15:35 UTC, twofaktor commented on guide/bonus/bitcoin/sparrow-terminal.md
> +  $ sudo apt install tmux
I agree! Tmux worked well for me. We will work to release the mixing section!

2023-01-17 15:48 UTC, twofaktor requested changes

2023-01-17 15:48 UTC, twofaktor commented on guide/bonus/bitcoin/sparrow-terminal.md
> +  $ tmux new -sSparrow
missing space? change to:
```suggestion
  $ tmux new -s sparrow_server
```

[Source](https://www.howtogeek.com/671422/how-to-use-tmux-on-linux-and-why-its-better-than-screen/)
**(Starting a Named tmux Session)** section

2023-01-17 15:48 UTC, twofaktor commented on guide/bonus/bitcoin/sparrow-terminal.md
> +
```suggestion
or use this if you have other sessions opened
  $ tmux a -t sparrow_server
```

2023-01-17 15:48 UTC, twofaktor commented on guide/bonus/bitcoin/sparrow-terminal.md
> +* Connect Sparrow Terminal to your own Electrs implementation according to steps above
```suggestion
* Connect Sparrow Terminal to your own Electrum Server implementation according to the steps above 
```
"To include Fulcrum"

2023-01-17 15:52 UTC, twofaktor requested changes

2023-01-17 15:52 UTC, twofaktor commented on guide/bonus/bitcoin/sparrow-terminal.md
> +  $ sudo apt full-upgrade
```suggestion
```
This line is not necessary, only line before updating and refresh new releases packages

2023-01-18 00:05 UTC, DanielPX1 commented
Commited the changes! @twofaktor

2023-01-19 22:11 UTC, twofaktor approved these changes
tested ACK! Does some more maintainer want to participate in the review? @kristapsk @blckbx

2023-01-20 09:40 UTC, blckbx approved these changes
ut but technicalACK

2023-01-20 09:58 UTC, merged

2023-01-20 09:58 UTC, twofaktor commented
Let's go to the master! :rocket: