Tailscale bonus guide
raspibolt/raspibolt pull request #1227
Opened 2023-01-08 00:14 UTC by greenart7c3

#### What

Added tailscale setup so we can access raspibolt from anywhere.

### Why

With tailscale we can access the raspibolt node over a wireguard vpn.

#### Scope

- [ ] significant change to core configuration
- [ ] independent bonus guide
- [ ] simple bug fix

Fixes # (link issue)

#### Test & maintenance

How can the changes be tested? Is there ongoing maintenance effort? If this is a bonus guide: are you willing to update it from time to time?

#### Animated GIF (optional)

Add some snazz if you feel like it :)

2023-01-08 07:44 UTC, kristapsk commented on guide/bonus/raspberry-pi/tailscale.md
> +[Tailscale](https://github.com/joinmarket-webui/jam) tailscale lets you easily manage access to private resources, quickly SSH into devices on your network, and work securely from anywhere in the wor
URL is not correct.

2023-01-08 10:44 UTC, greenart7c3 commented
Should I show how to connect to zeus, rtl etc too?
Also there's a one command install should we use that instead?

2023-01-09 07:32 UTC, blckbx commented
> Should I show how to connect to zeus, rtl etc too?

I think connecting a mobile wallet / node management app would be a first-class use case.

2023-01-09 10:52 UTC, twofaktor requested changes

2023-01-09 10:52 UTC, twofaktor commented on guide/bonus/raspberry-pi/tailscale.md
> +Status: Not tested v3
Is this right? Should not be "Tested v3" tag?

2023-01-09 10:52 UTC, twofaktor commented on guide/bonus/raspberry-pi/tailscale.md
> +* Go to the dns settings in the tailscale admin [panel] (https://login.tailscale.com/admin/dns)
`[panel] (ht...` spare space 

missing `{:target="_blank"}` tag??

2023-01-09 10:52 UTC, twofaktor commented on guide/bonus/raspberry-pi/tailscale.md
> +* With user "admin", let's install apt-transport-https {:target="_blank"}.
missing `{:target="_blank"}` tag?

2023-01-09 10:56 UTC, twofaktor commented
Don't forget to modify "index.md" file of `raspberry-pi.md` index bonus guide adding "Tailscale" title and a little description to the right. Reference --> https://raspibolt.org/guide/bonus/raspberry-pi/

On new section? @blckbx ? how we could call it?

2023-01-09 11:26 UTC, blckbx commented
> Don't forget to modify "index.md" file of `raspberry-pi.md` index bonus guide adding "Tailscale" title and a little description to the right. Reference --> https://raspibolt.org/guide/bonus/raspberry-pi/
> 
> On new section? @blckbx ? how we could call it?

Wouldn't this fit in "System administration"?

2023-01-18 18:26 UTC, blckbx commented on guide/bonus/raspberry-pi/tailscale.md
> +```
Why reinstalling tailscale on update?

2023-01-18 18:29 UTC, M1ch43lV commented on guide/bonus/raspberry-pi/tailscale.md
> +```
It's the official way to update tailscale. See 
https://tailscale.com/kb/1067/update/

2023-01-18 18:32 UTC, M1ch43lV approved these changes

2023-01-18 22:27 UTC, M1ch43lV commented
I am missing configurations for the firewall when using tailscale. Using tailscale should ensure to secure your node from being attacked from outside. To restrict access for the node one can follow this manual https://tailscale.com/kb/1077/secure-server-ubuntu-18-04/
I have following proposal for the configuration of the ufw firewall:

1. Check UFW status
2. Make sure that SSH connection on standard port 22 is allowed, also without using tailscale
3. Allow tailscale traffic without restriction
4. Allow general outgoing traffic
5. Deny incoming traffic outside from tailscale
6. Enable ufw if not enabled
7. Check status again

```sh
sudo ufw status
sudo ufw allow ssh 
sudo ufw allow in on tailscale0
sudo ufw default allow outgoing
sudo ufw default deny incoming
sudo ufw reload
sudo ufw status
```
8. Remove open ports, e.g. http port 80 or 443 if not needed
```sh
sudo ufw delete 80/tcp
sudo ufw delete 443/tcp
```

2023-01-20 10:24 UTC, blckbx commented
@M1ch43lV 
UFW is handled in security section (https://raspibolt.org/guide/raspberry-pi/security.html#enabling-the-uncomplicated-firewall). Only tailscale-specific settings should be taken care of here.

2023-03-27 17:53 UTC, blckbx approved these changes
utACK

2023-04-03 11:10 UTC, twofaktor requested changes

2023-04-03 11:22 UTC, twofaktor requested changes

2023-04-03 11:22 UTC, twofaktor commented on guide/bonus/raspberry-pi/tailscale.md
> +* Go to the dns settings in the tailscale admin [panel](https://login.tailscale.com/admin/dns){:target="_blank"}
should we add a comment for the previously needed registry process with a GitHub account for example?

2023-04-08 16:49 UTC, greenart7c3 commented on guide/bonus/raspberry-pi/tailscale.md
> +* If you want all ports to be open on the tailscale network you can run the following command:
This would open all ports to the tailscale network, so only those with access to the tailscale account can access the services you have.

2023-04-08 16:51 UTC, greenart7c3 commented on guide/bonus/raspberry-pi/tailscale.md
> +## Configure dns and certificate
I think this should be optional, since not everyone will agree with having the certificate generated by Tailscale.

2023-04-09 19:14 UTC, twofaktor commented on guide/bonus/raspberry-pi/tailscale.md
> +* If you want all ports to be open on the tailscale network you can run the following command:
Why this part is optional then? is important or not?

2023-04-10 11:22 UTC, greenart7c3 commented on guide/bonus/raspberry-pi/tailscale.md
> +* If you want all ports to be open on the tailscale network you can run the following command:
Removed it since firewall is handled in the other guides already

2023-04-10 11:23 UTC, twofaktor commented on guide/bonus/raspberry-pi/tailscale.md
> +```sh
Pay attention to the line that I'm referencing

Push 2 spaces more to standardize with the rest of the guide format in the code. Same with the rest of the guide

2023-04-10 11:25 UTC, twofaktor commented on guide/bonus/raspberry-pi/tailscale.md
> +## Configure dns and certificate
Change to an extra section with an (optional) tag

Ref: eg. Extra (opctiona) --> https://raspibolt.org/guide/bonus/lightning/thunderhub.html#extras

2023-04-10 11:26 UTC, twofaktor commented on guide/bonus/raspberry-pi/tailscale.md
> +* Go to the dns settings in the tailscale admin [panel](https://login.tailscale.com/admin/dns){:target="_blank"}
What about this?

2023-04-10 11:37 UTC, greenart7c3 commented on guide/bonus/raspberry-pi/tailscale.md
> +* Go to the dns settings in the tailscale admin [panel](https://login.tailscale.com/admin/dns){:target="_blank"}
What do you mean with this? Add a comment saying to register with a github account?

2023-04-11 08:55 UTC, twofaktor commented on guide/bonus/raspberry-pi/tailscale.md
> +* Go to the dns settings in the tailscale admin [panel](https://login.tailscale.com/admin/dns){:target="_blank"}
saying the previous registry is needed

2023-04-11 09:01 UTC, blckbx commented on guide/bonus/raspberry-pi/tailscale.md
> +* Go to the dns settings in the tailscale admin [panel](https://login.tailscale.com/admin/dns){:target="_blank"}
The registration for tailscale.com?  Yeah, could be noted. Signing in via Github is just one way to to so.

Suggestion: "Sign in on tailscale.com and go to the DNS settings in tailscale admin section ...."

2023-04-11 09:23 UTC, twofaktor commented on guide/bonus/raspberry-pi/tailscale.md
> +* If you want all ports to be open on the tailscale network you can run the following command:
Did you mean is not needed to apply a specific rule for Tailscale on Firewall because is enough to apply the rules of the services, e.g Electrum, BTC RPC explorer, etc as it does in other sections of the guide?

2023-04-12 10:48 UTC, greenart7c3 commented on guide/bonus/raspberry-pi/tailscale.md
> +* If you want all ports to be open on the tailscale network you can run the following command:
Yes, it's not needed to apply a specific rule for Tailscale

2023-04-15 16:55 UTC, Satsuma-LN commented
Hi, I'm having trouble getting this to work with zeus wallet, wondering if anyone else got it to work? 

Tailscale works for accessing my mempool, thunderhub and ssh but not zeus :(

should the port be something other than 8080 on the zeus app?

2023-04-15 17:38 UTC, greenart7c3 commented
> Hi, I'm having trouble getting this to work with zeus wallet, wondering if anyone else got it to work? 
> 
> Tailscale works for accessing my mempool, thunderhub and ssh but not zeus :(
> 
> should the port be something other than 8080 on the zeus app?

What are you using? Cln or lnd?

2023-04-15 18:58 UTC, twofaktor commented
> Hi, I'm having trouble getting this to work with zeus wallet, wondering if anyone else got it to work? 
> 
> Tailscale works for accessing my mempool, thunderhub and ssh but not zeus :(
> 
> should the port be something other than 8080 on the zeus app?

Definitely Zeus guide should will be adapted to Tailscale bonus guide


Like this:

Add to lnd.conf:

```
restlisten=0.0.0.0:8080
```

Ufw:

```
sudo ufw allow 8080/tcp comment "allow LND rest to anywhere" 
```

2023-04-16 08:19 UTC, edwardbickerton commented
> > Hi, I'm having trouble getting this to work with zeus wallet, wondering if anyone else got it to work?
> > Tailscale works for accessing my mempool, thunderhub and ssh but not zeus :(
> > should the port be something other than 8080 on the zeus app?
> 
> What are you using? Cln or lnd?

Lnd

2023-05-05 18:03 UTC, blckbx requested changes
one more comment and question if you would want to add a "connecting Zeus" section to the guide?

2023-05-05 18:03 UTC, blckbx commented on guide/bonus/raspberry-pi/tailscale.md
> +
```suggestion
```
we already installed `apt-transport-https` when installing Tor (https://raspibolt.org/guide/raspberry-pi/privacy.html#installation)

2023-05-08 11:00 UTC, greenart7c3 commented
> one more comment and question if you would want to add a "connecting Zeus" section to the guide?

Sure, i'll change the Access your node section

2023-05-13 07:39 UTC, blckbx commented on guide/bonus/raspberry-pi/tailscale.md
> +  $ lndconnect --host=abcdefg..............xyz.onion --port=8080
What would you say about replacing the onion address with the Tailscale IP example from above, like `--host=100.100.100.100` to be explicit here (also the comment above)?

2023-05-18 11:29 UTC, blckbx approved these changes
LGTM

2023-05-24 16:04 UTC, twofaktor requested changes

2023-05-24 16:04 UTC, twofaktor commented on guide/bonus/raspberry-pi/tailscale.md
> +  $ sudo tailscale cert machine-name.your-tailscale-domain.ts.net
"machine-name.your-tailscale-domain.ts.net" is it a variable depending on each case?

2023-05-24 16:04 UTC, twofaktor commented on guide/bonus/raspberry-pi/tailscale.md
> +* Replace nginx-selfsigned .crt and .key with machine-name.your-tailscale-domain.ts.net
Does this condition the operation of the connections in the local network?

2023-05-29 08:31 UTC, blckbx commented on guide/bonus/raspberry-pi/tailscale.md
> +### Ride The Lightning
Because @greenart7c3 proposed to add two use cases (node management app and mobile app, RTL and Zeus are the two main core guide tools, "web app" and "mobile app") for Tailscale here: https://github.com/raspibolt/raspibolt/pull/1227#issuecomment-1374797673

2023-07-15 09:50 UTC, closed without merging

2023-07-15 18:20 UTC, twofaktor commented
Hello @greenart7c3 why did you close this PR?