Update with fixing signature check Bitcoin Core + dependencies update
raspibolt/raspibolt pull request #1238
Opened 2023-01-30 18:55 UTC by twofaktor

#### What

New Signature verification process for Bitcoin Core 🔑 – Based the on Guix attestation method to release new Bitcoin Core releases with Bitcoin Core developer's signatures

### Why

Why is this change important?

#### How

How was this change accomplished?

#### Scope

- [ ] significant change to core configuration
- [ ] independent bonus guide
- [ ] simple bug fix

Fixes # (link issue)

#### Test & maintenance

How can the changes be tested? Is there ongoing maintenance effort? If this is a bonus guide: are you willing to update it from time to time?

#### Animated GIF (optional)

Add some snazz if you feel like it :)

2023-01-31 08:28 UTC, blckbx reviewed
verification process tACK
one question on system configuration

2023-01-31 08:28 UTC, blckbx commented on guide/raspberry-pi/system-configuration.md
> +  $ sudo apt install git jq --install-recommends
Why the removal of `wget`, `curl` and `gpg` here?

2023-01-31 09:20 UTC, twofaktor commented on guide/raspberry-pi/system-configuration.md
> +  $ sudo apt install git jq --install-recommends
Are already installed by default on Raspian Lite OS, I tested new installation of RaspiBolt recently and could see: wget/gpg... already installed on version blablaba

2023-01-31 09:39 UTC, blckbx approved these changes
tACK on amd64

2023-01-31 12:18 UTC, twofaktor commented
Does someone want to review this too?

2023-01-31 21:49 UTC, Mynima reviewed
ACK - tested, worked like a charm. Thanks!

2023-01-31 21:49 UTC, Mynima commented on guide/bitcoin/bitcoin-client.md
> +Bitcoin releases are signed by several individuals, each using its own key. To verify the validity of these signatures, you must first import the corresponding public keys into your GPG key database.
```suggestion
Bitcoin releases are signed by several individuals, each using their own key. To verify the validity of these signatures, you must first import the corresponding public keys into your GPG key database.
```

2023-01-31 21:49 UTC, Mynima commented on guide/bitcoin/bitcoin-client.md
> +💡 If appears to you `Command 'jq' not found` you will need to install `jq` with `$ sudo apt install jq`. When it finishes, repeat the step before.
```suggestion
💡 If, instead of the expected output above, you see `Command 'jq' not found` you will need to install `jq` by executing the following command `$ sudo apt install jq`. After which, repeat previous cURL command and verify the results.
```

2023-01-31 21:49 UTC, Mynima commented on guide/bitcoin/bitcoin-client.md
> +* Return to the `tmp` folder and follow the signature check process
```suggestion
* Return to the `tmp` folder and complete the signature check process
```

2023-01-31 21:49 UTC, Mynima commented on guide/bitcoin/bitcoin-client.md
> +  $ curl 'https://api.github.com/repositories/355107265/contents/builder-keys' | jq '.[] .download_url' | xargs -L1 wget -N && curl 'https://api.github.com/repositories/355107265/contents/builder-key
Is it worth adding the note again here in case of an error (Command 'jq' not found)? Since the previous section where it was mentioned would only be applicable to new installations. Anyone upgrading having not followed this initial process may well run into the issue and be confused. Alternatively, you could always hyperlink to that earlier section.

2023-02-01 10:08 UTC, twofaktor commented on guide/bitcoin/bitcoin-client.md
> +  $ curl 'https://api.github.com/repositories/355107265/contents/builder-keys' | jq '.[] .download_url' | xargs -L1 wget -N && curl 'https://api.github.com/repositories/355107265/contents/builder-key
`💡 If appears to you `Command 'jq' not found` you will need to install `jq` with `$ sudo apt install jq`. When it finishes, repeat the step before.`

I think one time is enough

2023-02-01 10:10 UTC, twofaktor commented on guide/bitcoin/bitcoin-client.md
> +  $ curl 'https://api.github.com/repositories/355107265/contents/builder-keys' | jq '.[] .download_url' | xargs -L1 wget -N && curl 'https://api.github.com/repositories/355107265/contents/builder-key
If you have a better solution, tell us

2023-02-01 10:29 UTC, Mynima commented on guide/bitcoin/bitcoin-client.md
> +  $ curl 'https://api.github.com/repositories/355107265/contents/builder-keys' | jq '.[] .download_url' | xargs -L1 wget -N && curl 'https://api.github.com/repositories/355107265/contents/builder-key
OK no problem. Happy with this for now, not difficult to find the info if someone gets the problem during the next Bitcoin Client update.

2023-02-01 10:31 UTC, Mynima approved these changes

2023-02-01 10:45 UTC, kristapsk commented on guide/bitcoin/bitcoin-client.md
> +  $ curl 'https://api.github.com/repositories/355107265/contents/builder-keys' | jq '.[] .download_url' | xargs -L1 wget -N && curl 'https://api.github.com/repositories/355107265/contents/builder-key
This works without `jq` and do one download less.
```suggestion
  $ curl -s "https://api.github.com/repositories/355107265/contents/builder-keys" | grep download_url | grep -oE "https://[a-zA-Z0-9./-]+" | while read url; do curl -s "$url" | gpg --import; done
```

2023-02-01 14:08 UTC, Mynima commented on guide/bitcoin/bitcoin-client.md
> +  $ curl 'https://api.github.com/repositories/355107265/contents/builder-keys' | jq '.[] .download_url' | xargs -L1 wget -N && curl 'https://api.github.com/repositories/355107265/contents/builder-key
If we go ahead with this change let's update "For the future: upgrade Bitcoin Core" as well and remove the `Command 'jq' not found` item below. Also can then revert any changes with ssystem-configuration.md.

2023-02-01 14:41 UTC, twofaktor commented
Changes done! Pending review @Mynima @kristapsk @blckbx

2023-02-01 14:52 UTC, Mynima requested changes
Just the one change, didn't spot it before. I think you need to add the page for the in-page section hyperlinks. I know this was a bug on another guide.

2023-02-01 14:52 UTC, Mynima commented on guide/bitcoin/bitcoin-client.md
> +* Verify the timestamp. If the prompt shows you `-bash: ots: command not found`, ensure that you are installing correctly OTS client in the [proper section](#opentimestamps-client)
```suggestion
* Verify the timestamp. If the prompt shows you `-bash: ots: command not found`, ensure that you are installing correctly OTS client in the [proper section](bitcoin-client.md#opentimestamps-client)
```

2023-02-01 14:58 UTC, Mynima approved these changes

2023-02-01 16:51 UTC, kristapsk commented on guide/bitcoin/bitcoin-client.md
> +  > 100 30520  100 30520    0     0   200k      0 --:--:-- --:--:-- --:--:--  198k
There will be no this part, as updated commands use `curl -s`.

2023-02-01 17:42 UTC, twofaktor commented on guide/bitcoin/bitcoin-client.md
> +  > 100 30520  100 30520    0     0   200k      0 --:--:-- --:--:-- --:--:--  198k
Fixed!

2023-02-01 17:48 UTC, kristapsk approved these changes

2023-02-01 17:48 UTC, merged