[UPDATE BONUS GUIDE] Sparrow Terminal to version 1.7.3
raspibolt/raspibolt pull request #1258
Opened 2023-04-03 18:59 UTC by DanielPX1

#### What

Change ST version to latest version 1.7.3

### Why

Upgraded version of Sparrow 

#### How

Changing links & testing them / key verification. Upgrading output values

#### Test & maintenance

Following guide and reporting issues, output values which do not match

2023-04-03 20:19 UTC, DanielPX1 commented
> utACK
> 
> ```
> $ VERSION="1.7.3"
> ```
> 
> You could also consider adding the above between line 57 and 58, then everywhere else the version is mentioned (58, 59, 60, 72, 85 & 92) replace 1.7.1/1.7.3 with $VERSION. It would bring the future updates of the version number down and make the maintenance a little quicker.
> 
> e.g.
> 
> ```
> $ wget https://github.com/sparrowwallet/sparrow/releases/download/$VERSION/sparrow-server-$VERSION-aarch64.tar.gz
> $ wget https://github.com/sparrowwallet/sparrow/releases/download/$VERSION/sparrow-$VERSION-manifest.txt.asc
> $ wget https://github.com/sparrowwallet/sparrow/releases/download/$VERSION/sparrow-$VERSION-manifest.txt
> ```
> 
> Anyway, see what you think. Not a critical change tbh.

hmm interesting idea. I was following raspibolt template where links point to version directly. But it would for sure save some time. Maybe redirecting user to site for latest version and just changing version number to the latest one? (which they see)

2023-04-03 20:59 UTC, twofaktor commented
> > utACK
> > ```
> > $ VERSION="1.7.3"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You could also consider adding the above between line 57 and 58, then everywhere else the version is mentioned (58, 59, 60, 72, 85 & 92) replace 1.7.1/1.7.3 with $VERSION. It would bring the future updates of the version number down and make the maintenance a little quicker.
> > e.g.
> > ```
> > $ wget https://github.com/sparrowwallet/sparrow/releases/download/$VERSION/sparrow-server-$VERSION-aarch64.tar.gz
> > $ wget https://github.com/sparrowwallet/sparrow/releases/download/$VERSION/sparrow-$VERSION-manifest.txt.asc
> > $ wget https://github.com/sparrowwallet/sparrow/releases/download/$VERSION/sparrow-$VERSION-manifest.txt
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Anyway, see what you think. Not a critical change tbh.
> 
> hmm interesting idea. I was following raspibolt template where links point to version directly. But it would for sure save some time updating. Maybe we could redirect user to sparrow site for the latest version and make them just change version number to the latest one in command? (which they see)
> 
> how does it sound to @twofaktor ?

Sound good there is an abandoned existing PR https://github.com/raspibolt/raspibolt/pull/1200 to integrate this in other guides: If you want, change this PR to integrate this.

2023-04-03 22:32 UTC, DanielPX1 commented
> > > utACK
> > > ```
> > > $ VERSION="1.7.3"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > You could also consider adding the above between line 57 and 58, then everywhere else the version is mentioned (58, 59, 60, 72, 85 & 92) replace 1.7.1/1.7.3 with $VERSION. It would bring the future updates of the version number down and make the maintenance a little quicker.
> > > e.g.
> > > ```
> > > $ wget https://github.com/sparrowwallet/sparrow/releases/download/$VERSION/sparrow-server-$VERSION-aarch64.tar.gz
> > > $ wget https://github.com/sparrowwallet/sparrow/releases/download/$VERSION/sparrow-$VERSION-manifest.txt.asc
> > > $ wget https://github.com/sparrowwallet/sparrow/releases/download/$VERSION/sparrow-$VERSION-manifest.txt
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Anyway, see what you think. Not a critical change tbh.
> > 
> > 
> > hmm interesting idea. I was following raspibolt template where links point to version directly. But it would for sure save some time updating. Maybe we could redirect user to sparrow site for the latest version and make them just change version number to the latest one in command? (which they see)
> > how does it sound to @twofaktor ?
> 
> Sound good, there is an abandoned existing PR #1200 to integrate this in other guides. If you want, change this PR to integrate this.

@twofaktor 
OK it is upgraded, thanks for improvement @Mynima

2023-04-03 22:47 UTC, twofaktor requested changes

2023-04-03 22:47 UTC, twofaktor commented on guide/bonus/bitcoin/sparrow-terminal.md
> +* Look up the [latest Sparrow Wallet release version](https://github.com/sparrowwallet/sparrow/releases), change "$VERSION" value in the prepared links to that number to download Sparrow
You must declare the environment variable before use it

2023-04-03 22:47 UTC, twofaktor commented on guide/bonus/bitcoin/sparrow-terminal.md
>    $ cd /tmp
Add:

```sh
$ VERSION=1.7.3
```

2023-04-04 05:21 UTC, Mynima requested changes
utACK

Just couple of minor updates where we still need to get the version number.

2023-04-04 05:21 UTC, Mynima commented on guide/bonus/bitcoin/sparrow-terminal.md
> +  > gpg: assuming signed data in 'sparrow-$VERSION-manifest.txt'
```suggestion
  > gpg: assuming signed data in 'sparrow-1.7.3-manifest.txt'
```
This is one of the couple of places you need to leave it as the actual version number. Since it is the output from a command rather than the command itself.

2023-04-04 05:21 UTC, Mynima commented on guide/bonus/bitcoin/sparrow-terminal.md
> +  > sparrow-server-$VERSION-aarch64.tar.gz: OK
```suggestion
  > sparrow-server-1.7.3-aarch64.tar.gz: OK
```
This is the other place you need to leave it as the actual version number. Since it is the output from a command rather than the command itself.

2023-04-04 09:25 UTC, Mynima requested changes

2023-04-04 09:25 UTC, Mynima commented on guide/bonus/bitcoin/sparrow-terminal.md
>    $ cd /tmp
```suggestion
  $ VERSION="1.7.3"
  $ cd /tmp
```

2023-04-04 09:25 UTC, Mynima commented on guide/bonus/bitcoin/sparrow-terminal.md
>    $ cd /tmp
This will resolve the issue Twofaktor is referring to.

2023-04-04 09:28 UTC, DanielPX1 commented on guide/bonus/bitcoin/sparrow-terminal.md
>    $ cd /tmp
Thanks! will commit

2023-04-04 09:30 UTC, DanielPX1 commented
Thanks, guess I understood it incorrectly, is it good now? commited all suggested changes

2023-04-04 09:30 UTC, DanielPX1 commented on guide/bonus/bitcoin/sparrow-terminal.md
> +* Look up the [latest Sparrow Wallet release version](https://github.com/sparrowwallet/sparrow/releases), change "$VERSION" value in the prepared links to that number to download Sparrow
Thanks, commited

2023-04-04 10:11 UTC, twofaktor requested changes

2023-04-04 10:15 UTC, twofaktor commented
All LGTM, tACK! Let's go to the main! 🚀

2023-04-04 10:21 UTC, twofaktor requested changes

2023-04-04 10:21 UTC, twofaktor commented on guide/bonus/bitcoin/sparrow-terminal.md
> +* Look up the [latest Sparrow Wallet release version](https://github.com/sparrowwallet/sparrow/releases), change "$VERSION" value in the prepared links to that number to download Sparrow
```suggestion
* Download Sparrow Server and signatures into "/tmp" directory, which is cleared on the reboot. If you want to update or install the latest version, look up the [latest Sparrow Wallet release version](https://github.com/sparrowwallet/sparrow/releases), and change the "VERSION="x.x.x" value line, to that number to download the latest Sparrow server binary.
```

2023-04-04 11:42 UTC, twofaktor approved these changes

2023-04-04 11:44 UTC, twofaktor commented
utACK! Let's go to the master! 🚀

2023-04-04 11:44 UTC, merged