[UPDATE BONUS GUIDE] Fulcrum v1.9.1
raspibolt/raspibolt pull request #1267
Opened 2023-04-19 07:33 UTC by dutu

#### What

1) Update Bonus Guide Fulcrum to v1.9.1
2) Update "Fulcrum upgrade" section to include relevant steps only

### Why

1) New Fulcrum release version
2) Some steps that were part of initial installation are not required for application upgrade

#### How

Update the Bonus Guide

#### Scope

- [ ] significant change to core configuration
- [x ] independent bonus guide
- [x] simple bug fix

#### Test & maintenance

Included steps have been tested to upgrade from v1.9.0

2023-04-19 10:06 UTC, twofaktor commented on guide/bonus/bitcoin/fulcrum.md
> +  $ LATEST_RELEASE=$(wget -qO- https://api.github.com/repos/cculianu/Fulcrum/releases/latest | grep -oP '"tag_name": "v\K(.*)(?=")')
Could this avoid us to can select the version that we want to use?

2023-04-19 10:46 UTC, dutu commented on guide/bonus/bitcoin/fulcrum.md
> +  $ LATEST_RELEASE=$(wget -qO- https://api.github.com/repos/cculianu/Fulcrum/releases/latest | grep -oP '"tag_name": "v\K(.*)(?=")')
Pushed an update, hope it makes is better.

2023-04-27 07:34 UTC, twofaktor requested changes

2023-04-27 07:34 UTC, twofaktor commented on guide/bonus/bitcoin/fulcrum.md
> +  $ RELEASE="1.9.1"
The standard on RaspiBolt guide began to be "VERSION" instead of "RELEASE", check: https://github.com/raspibolt/raspibolt/pull/1200/files // https://github.com/raspibolt/raspibolt/pull/1258/files 

Change this accordingly, change this also in the rest of the guide please

2023-04-27 09:36 UTC, dutu commented on guide/bonus/bitcoin/fulcrum.md
> +  $ RELEASE="1.9.1"
Done

2023-04-27 12:36 UTC, twofaktor requested changes
Change to: `zmqpubhashblock=tcp://127.0.0.1:8433` on line 162:
https://github.com/raspibolt/raspibolt/pull/1267/files#diff-730f9901c4e7cac9c3b645e8bbe633d5e208fa99886bbee3fc28d2c873c3b8a0R162

ref: https://github.com/raspibolt/raspibolt/pull/1180#discussion_r1152976728

Improvement for security reasons

2023-04-27 16:23 UTC, dutu commented
Also added steps to update `zmqpubhashblock` when updating Fulcrum.
These would be good to have in case of an upgrade, since, as per previous installation instruction, `bitcoin.conf` contained old value.

2023-04-27 17:45 UTC, twofaktor requested changes

2023-04-27 17:45 UTC, twofaktor commented on guide/bonus/bitcoin/fulcrum.md
> +  Apr 19 12:20:13 rasp Fulcrum[181811]: [2022-04-19 12:20:13.063] simdjson: version 0.6.0
```suggestion
  Apr 19 12:20:13 rasp Fulcrum[181811]: [2023-04-19 12:20:13.063] simdjson: version 0.6.0
```

2023-04-27 17:45 UTC, twofaktor commented on guide/bonus/bitcoin/fulcrum.md
> +  Apr 19 12:20:13 rasp Fulcrum[181811]: [2022-04-19 12:20:13.063] simdjson: version 0.6.0
2023?
change the rest accordingly

2023-04-27 17:45 UTC, twofaktor commented on guide/bonus/bitcoin/fulcrum.md
> +* Check `bitcoin.conf` and update `zmqpubhashblock` with the correct value if needed. Save and exit
Delete this entire new upgrade section, it is not necessary to repeat the same commands specified above. Only specify restart when you finish "### Download and set up Fulcrum" above section

2023-04-27 19:25 UTC, twofaktor requested changes

2023-04-27 19:25 UTC, twofaktor commented on guide/bonus/bitcoin/fulcrum.md
> +* Start fulcrum service
```suggestion
* Start Fulcrum service
```

2023-04-27 19:25 UTC, twofaktor commented on guide/bonus/bitcoin/fulcrum.md
> +  $ sudo systemctl start fulcrum.service
```suggestion
  $ sudo systemctl start fulcrum
```

2023-04-30 17:23 UTC, twofaktor approved these changes
tACK! Let's go! 🚀

2023-04-30 17:23 UTC, merged