bump Bitcoin Guide to 28.0
raspibolt/raspibolt pull request #1451
Opened 2024-10-29 12:21 UTC by bankersbaddream

#### What

What is the reason of this change?

Update the guide to more accurately follow the process of setting up the latest Bitcoin client

### Why

Why is this change important?

Simplicity for beginners to follow along.

#### Scope

- [ ] significant change to core configuration
- [ ] independent bonus guide
- [*] simple bug fix

2024-10-29 13:07 UTC, kristapsk commented
We treat Bitcoin Core upgrades as "significant change to core configuration" not "simple bug fix". Upgrading, especially between major versions, may cause various incompatibilities with other software, so needs careful testing.

2024-10-30 05:51 UTC, sig-noi requested changes
To allow inbound onion connections, add the following to the Network section of bitcoin.conf

bind=127.0.0.1:8334=onion
bind=127.0.0.1:8333=onion

(line 246)

2024-10-30 07:04 UTC, sig-noi commented
To allow LND 0.18.3 to work, add the following to bitcoin.conf

# Allow LND 18.3 to work
deprecatedrpc=warnings

2024-11-14 06:33 UTC, kristapsk commented
> I will implement a Raspibolt in a couple of days, so I will be able to try this commit with the new core v28. Not going to implement LN, though. Do you suggest anything else to test?

Anything that depends on Bitcoin Core can be affected - Electrum server, Blockchain explorer, JoinMarket, etc. The more things are tested and feedback is given, the better.

2024-11-27 03:47 UTC, sarsey-walker commented
if i had seen this PR before... I did not follow the entirely tutorial, and gosh, some minors are really annoying, like this

> To allow LND 0.18.3 to work, add the following to bitcoin.conf
> deprecatedrpc=warnings

BUT nothing a big deal.
And I installed Alby Hub to manage my channel btw.

2025-01-03 10:40 UTC, gwilkinson01 commented
I upgraded to v28 with no major issues. Only minor issues was indeed lnd v0.18.03 breaking which is fixed when adding ``deprecatedrpc=warnings`` to bitcoin.conf. It's possible that v0.18.04 does not require that fix though but haven't tested yet. 

I also had no issues with incoming onion connections so the above comment from @sig-noi did not apply to me.

2025-01-08 14:00 UTC, gwilkinson01 approved these changes
Looks good. Upgraded to v28 and no issues (0.18.4 lnd is compatible).

2025-01-08 16:16 UTC, blckbx approved these changes
utACK

2025-01-08 16:18 UTC, blckbx commented on guide/bitcoin/bitcoin-client.md
> +* In the next box, drop or upload the SHA256SUMS file* If the timestamps is verified, you should see the following message. The timestamp proves that the checksums file existed on the [release date](
accidently removed line break here?
```suggestion
* In the next box, drop or upload the SHA256SUMS file
* If the timestamps is verified, you should see the following message. The timestamp proves that the checksums file existed on the [release date](https://github.com/bitcoin/bitcoin/releases/tag/v28.0){:target="_blank"} of Bitcoin Core v28.0.
```

2025-01-15 10:03 UTC, lustremedia commented
So 28.0 bitcoin core works fine with the latest electrs 0.10.8 on raspi 5 using bookworm. We should start a version 4 of raspibolt taking newest hardware/software into consideration. I have forked and started a branch bookworm on my repo where I documented my journey so far. Changes are not massive so far, but I haven't implemented LND.

2025-05-15 10:43 UTC, closed without merging