Add Bonus Guide: Installation ThunderHub
raspibolt/raspibolt pull request #735
Opened 2021-06-17 16:22 UTC by d-hoffi

I installed ThunderHub on my Raspibolt. The following Guide describes my steps and setup.

2021-07-17 21:07 UTC, d-hoffi commented
and I also updated the SCB part, which already existed. (new pictures and just some small text changes)

2021-07-24 15:22 UTC, Stadicus commented
Will need to test this more in-depth, unless someone else can attest that everything works.

2021-07-25 05:42 UTC, weasel3 commented
Oh nice, thank you.
I assume you used the btcexplorer guide as template because there are still some hints in your guide :)

You should correct these before merge.

Additionally you should link the original installation guide from apotdevin.
Some words about security mesures should also not avoided since the original guide dives deep into this topic by configuring quite a few things.

2021-08-09 22:10 UTC, d-hoffi commented
Yes I used btcrpcexplorer as template. Unfortunately I don't know much about the security risks that may come with thunderhub (and with the "wrong" configuration)

I linked the original [guide](https://github.com/apotdevin/thunderhub#thunderhub---lightning-node-manager) and hopefully I removed all "btcrpcexplorer" parts out of my file.

2021-12-13 10:52 UTC, VajraOfIndra commented
@real-doman Would you like to open a PR again to include ThunderHub as a new bonus guide? It would be great to add to the +Lightning section of the Bonus Section! 

We use a new file naming convention and formatting for v3, happy to help with this if needed.

2022-01-05 09:22 UTC, VajraOfIndra commented on bonus/lightning/thunderhub.md
> +[Thunderhub](https://github.com/apotdevin/thunderhub) is an open source LND node manager where you can manage and monitor your node on any device or browser. It allows you to take control of the ligh
```suggestion
[Thunderhub](https://github.com/apotdevin/thunderhub) is an open source LND node manager where you can manage and monitor your node on any device or browser. It allows you to take control of the lightning network with a simple and intuitive UX and the most up-to-date tech stack.
```
```suggestion
[Thunderhub](https://github.com/apotdevin/thunderhub){:target="_blank"} is an open source LND node manager where you can manage and monitor your node on any device or browser. It allows you to take control of the lightning network with a simple and intuitive UX and the most up-to-date tech stack.
```

For external links, we add "{:target="_blank"}" after the brackets to ensure that it will open in a new tab (it's a feature of [Just the Docs](https://pmarsceill.github.io/just-the-docs/), the Jekyll theme used for the guide.

2022-01-05 09:25 UTC, VajraOfIndra commented on bonus/lightning/thunderhub.md
> +![thunderhub](../../images/75_thunderhub.png)
The picture is a screenshot of the Lightning Terminal rather than ThunderHub.

2022-01-05 09:50 UTC, VajraOfIndra commented on bonus/lightning/thunderhub.md
> +We do not want to run the thunderhub code alongside `bitcoind` and `lnd` because of security reasons.
```suggestion
We do not want to run the ThunderHub code alongside `bitcoind` and `lnd` because of security reasons.
```
Just nitpicking there :)

2022-01-05 09:50 UTC, VajraOfIndra commented on bonus/lightning/thunderhub.md
> +We are going to install thunderhub in the home directory since it doesn't take much space.
```suggestion
We are going to install ThunderHub in the home directory since it doesn't take much space.
```

2022-01-05 09:51 UTC, VajraOfIndra commented on bonus/lightning/thunderhub.md
> +* Create a new user with  your `password[A]`. The new user needs read-only access to the `tls.cert` and our `admin.macaroon`,
```suggestion
* Create a new user. The new user needs read-only access to the `tls.cert` and our `admin.macaroon`, 
```

2022-01-05 09:52 UTC, VajraOfIndra commented on bonus/lightning/thunderhub.md
> +  $ sudo adduser thunderhub
```suggestion
  $ sudo adduser --disabled-password --gecos "" thunderhub
```

2022-01-05 09:54 UTC, VajraOfIndra commented on bonus/lightning/thunderhub.md
> +  $ sudo adduser thunderhub bitcoin
```suggestion
  $ sudo adduser thunderhub lnd
```

The owner of the LND data in v3 is now "lnd"

2022-01-05 09:55 UTC, VajraOfIndra commented on bonus/lightning/thunderhub.md
> +  so we add him to the "bitcoin" group. Open a new session.
```suggestion
  so we add him to the "lnd" group. Open a new session.
```

The owner of the LND data in v3 is now "lnd"

2022-01-05 09:57 UTC, VajraOfIndra commented on bonus/lightning/thunderhub.md
> +```
```suggestion
  ```sh
  $ git clone https://github.com/apotdevin/thunderhub.git
  $ cd thunderhub
  $ npm install
  $ npm run build
  ```
```

Adding two spaces in front of code block for consistency

2022-01-05 09:59 UTC, VajraOfIndra commented on bonus/lightning/thunderhub.md
> +* If the version is v12.0 or above, you can move to the next section. If NodeJS is not installed, follow [this guide](https://raspibolt.org/btcrpcexplorer.html#install-nodejs) to install it.
```suggestion
* If the version is v14.15 or above, you can move to the next section. If NodeJS is not installed, follow [this guide](https://raspibolt.org/btcrpcexplorer.html#install-nodejs) to install it.
```

2022-01-05 09:59 UTC, VajraOfIndra commented on bonus/lightning/thunderhub.md
> +* NojeJS v14.0 or above should have been installed for the BTC RPC Explorer. We can check our version of NodeJS with user "admin":
```suggestion
* NojeJS v14.15 or above should have been installed for the BTC RPC Explorer. We can check our version of NodeJS with user "admin": 
```

ThunderHub now recommends to have NodeJS v14.15 or above: https://docs.thunderhub.io/setup/

2022-01-05 10:28 UTC, VajraOfIndra commented on bonus/lightning/thunderhub.md
> +* Edit the configuration file. Switch to `thunderhub` user for this.
```suggestion
* Still with user "thunderhub", edit the configuration file.
```

As we are already using the user "thunderhub", we could maybe just ad a reminder "Still with user .." (that's how Stadicus advised me to deal with these situations)

2022-01-05 10:28 UTC, VajraOfIndra commented on bonus/lightning/thunderhub.md
> +  $ sudo su - thunderhub
```suggestion
```

2022-01-05 10:37 UTC, VajraOfIndra commented on bonus/lightning/thunderhub.md
> +  $ nano ~/thunderhub/.env
```suggestion
  $ cp ~/thunderhub/.env ~/thunderhub/.env.local
  $ nano ~/thunderhub/.env.local
```

Maybe we could create a .env.local config file as recommended by ThunderHub, to avoid losing the configuration when updating the program, wdyt?

2022-01-06 16:33 UTC, real-doman reviewed
I used this guide on my RaspiBolt v3 to install thunderhub successful.

2022-02-01 07:04 UTC, Stadicus commented
Don't forget to add an entry on https://raspibolt.org/bonus/lightning/

2022-02-01 12:02 UTC, real-doman commented
> Don't forget to add an entry on https://raspibolt.org/bonus/lightning/

right, good point. I added thunderhub to the index.md

2022-02-01 12:57 UTC, VajraOfIndra requested changes
Just the first part of a review dealing with minor things, mostly to be consistent with the rest of the guide.

I think the main thing to discuss is how to configure ThunderHub and the login method. I'm not sure what's the best/most secure option is for us...

2022-02-01 12:57 UTC, VajraOfIndra commented on bonus/lightning/index.md
> +## Node management
I propose we move this entry under "Dashboard & Wallets", and under the heading "GUI - Web". The Lightning Terminal bonus guide would also be placed under this "GUI - Web" sub-heading.

"GUI - Web" or "GUI - Browser"? not sure which ine would be the more semantically meaningful..

2022-02-01 12:57 UTC, VajraOfIndra commented on bonus/lightning/index.md
> +* **[Thunderhub](thunderhub.md)** - a browser interface to mange all parts of your LN node like forwarding fees, channel opening/closeing, usage of lnurl and much more.
```suggestion
* **[ThunderHub](thunderhub.md)** - a browser interface to manage all parts of your LN node like forwarding fees, channel opening/closing, usage of lnurl and much more.
```

Fixing a couple of typos

2022-02-01 12:57 UTC, VajraOfIndra commented on bonus/lightning/thunderhub.md
> +title: Installation Thunderhub
```suggestion
title: ThunderHub
```

Nitpicking here, just for consistency with other guide (afaik we never use Installation just the title of the program) and for spelling of ThunderHub (with a capital H like in their repo)

2022-02-01 12:57 UTC, VajraOfIndra commented on bonus/lightning/thunderhub.md
> +# Bonus Guide: Install Thunderhub
```suggestion
# Bonus Guide: Install ThunderHub
```

2022-02-01 12:57 UTC, VajraOfIndra commented on bonus/lightning/thunderhub.md
> +[Thunderhub](https://github.com/apotdevin/thunderhub){:target="_blank"} is an open source LND node manager where you can manage and monitor your node on any device or browser. It allows you to take c
```suggestion
[ThunderHub](https://github.com/apotdevin/thunderhub){:target="_blank"} is an open source LND node manager where you can manage and monitor your node on any device or browser. It allows you to take control of the lightning network with a simple and intuitive UX and the most up-to-date tech stack.
```

2022-02-01 12:57 UTC, VajraOfIndra commented on bonus/lightning/thunderhub.md
> +### Check NodeJS
```suggestion
### Check Node.js
```

2022-02-01 12:57 UTC, VajraOfIndra commented on bonus/lightning/thunderhub.md
> +* NojeJS v14.15 or above should have been installed for the BTC RPC Explorer. We can check our version of NodeJS with user "admin":
```suggestion
* Noje.js v16 should have been installed for the BTC RPC Explorer and RTL. We can check our version of Node.js with user "admin": 
```

We now use the "Node.js" spelling. Also, the guide is now using v16.

2022-02-01 12:57 UTC, VajraOfIndra commented on bonus/lightning/thunderhub.md
> +  > v14.18.2
```suggestion
  > v16.13.2
```

2022-02-01 12:57 UTC, VajraOfIndra commented on bonus/lightning/thunderhub.md
> +* If the version is v14.15 or above, you can move to the next section. If NodeJS is not installed, follow [this guide](https://raspibolt.org/btcrpcexplorer.html#install-nodejs){:target="_blank"} to i
```suggestion
* If the version is v14.15 or above, you can move to the next section. If Node.js is not installed, follow [this guide](https://raspibolt.org/btcrpcexplorer.html#install-nodejs){:target="_blank"} to install it.
```

2022-02-01 13:57 UTC, real-doman commented on bonus/lightning/index.md
> +## Node management
agreed, that makes sense. I used "GUI - Web"

2022-02-01 13:58 UTC, real-doman commented on bonus/lightning/index.md
> +* **[Thunderhub](thunderhub.md)** - a browser interface to mange all parts of your LN node like forwarding fees, channel opening/closeing, usage of lnurl and much more.
typos fixed

2022-02-01 14:09 UTC, real-doman commented
> 

I share your opinion. The login method as decribed in the guide works for me, but I don't know much about other methods, so I won't change it for now, but I am open for other recommendations.

2022-03-06 19:42 UTC, SSSOCPaulCote reviewed
Any chance we can include setting up nginx reverse proxy for this? I've tried by creating the following file as `admin` user `$ sudo nano /etc/nginx/streams-enabled/thunderhub.conf`
```
upstream thunder {
    server 127.0.0.1:3010
}

server {
    listen 3003 ssl;
    proxy_pass thunder;
}
```
When I access thunderhub via `https://raspibolt.local:3003` it works, when I then use Tor hidden service, I get `connection reset` errors. When I follow the guide as is without nginx, it works with Tor. Not sure why this is the case but it would be useful to load balance if we are opening raspi to the internet for thunderhub. My `torrc` hidden service looks like this when using nginx
```
HiddenServiceDir /var/lib/tor/hidden_service_thunderhub
HiddenServiceVersion 3
HiddenServicePort 80 127.0.0.1:3003
```

2022-03-06 19:42 UTC, SSSOCPaulCote commented on bonus/lightning/thunderhub.md
> +      macaroonPath: '/home/bitcoin/.lnd/data/chain/bitcoin/mainnet/admin.macaroon'
If you set up a symlink `$ ln -s /data/lnd /home/thunderhub/.lnd` you can change `macaroonPath` and `certificatePath` to use `/home/thunderhub/.lnd/...` instead of the `bitcoin` user path. More inline with other tutorials

2022-03-10 13:13 UTC, flexo82 requested changes

2022-03-10 13:13 UTC, flexo82 commented on bonus/lightning/thunderhub.md
> +  WantedBy=multi-user.target
Please add the following to the systemd file in order to ensure it starts up on port 3010

```
[Service]
Environment="PORT=3010"
```

2022-03-10 13:13 UTC, flexo82 commented on bonus/lightning/thunderhub.md
> +
Please add nginx config for reverse proxy.

Here is an example of the nginx config. You can change the listen port to whatever port you think fits best for nginx to list on. I just selected RTL+1 :)

```
upstream thunderhub {
  server 127.0.0.1:3010;
}
server {
  listen 4002 ssl;
  proxy_pass thunderhub;
}
```

2022-03-23 19:58 UTC, blckbx commented on bonus/lightning/thunderhub.md
> +  WantedBy=multi-user.target
Just throwing this in:
Another possibility is adding port parameter to `.env.local`:
`PORT=3010`

2022-03-23 20:29 UTC, blckbx commented on bonus/lightning/thunderhub.md
> +You now have the BTC RPC Explorer running to check the Bitcoin network information directly from your node.
BTC RPC Explorer -> Thunderhub

2022-03-23 20:32 UTC, blckbx commented on bonus/lightning/thunderhub.md
> +  $ npm run build
easier way: `npm run update`

2022-05-17 14:34 UTC, closed without merging