RaspiBolt: version 3
raspibolt/raspibolt pull request #791
Opened 2021-11-19 22:22 UTC by Stadicus

This pull request overhauls the "core" guide in terms of layout, structure, wording, and underlying operating system. 

Preview: https://v3.raspibolt.org

### Core guide structure
The "core" guide is defined as a basic set of guides on how to set up the Raspberry Pi and install a core set of Bitcoin and Lightning tools. It is structured as follows:

* Intro: what is the project and why should you care?
* Backstory: original motivation
* Raspberry Pi: set up the system
* Bitcoin: run Bitcoin Core, Electrum server, and a blockchain explorer
* Lightning: run LND including web-based node management

### Main changes of the RaspiBolt version 3:

#### Raspberry Pi
* Raspberry Pi OS Lite 64-bit
* Only standard Debian commands are used for wider compatibility
* RaspiOS is flashed directly to an external drive, no need for a microSD card (this lowers setup complexity tremendously)
* Individual service users for all applications
* Data directory at `/data/`, by default on the same drive, but anything can be mounted
* NGINX using dedicated reverse proxy include files for all of the exposed ports (Electrum, web apps)
* Tor is installed from Debian repositories
* SSH over Tor

#### Bitcoin
* Bitcoin Core
  * Usage of `rpcauth.py` to create hashed RPC credentials, enabling cookie authentication
  * runs without wallet (prerequisite for group-based access to cookie, set via `sysparms`)
* Electrs 
  * updated to v0.9.2
  * compilation uses Rust repository installation
  * Elects PGP git tag verification
* BTC RPC Explorer 
  * updated to v0.3.2
  * exposed via SSL/TLS at https://raspibolt.local:4000
  * Basic Authentication for web interface

#### Lightning
* LND
  * updated to v0.14.0
  * automated password unlock via password file (todo: offer more secure options)
* Ride The Lightning
  * new addition to RaspiBolt: v0.11.2
  * exposed via SSL/TLS at https://raspibolt.local:4001
 
### Other changes

* new dark-mode with raspberry pink glowing 80's color theme
* added OpenGraph tags for social media previews
* renamed files to a more atomic naming scheme

### Bonus Section out of scope

The Bonus Section remains untouched, as @VajraOfIndra is restructuring them. They should stay/become a great resource for more specific guides with lesser maintenance guarantees. The most relevant guides could be linked directly from the core guide ("further reading").

2021-11-19 23:02 UTC, asvdf commented
I think there is a duplicate:
```
$2 exit
$2 exit
```
in LND page, just one random thing I caught

2021-11-20 11:10 UTC, Stadicus commented
> I think there is a duplicate

It's correct that there are two `exit` commands: the first switches back to the "admin" user, and the second exits the 2nd SSH session. But I agree that the explanation could be much better, will improve. :)

2021-11-20 14:07 UTC, bmml1 commented
Hello,
 
for people migrating from the old guide what would be the best/safest approach:

1. copy whole .lnd folder and adjust config
2. use backup phrase and channel backup

Should a migration explanation be included or do you think it is out of scope?

2021-11-20 14:23 UTC, Stadicus commented
> what would be the best/safest approach for lnd

I haven't done this on a live system with real money, so can't give a conclusive recommendation. From what I know and hear, stopping the old node, moving the whole `.lnd` folder, and starting the new node works just fine. Just make sure that the old node never comes up again!

AFAIK, everything else basically means closing all channels and opening new ones.

Maybe @openoms can provide some more insights?

> Should a migration explanation be included or do you think it is out of scope?

Yes, that's a good suggestions.

2021-11-20 15:56 UTC, asvdf commented
> > what would be the best/safest approach for lnd
> 
> I haven't done this on a live system with real money, so can't give a conclusive recommendation. From what I know and hear, stopping the old node, moving the whole `.lnd` folder, and starting the new node works just fine. Just make sure that the old node never comes up again!
> 
> AFAIK, everything else basically means closing all channels and opening new ones.
> 
> Maybe @openoms can provide some more insights?
> 
> > Should a migration explanation be included or do you think it is out of scope?
> 
> Yes, that's a good suggestions.

This is correct:

1. Stop **once and for all** old node
2. Copy whole contents of .lnd folder over to the new system, best practice is deleting the tls and macaroon files to have then recreated specifically for the new machine
3. On new machine run `lnd` from CLI to check the live output and see what happens
4. Make sure to observe point 1, and never ever run lnd on old node, better yet just delete everything lnd related in there after you verify the new node runs fine

Re: double `exit` I kinda suspected as much but I was too lazy to verify myself, sorry for that

2021-11-20 16:27 UTC, n-e-t-d-i-v-e-r commented
as we chatted in another forum, you should delete these sentences from the manual, because no pw is needed there anymore:
«Switch to “electrs” user and create config file with the following content. Replace <PasswordB> with your actual password [B]»

2021-11-20 16:32 UTC, n-e-t-d-i-v-e-r commented
another question: before my holidays i started to reconfigure my raspibolt with version2 and continued after with version 3. with the result of this «issue»: https://github.com/Stadicus/RaspiBolt/issues/2

do you think somebody can help me do solve this or should i start from the scretch with version 3 again (fullnode syncing etc.)?

2021-11-20 22:35 UTC, Stadicus commented
Thanks @n-e-t-d-i-v-e-r, both issues are related and fixed now: https://v3.raspibolt.org/electrs.html#configuration--indexing

2021-11-23 09:03 UTC, sig-noi commented on security.md
> +  $ sudo openssl req -x509 -nodes -newkey rsa:2048 -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt -subj "/CN=localhost" -days 3650
What about using 4098? I know it's overkill, but from what I gather should not affect performance. Who doesn't like harmless futureproofing?

sudo openssl req -x509 -nodes -newkey rsa:**4096** -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt -subj "/CN=localhost" -days 3650

2021-11-23 09:21 UTC, sig-noi commented on system-configuration.md
> +* Exit your current "pi" user session:
This confused me. Didn't realize it would be ending my SSH session. Might be good to clarify by changing to:

`* Exit your current "pi" user SSH session:`

2021-11-23 09:27 UTC, sig-noi commented on system-configuration.md
> +
Is it important to do this for "pi" user when we aren't going to be using "pi" for the rest of the tutorial? It felt weird to do it here and then be asked to do it again for "admin".

2021-11-23 09:33 UTC, Stadicus commented on system-configuration.md
> +
True. It's just to avoid confusing errors when adding the users. Can be skipped safely, I don't have a strong opinion on this.

2021-11-23 10:00 UTC, sig-noi commented on electrs.md
> +```
I think this refers to a Linux environment? It is confusing from the perspective of a Mac Terminal user (did not work). Could clarify with: 

`If your personal computer runs Linux, you can force Electrum to only use your own server on startup with the following command line arguments:`

2021-11-23 10:26 UTC, sig-noi commented on electrs.md
> +[![Electrum Wallet local](images/50_electrum_wallet_tor.png)](images/50_electrum_wallet_local.png){:target="_blank"}
I believe this may be out of date (image is taken from Electrum 3.3.5) and so was confusing as the Network option tabs have changed. Current Electrum 4.1.5 on Mac OS would be:
`
* In the menu: `Tools > Network`
* In the `Proxy` tab, check `Use Tor proxy at 9050` (if not available, Tor is not properly installed on the client computer)
* In `Overview` tab `Server:` enter your Tor onion address appending the port :50002 (e.g. `gwdllz5g7vky2q4gr45zGuvopjzf33czreca3a3exosftx72ekppkuqd.onion:50002`
* Press `Enter` or click `Close` and check the connection in the console window`
<img width="640" alt="Screen Shot 2021-11-23 at 02 23 14" src="https://user-images.githubusercontent.com/94819106/143007628-962b5ed4-a05c-44bc-b880-825d4d2857ca.png">
<img width="640" alt="Screen Shot 2021-11-23 at 02 23 40" src="https://user-images.githubusercontent.com/94819106/143007635-d97f3508-f664-46d8-ae2c-9d6b4c14a0af.png">

2021-11-23 10:47 UTC, sig-noi requested changes

2021-11-23 10:47 UTC, sig-noi commented on electrs.md
> +[![Electrum Wallet local](images/50_electrum_wallet_tor.png)](images/50_electrum_wallet_local.png){:target="_blank"}
I believe this may be out of date (images are from Electrum 3.3.5) and so was confusing as the Network option tabs have changed. Current Electrum 4.1.5 on Mac OS would be:
`
* In the menu: `Tools > Network`
* In the `Proxy` tab, check `Use Tor proxy at 9050` (if not available, Tor is not properly installed on the client computer)
* In `Overview` tab `Server:` enter your Tor onion address appending the port :50002 (e.g. `gwdllz5g7vky2q4gr45zGuvopjzf33czreca3a3exosftx72ekppkuqd.onion:50002`
* Press `Enter` or click `Close` and check the connection in the console window`
<img width="640" alt="Screen Shot 2021-11-23 at 02 23 14" src="https://user-images.githubusercontent.com/94819106/143007628-962b5ed4-a05c-44bc-b880-825d4d2857ca.png">
<img width="640" alt="Screen Shot 2021-11-23 at 02 23 40" src="https://user-images.githubusercontent.com/94819106/143007635-d97f3508-f664-46d8-ae2c-9d6b4c14a0af.png">

2021-11-23 10:47 UTC, sig-noi commented on electrs.md
> +[![Electrum Wallet local](images/50_electrum_wallet_local.png)](images/50_electrum_wallet_local.png){:target="_blank"}
I believe this may be out of date (images are from Electrum 3.3.5) and so was confusing as the Network option tabs have changed. I would also clarify that this should only be done on LAN without sacrificing privacy. Current Electrum 4.1.5 on Mac OS would be:
`
On a client computer on your RaspiBolt's local area network, you can securely configure [Electrum wallet](https://electrum.org){:target="_blank"} to use your RaspiBolt without Tor:

* In the menu: `Tools > Network`
* In the `Overview` tab, uncheck `Select server automatically`
* Enter the hostname (e.g. `raspibolt.local`) or or ip address (e.g. `192.168.0.20`) of your RaspiBolt in the `Server:` field
appended by the port `50002` (e.g. `raspibolt.local:50002` or `192.168.0.20:50002`)
* Press `Enter` or click `Close` and check the connection in the console window`

<img width="640" alt="Screen Shot 2021-11-23 at 02 38 54" src="https://user-images.githubusercontent.com/94819106/143009794-cad08b71-82ad-43cd-a7b2-656a57ac0619.png">

2021-11-23 10:47 UTC, sig-noi commented on electrs.md
> +```
I think this refers to a Linux environment? It is confusing from the perspective of a Mac Terminal user (did not work). Could clarify with:

`If you run Electrum from on Linux, you can force it to only use your own server on startup with the following command line arguments:`

2021-11-23 10:49 UTC, sig-noi commented on system-configuration.md
> +
Oh I see. I did it so don't know what the confusing errors look like and would defer to your aesthetic.  :)  I may have just been in a critical mood at the time as well, since I was just starting my upgrade from v2.

2021-11-23 11:26 UTC, sig-noi commented on remote-access.md
> +* You should now be able to reach your Pi, either with the hostname `raspibolt.local` or an IP address like `192.168.0.20`.
Would add:

`Note that some routers use the 10.0.0.xxx format for local private network addresses. Please take note because this will be need to be reflected in networking configuration later on.`

2021-11-23 11:52 UTC, sig-noi requested changes

2021-11-23 11:52 UTC, sig-noi commented on btcrpcexplorer.md
> +  ```
I would suggest the following to clarify for the rare users like me who don't have a 192.168 local area network:


If your Raspibolt's IP address is of the form 192.168.0.xxx use:

  ```sh
  $ sudo ufw allow from 192.168.0.0/16 to any port 4000 comment 'allow BTC RPC Explorer SSL from local network'
  $ sudo ufw status
  ```

If your RaspiBolt's IP address is of the form 10.0.1.xxx, use:
  
  ```sh
  $ sudo ufw allow from 10.0.0.0/16 to any port 4000 comment 'allow BTC RPC Explorer SSL from local network'
  $ sudo ufw status
  ```

In case you run into issues and need to change a rule, errors in ufw rules can be removed with:

  ```sh
  $ sudo ufw delete <rule action> from <port> to <port>
  ```
e.g:
  ```sh
  $ sudo ufw delete allow from 192.168.0.0/16 to any port 4000
  ```
`

2021-11-24 11:32 UTC, VajraOfIndra reviewed
Here is the first part of the review, up to the bitcoind guide. I'll have a look at the rest in the next couple of days. 

Just a few suggestions for minor changes.

2021-11-24 11:32 UTC, VajraOfIndra commented on bitcoin-core.md
> +  ```sh
```suggestion
  ```ini
```
As this is a configuration file, shouldn't it be ini or another similar language rather than sh?

2021-11-24 11:32 UTC, VajraOfIndra commented on bitcoin-core.md
> +  ```sh
Same as above, ini rather than sh?
```suggestion
  ```ini
```

2021-11-24 11:32 UTC, VajraOfIndra commented on bitcoin-core.md
> +  ```
I suggest to add a result line showing the first couple of lines, including the expected green 'active' word

2021-11-24 12:12 UTC, bmml1 commented on btcrpcexplorer.md
> +  ```
Hello, I think it would be more userfriendly to delete ufw rules like this:
`sudo ufw status numbered`
`sudo ufw delete <number of rule>`

2021-11-24 13:00 UTC, sig-noi commented on operating-system.md
> +* **That's it.**
Reading about this on https://www.raspberrypi.com/news/raspberry-pi-imager-update/ and https://www.zdnet.com/article/raspberry-pis-imager-tool-just-added-these-new-options/ it sounds like this only sends anonymized information on the version of OS installed. Looking at Rpi's published data 64-lite doesn't even seem to appear at this point. (https://rpi-imager-stats.raspberrypi.com/). I feel fairly confident that this is only related to the Imager App rather than the OS and RPi itself. If that is in fact true, I think this addition would merely raise red flags without improving actual privacy.

I do _imagine_ there is a way to monitor RPi's packets and determine if any telemetry is going on, which I like as a QA process on our end, or as a bonus guide, but not part of the main guide.

2021-11-24 13:06 UTC, sig-noi commented on privacy.md
> +
I like this idea. Making a separate comment about the previous KeePassXC recommendation.

2021-11-24 13:16 UTC, sig-noi requested changes

2021-11-24 13:16 UTC, sig-noi commented on raspibolt_10_preparations.md
> -If you need inspiration for creating your passwords: the [xkcd: Password Strength](https://xkcd.com/936/) comic is funny and contains a lot of truth.
Could add a recommendation for `https://xkpasswd.net/` or something like it as well. Personally I don't mind using it for security phrases (those annoying ones some websites still require) though I haven't considered whether it could have meaningful privacy leaks. +/- could recommend KeePassXC's built in password generator which I gather would be a more privacy leak-proof recommendation.

2021-11-24 15:01 UTC, sig-noi commented on btcrpcexplorer.md
> +It's a database-free, self-hosted Bitcoin blockchain explorer, querying Bitcoin Core and Electrs via RPC.
Nitpicking, but the intro sentence makes running Electrs sound optional but the final sentence makes it sound like BTC RPC Explorer does query Electrs. Are both of these statements true? Is this ambiguity OK?

2021-11-25 07:53 UTC, Stadicus commented on electrs.md
> +```
The command-line argument should be universal, but how to actually start Electrum might be different (change to the proper directory or give full path).

2021-11-25 07:53 UTC, Stadicus commented on electrs.md
> +[![Electrum Wallet local](images/50_electrum_wallet_tor.png)](images/50_electrum_wallet_local.png){:target="_blank"}
Good points, will update!

2021-11-25 07:54 UTC, Stadicus commented on electrs.md
> +[![Electrum Wallet local](images/50_electrum_wallet_local.png)](images/50_electrum_wallet_local.png){:target="_blank"}
Thanks, will update

2021-11-25 07:54 UTC, Stadicus commented on electrs.md
> +```
see comment above, cli args should be universal

2021-11-25 07:55 UTC, Stadicus commented on remote-access.md
> +* You should now be able to reach your Pi, either with the hostname `raspibolt.local` or an IP address like `192.168.0.20`.
Seriously? Never heard of that before. Do you have an example or link?

2021-11-25 07:57 UTC, Stadicus commented on btcrpcexplorer.md
> +  ```
If routers with a `10.0.x.x` subnet really are a thing, I'd just remove the restriction to the local subnet. It does not add much security, as you're behind a NAT anyway. 

Unless you open the ports in your router, the ports are not reachable. And if someone compromises your router, well, then they're in your subnet alread.

2021-11-25 08:00 UTC, Stadicus commented on index.md
> +### Features
For me (Ubuntu, Firefox) they look pretty neat and distinct from the regular text. Can you add a screenshot?

![image](https://user-images.githubusercontent.com/19550140/143402192-cf8de07d-5b87-4419-9d92-757d734f1c12.png)

2021-11-25 08:00 UTC, Stadicus commented on preparations.md
> +* external storage: 1+ TB with USB3, an SSD is recommended
Good point. Do you have links to some resources on this?

2021-11-25 08:01 UTC, Stadicus commented on preparations.md
> +* optional: Raspberry Pi case
I'm not sure this matters too much, I run my nodes without fans in cheap plastic cases. Isn't this more of a personal preference?

2021-11-25 08:05 UTC, Stadicus commented on bitcoin-core.md
> +  ```sh
I know, but I chose the code syntax highlighting on looks, not on technical accuracy... Plain `sh` looks better, otherwise the color coding is hard to read in darkmode.

2021-11-25 08:06 UTC, Stadicus commented on bitcoin-core.md
> +  ```
Again, choosing the code syntax highlighting on looks, not on technical accuracy

2021-11-25 08:06 UTC, Stadicus commented on bitcoin-core.md
> +  ```sh
Again, choosing the code syntax highlighting on looks, not on technical accuracy

2021-11-25 08:09 UTC, Stadicus commented on raspibolt_10_preparations.md
> -Store a copy of your passwords somewhere safe (preferably in an open source password manager like [KeePassXC](https://keepassxc.org/)) and keep your original notes out of sight once your system is up
I'm not sure why downloading / installing the KeePassXC application is more than just that? Of course you can go bonkers with the browser plugins, and syncing different devices, but that's not necessarily needed here. 

I could add something like "..., or whatever you're already using, ..." here, as it really doesn't matter too much.

2021-11-25 08:11 UTC, Stadicus commented on btcrpcexplorer.md
> +It's a database-free, self-hosted Bitcoin blockchain explorer, querying Bitcoin Core and Electrs via RPC.
Good thinking, thanks! :)

2021-11-25 08:30 UTC, dominicus commented on remote-access.md
> +* You should now be able to reach your Pi, either with the hostname `raspibolt.local` or an IP address like `192.168.0.20`.
[XFinity/Comcast gateways implement 10.0.0.1](https://www.xfinity.com/support/articles/view-change-wifi-password#:~:text=Open%20a%20web%20browser%20and,Username%3A%20admin).  Among the largest ISPs in US.

2021-11-25 09:14 UTC, Stadicus commented on remote-access.md
> +* You should now be able to reach your Pi, either with the hostname `raspibolt.local` or an IP address like `192.168.0.20`.
Damn...

2021-11-25 09:22 UTC, VajraOfIndra commented on operating-system.md
> +* **That's it.**
I'm just used to untick any kind of similar boxes just to be on the safe side... but your 'red flag' comment is very interesting, I never thought of that!

2021-11-25 10:41 UTC, Stadicus commented on electrs.md
> +```
I changed the guide from using cli-arguments to editing the configuration file:
https://v3.raspibolt.org/electrs.html#connect-electrum-wallet

I think that's easier across platforms (otherwise you need to change the link in the Window icon, etc). That also solves all outdated instructions regarding the Electrum Network UI.

2021-11-25 10:41 UTC, Stadicus commented on electrs.md
> +[![Electrum Wallet local](images/50_electrum_wallet_tor.png)](images/50_electrum_wallet_local.png){:target="_blank"}
Changed to editing this information directly in the config file

2021-11-25 10:41 UTC, Stadicus commented on electrs.md
> +```
Changed to editing this information directly in the config file

2021-11-25 10:41 UTC, Stadicus commented on electrs.md
> +[![Electrum Wallet local](images/50_electrum_wallet_local.png)](images/50_electrum_wallet_local.png){:target="_blank"}
Changed to editing this information directly in the config file

2021-11-25 10:46 UTC, Stadicus commented on remote-access.md
> +* You should now be able to reach your Pi, either with the hostname `raspibolt.local` or an IP address like `192.168.0.20`.
Changed all `ufw allow from 192.168.0.0/16 to any port 1233` instructions to `ufw allow 1234`. Otherwise I don't think separate IP format does not need to be mentioned specifically,

2021-11-25 10:47 UTC, Stadicus commented on btcrpcexplorer.md
> +  ```
Changed all `ufw allow from 192.168.0.0/16 to any port 1233` instructions to `ufw allow 1234`

2021-11-25 10:50 UTC, Stadicus commented on privacy.md
> +
Added

2021-11-25 10:52 UTC, Stadicus commented on bitcoin-core.md
> +  ```
Ack, added

2021-11-25 18:32 UTC, Stadicus commented
I think all comments are addressed.

2021-11-25 19:33 UTC, VajraOfIndra commented on system-configuration.md
> +---
```suggestion
---

## Check USB3 drive performance

A performant USB3 drive is essential for your node.
The Raspberry Pi 4 supports these out of the box, but is a bit picky.
Some USB3 adapters for external drives are not compatible and need a workaround to be usable.

Let's check if your drive works well as-is, or if additional configuration is needed.

* Install the software to measure the performance of your drive

  ```sh
  $ sudo apt update
  $ sudo apt install hdparm
  ```

* Your external drive should be connected as `/dev/sda1`.
  Check if this is the case and look for the mountpoint `/`

  ```sh
  $ lsblk -pli
  ```

* Measure the speed of your external drive

  ```sh
  $ sudo hdparm -t --direct /dev/sda2
  > Timing O_DIRECT disk reads: 932 MB in  3.00 seconds = 310.23 MB/sec
  ```

If the measured speed is more than 50 MB/s, you're good, no further action needed.

If the speed of your USB3 drive is not acceptable, we need to configure the USB driver to ignore the UAS interface.

Check the [Fix bad USB3 performance](troubleshooting.md#fix-bad-usb3-performance) entry in the Troubleshooting guide to learn how.

* Exit your current "pi" user session and exit SSH

  ```sh
  $ exit
  ```

---
```

I suggest to move the 'exit pi user' lines to the end of the next section (USB3 test) as otherwise we have to exit and then log in again straight away with the "pi" user for the USB3 test. The next section (System update) asking to log in with admin would then makes more sense as we would have then just exited the "pi" user session.

2021-11-25 19:59 UTC, Stadicus commented on system-configuration.md
> +---
Makes sense, thanks!

2021-11-26 13:19 UTC, merged

2021-11-26 15:33 UTC, sig-noi requested changes

2021-11-26 23:10 UTC, Stadicus commented on btcrpcexplorer.md
> +  run `npm audit fix` to fix them, or `npm audit` for details
I did that as well in the past, but according to @saubyk it's not advisable. It might break stuff and cause issues that might be difficult to debug. They take care of vulnerabilities with every release, I guess it's like whack-a-mole :)