add pull request and issue template
raspibolt/raspibolt pull request #796
Opened 2021-11-27 09:49 UTC by Stadicus

Support in issues and collaboration through pull requests was done
without proper guidance. Providing a template for both encourages
the inclusion of essential information.

2021-11-28 09:24 UTC, VajraOfIndra commented on .github/ISSUE_TEMPLATE/bug_report.md
> +Link to the corresponding page and section on https://raspibolt.org
```suggestion
Link to the corresponding page and section on [https://raspibolt.org](https://raspibolt.org).
```

2021-11-28 09:34 UTC, VajraOfIndra requested changes
LGTM, that's a nice addition to the guide! :)

A few typos fixed for consistency. Other than that I think a few lines about how to best add a screenshot would be super useful as I remember I was wonerding how to do that as a new user and I'm still unsure what is considered best practices!

2021-11-28 09:34 UTC, VajraOfIndra commented on .github/ISSUE_TEMPLATE/bug_report.md
> +If applicable, add screenshots to help explain your problem.
As a new user I remember not knowing how to add a screenshot, could we add some suggestions on what the best or recommened practices are for adding screenshots?

2021-11-28 09:34 UTC, VajraOfIndra commented on .github/ISSUE_TEMPLATE/bug_report.md
> + - Hardware platform; [e.g. Raspberry Pi 4, Odroid, ... ]
```suggestion
 - Hardware platform: [e.g. Raspberry Pi 4, Odroid, ... ]
```

2021-11-28 09:34 UTC, VajraOfIndra commented on .github/ISSUE_TEMPLATE/support.md
> +Link to the corresponding page and section on https://raspibolt.org
```suggestion
Link to the corresponding page and section on [https://raspibolt.org](https://raspibolt.org).
```

2021-11-28 09:34 UTC, VajraOfIndra commented on .github/ISSUE_TEMPLATE/support.md
> + - Hardware platform; [e.g. Raspberry Pi 4, Odroid, ... ]
```suggestion
 - Hardware platform: [e.g. Raspberry Pi 4, Odroid, ... ]
```

2021-11-28 09:34 UTC, VajraOfIndra commented on .github/ISSUE_TEMPLATE/support.md
> +If applicable, add screenshots to help explain your problem.
Same comment as for bug report: adding explanations on how to add a screenshot

2021-11-28 09:34 UTC, VajraOfIndra commented on .github/pull_request_template.md
> +- [ ] indipendent bonus guide
```suggestion
- [ ] independent bonus guide 
```

2021-11-28 09:38 UTC, Stadicus commented on .github/ISSUE_TEMPLATE/bug_report.md
> +Link to the corresponding page and section on https://raspibolt.org
Good suggestion, thanks. In Markdown, it's even simpler to make a URL clickable: just write it as `<https://url.com>`

https://stackoverflow.com/a/41348909

2021-11-28 09:40 UTC, Stadicus commented on .github/ISSUE_TEMPLATE/bug_report.md
> +If applicable, add screenshots to help explain your problem.
I'd prefer to see if this is actually is an issue. It's just copy/paste or drag & drop, as mentioned just below the issue text field.

2021-11-28 09:49 UTC, Stadicus commented on .github/ISSUE_TEMPLATE/bug_report.md
> +Link to the corresponding page and section on https://raspibolt.org
Fixed

2021-11-28 09:49 UTC, Stadicus commented on .github/ISSUE_TEMPLATE/bug_report.md
> + - Hardware platform; [e.g. Raspberry Pi 4, Odroid, ... ]
Fixed

2021-11-28 09:49 UTC, Stadicus commented on .github/ISSUE_TEMPLATE/support.md
> +Link to the corresponding page and section on https://raspibolt.org
Fixed

2021-11-28 09:49 UTC, Stadicus commented on .github/ISSUE_TEMPLATE/support.md
> + - Hardware platform; [e.g. Raspberry Pi 4, Odroid, ... ]
Fixed

2021-11-28 09:50 UTC, Stadicus commented on .github/ISSUE_TEMPLATE/support.md
> +If applicable, add screenshots to help explain your problem.
see above, I find it simple enough

2021-11-28 09:50 UTC, Stadicus commented on .github/pull_request_template.md
> +- [ ] indipendent bonus guide
Fixed

2021-11-28 09:50 UTC, Stadicus commented
Updated links and typos and addressed all your comments.

PTAL

2021-11-29 12:39 UTC, VajraOfIndra commented on .github/ISSUE_TEMPLATE/bug_report.md
> +Link to the corresponding page and section on https://raspibolt.org
> 

Good to know. Originally I just wanted to add a dot at the end of the line to be consistent with the rest of the paragraphs, so I thought it would be necessary to add the some hyperkink formatting even though the link was working well without any special formatting at all. Using <> is ideal in the case.

2021-11-29 12:44 UTC, VajraOfIndra commented on .github/ISSUE_TEMPLATE/bug_report.md
> +If applicable, add screenshots to help explain your problem.
Ok, I didn't see the copy/paste and drag & drop suggestions, if it's there then that's great.

2021-11-29 12:46 UTC, VajraOfIndra commented on .github/ISSUE_TEMPLATE/support.md
> +Link to the corresponding page and section on https://raspibolt.org
See above comment about dot at end of sentence

2021-11-29 12:49 UTC, VajraOfIndra commented
> Updated links and typos and addressed all your comments.
> 
> PTAL

I reviewed and resolved all comments. The only one remaining is the dot at the end of the sentence with hyperlinks, see discussions above. just wanted to point it out in case its removal was unintentional.

2021-11-29 12:52 UTC, Stadicus commented on .github/ISSUE_TEMPLATE/bug_report.md
> +Link to the corresponding page and section on https://raspibolt.org
I left it out as I'd expect people to just copy/paste the URL, and not mess up the link with a dot at the end. Doesn't matter too much, though. Good as is?

2021-11-29 13:03 UTC, VajraOfIndra commented on .github/ISSUE_TEMPLATE/bug_report.md
> +Link to the corresponding page and section on https://raspibolt.org
Ok, makes sense to me :)

2021-11-29 13:04 UTC, VajraOfIndra approved these changes

2021-11-29 13:55 UTC, merged