New structure for the 'Bonus Section'
raspibolt/raspibolt pull request #803
Opened 2021-11-28 08:50 UTC by VajraOfIndra

The goals and rationales behind the choices are explained in Issue #788.

This pull-request focuses solely on navigation and content of the index pages ('Bonus Section', 'Bonus Raspberry Pi', 'Bonus Bitcoin' and 'Bonus Lightning' index pages). The content of the Bonus guides themselves has not been updated or modified.

The repo structure for the bonus section is:

|-- (main guide .md files, .yml, license, readme etc)
|-- bonus-section.md
|-- bonus
| |-- bitcoin
| | |-- bonus-bitcoin.md (index page)
| | |-- (bitcoin bonus guides .md files)
| |-- lightning
| | |-- bonus-lightning.md (index page)
| | |-- (lightning bonus guides .md files)
| |-- raspberry_pi
| | |-- raspberry-pi.md (index page)
| | |-- (raspberry pi bonus guides .md files)

For now, the guides are categorized under the following headings (headings to be added or changed as new bonus guides get merged):

* Bonus Raspberry Pi
  * Dashboards & Appearance
  * Security
  * Hardware
* Bonus Bitcoin
  * Electrum servers
  * Privacy
    * Coinjoin
  * Security
    * Multisig (security)
* Bonus Lightning
  * Maintenance
  * Resilience
  * Dashboards & Wallets
    * CLI-only
    * GUI - Desktop
    * GUI - Mobile
* Even more extras

2021-11-28 10:32 UTC, Stadicus commented
Thanks, I'll properly review this later today :+1:

2021-11-28 15:25 UTC, Stadicus requested changes
The overall structure looks great and can scale with many more guides.

Some thoughts on the Bonus subsection pages:
* The naming of the subsections (e.g., "Bonus Raspberry Pi" etc.) feels very redundant in the navigation. I know it's necessary to prevent the same categories as in the core guide. How about changing this to something like `+ Raspberry Pi`, `+ Bitcoin`, etc.?
* The Bonus subpages should contain a title, e.g., "Bonus Section: Raspberry Pi guides"
* Some horizontal rulers between the H2 sections could help visually divide them better
* For filenames, I used `-` to replace spaces. All directory and file names should follow this, e.g. for `./bonus/raspberry-pi/`
 

In general:
* For external links, `{:target="_blank"}` should be added to open it in a new browser tab
* also see some comments directly in the code

You can check out my updated and tested version of your branch here:  
https://stadicus.github.io/raspibolt-dev/bonus/bitcoin/bonus-bitcoin.html

You can see the individual changes in this commit. Technically it would be possible to import that into your own branch (e.g. with `merge` or `cherry-pick`), but it might be easier to do it manually.

https://github.com/Stadicus/raspibolt-dev/commit/e35d09e21d31622d9ff3065586a0ec525b0cdfc7

2021-11-28 15:25 UTC, Stadicus commented on bonus/lightning/remote-lncli.md
> +## Bonus guide: lntop: LNTOP terminal dashboard
The file `lightning/remote-lncli.md` somehow contains the "LNTOP" guide

2021-11-28 15:25 UTC, Stadicus commented on bonus/lightning/auto-unlock.md
> +grand-parent: Bonus Section
should be `grand_parent`, the breadcrumbs don't work like this

2021-11-28 15:25 UTC, Stadicus commented on bonus/bitcoin/bonus-bitcoin.md
> +* *Coinjoin*
I think the "Coinjoin" title could be removed for now, too much structure for just one entry

2021-11-28 15:25 UTC, Stadicus commented on bonus/bitcoin/bonus-bitcoin.md
> +* *Multisig*
I think the "Multisig" title could be removed for now, too much structure for just one entry

2021-11-28 15:25 UTC, Stadicus commented on bonus/lightning/static-backup-dropox.md
>  ---
The filename `bonus/lightning/static-backup-dropox.md` contains a typo

2021-11-29 12:21 UTC, VajraOfIndra commented on bonus/lightning/remote-lncli.md
> +## Bonus guide: lntop: LNTOP terminal dashboard
Oops, that must have been a copy/paste mistake, fixed!

2021-11-29 12:21 UTC, VajraOfIndra commented on bonus/lightning/auto-unlock.md
> +grand-parent: Bonus Section
fixed!

2021-11-29 12:23 UTC, VajraOfIndra commented on bonus/bitcoin/bonus-bitcoin.md
> +* *Coinjoin*
It makes sense. I opted for:

## Privacy (coinjoin)

and

## Security (multisig)

as I thought the Security categorisation of the Specter wallet guide was not obvious without the 'multisg' highlight....

But we could just use ' Privacy' and 'Security' if you prefer shorter/simpler heading, just let me know.

2021-11-29 12:23 UTC, VajraOfIndra commented on bonus/bitcoin/bonus-bitcoin.md
> +* *Multisig*
See above

2021-11-29 12:24 UTC, VajraOfIndra commented on bonus/lightning/static-backup-dropox.md
>  ---
thanks, fixed!

2021-11-29 12:28 UTC, VajraOfIndra commented
> The overall structure looks great and can scale with many more guides.

Great :)

>     * The naming of the subsections (e.g., "Bonus Raspberry Pi" etc.) feels very redundant in the navigation. I know it's necessary to prevent the same categories as in the core guide. How about changing this to something like `+ Raspberry Pi`, `+ Bitcoin`, etc.?

Looks like a good solution indeed, I changed the file names and all paths using this new naming convention. I hope I didn't forget any.

>     * The Bonus subpages should contain a title, e.g., "Bonus Section: Raspberry Pi guides"

Agree, that's nicer! It's been added now.


>     * Some horizontal rulers between the H2 sections could help visually divide them better

Great suggestion, fixed.
 
>     * For filenames, I used `-` to replace spaces. All directory and file names should follow this, e.g. for `./bonus/raspberry-pi/`

Fixed.

>     * For external links, `{:target="_blank"}` should be added to open it in a new browser tab

Makes sense, fixed!
 
>     * also see some comments directly in the code

See below for a reply to each comment.

> You can check out my updated and tested version of your branch here: https://stadicus.github.io/raspibolt-dev/bonus/bitcoin/bonus-bitcoin.html
> 
> You can see the individual changes in this commit. Technically it would be possible to import that into your own branch (e.g. with `merge` or `cherry-pick`), but it might be easier to do it manually.

I didn't have time to setup git and learn how to use it so I opted to replicate all your changes manually. I went through the comments above and in the code and also reviwed your branch with the modifications. I think I got them all but I might have missed a couple, just let me know if you spot any typos or forgotten update.

2021-11-29 12:49 UTC, Stadicus commented on bonus/bitcoin/bonus-bitcoin.md
> +* *Coinjoin*
Sounds good, can always update later

2021-11-29 19:59 UTC, Stadicus requested changes
Great work, all my comments have been addressed.

One thing that can be improved: the main page of each part of the guide (as defined by the directory structure) should be called `index.md`, within the corresponding directory:

* /index.md
* /bonus/index.md
* /bonus/raspberry-pi/index.md

This ensures that links like the following, just specifying the directory, don't lead to a 404 error:

* https://vajraofindra.github.io/RaspiBolt/bonus/
* https://vajraofindra.github.io/RaspiBolt/bonus/bitcoin/

Everything else looks good! :tada:

2021-11-30 13:08 UTC, VajraOfIndra commented
> One thing that can be improved: the main page of each part of the guide (as defined by the directory structure) should be called `index.md`, within the corresponding directory:
[...]
> This ensures that links like the following, just specifying the directory, don't lead to a 404 error:

Awesome, I updated accordingly. I noticed eralier that this was the recommended structure and naming convention in the 'Just the Docs' documentation but I didn't know about the advantage you mentionned above about 404 errors, that's neat.
 
> Everything else looks good! 🎉

Woohoo 🎉 :)

2021-11-30 21:28 UTC, Stadicus approved these changes
LGTM, tACK :)

@VajraOfIndra do you want to do the honors and push the "MERGE" button?

2021-11-30 22:04 UTC, VajraOfIndra commented
> LGTM, tACK :)
> 
> @VajraOfIndra do you want to do the honors and push the "MERGE" button?

With great pleasure! :)

2021-11-30 22:05 UTC, merged