bonus: boot from microsd card
raspibolt/raspibolt pull request #807
Opened 2021-11-30 09:32 UTC by Stadicus

#### What

This change adds a bonus guide on how to boot from a microSD card and mount an external drive to /data/ to use for data storage. This method should work with the broadest range of devices.

### Why

The new RaspiBolt version 3 assumes that all external drives can be used to boot the Raspberry Pi.

This seems to hold true for most modern drives, but if this does not work with a specific drive, the reader is stuck without any fallback instructions.

#### How

The instructions from the v2 guide are simplified, and the external drive mounted to `/data/`. Making the directory itself immutable with `chattr +i` prevents accidental data storage on the microSD card.

_Note:_ this change needs to be rebased after the new Bonus Guide structure is in place.

#### Scope

- [ ] significant change to core configuration
- [x] independent bonus guide
- [ ] simple bug fix

Fixes #806 

#### Test & maintenance

This change can be tested by writing a vanilla RasPiOS image to a microSD card and following the guide with a spare drive to format and mount.

#### Animated GIF (optional)

![old school](https://media.giphy.com/media/bZQvimlS7kuGc/giphy.gif)

2021-12-01 10:28 UTC, VajraOfIndra commented on bonus/raspberry-pi/boot-from-microsd-card.md
> +1. [System configuration](../../system-configuration.md):
```suggestion
2. [System configuration](../../system-configuration.md):
```

Fix typo in numbered list

2021-12-01 10:42 UTC, VajraOfIndra commented on bonus/raspberry-pi/boot-from-microsd-card.md
> +To boot from a microSD card and store the data on an external drive, there are a few additional steps compared to the default RaspiBolt guide:
```suggestion
To boot from a microSD card and store the data on an external drive, there are a few additional steps compared to the default RaspiBolt guide. Below is a summary of the main differences. Detailed guidance is given in the following sections.
```
I added a few more words just to clarify a bit what this section is about vs the following section, as I was a bit confused at first how this section related to the next two sections. My wording is poor so could be reworked and improved for sure, but just wanted to give an example of clarification that I think could be useful.

2021-12-01 10:44 UTC, VajraOfIndra commented on bonus/raspberry-pi/index.md
> +
```suggestion
```

2021-12-01 10:47 UTC, VajraOfIndra commented on operating-system.md
> +This method works for most modern drives, but if it doesn't work in your case, please follow the fallback instructions 'Boot from microSD card instead of external drive](bonus/raspberry-pi/boot-from-
```suggestion
This method works for most modern drives, but if it doesn't work in your case, please follow the fallback instructions [Boot from microSD card instead of external drive](bonus/raspberry-pi/boot-from-microsd-card.md).
```

2021-12-01 10:50 UTC, VajraOfIndra commented on system-configuration.md
> +* Your external disk should be connected as `/dev/sda`.
No change required but just curious and to learn :) Why changing from 'drive' to 'disk'? I thought disk was the outdated term between the two...

2021-12-01 10:52 UTC, VajraOfIndra requested changes
I won't have time to test this guide with a SD card in the coming days/weeks so I just leave an untested review.

It's a really useful addition to the guide and a timely one, awesome to see :)

Just a few typo corrections and suggestions for very minor changes.

2021-12-01 11:44 UTC, Stadicus commented on bonus/raspberry-pi/boot-from-microsd-card.md
> +1. [System configuration](../../system-configuration.md):
Markdown ignores the numbers and will show them consecutively in any case. No need to do the actual numbering:
https://www.markdownguide.org/basic-syntax#ordered-lists

2021-12-01 11:45 UTC, Stadicus commented on bonus/raspberry-pi/boot-from-microsd-card.md
> +To boot from a microSD card and store the data on an external drive, there are a few additional steps compared to the default RaspiBolt guide:
Ack, makes sense.

2021-12-01 11:46 UTC, Stadicus commented on bonus/raspberry-pi/index.md
> +
I usually put a blank line between paragraphs, headers etc. Only simple lists are squashed together. It does not matter for web layout, but I feel it's easier to read the MD file. 

Happy to talk if we want to do this in general, or not.

2021-12-01 11:47 UTC, Stadicus commented on operating-system.md
> +This method works for most modern drives, but if it doesn't work in your case, please follow the fallback instructions 'Boot from microSD card instead of external drive](bonus/raspberry-pi/boot-from-
Good catch

2021-12-01 11:47 UTC, Stadicus commented on system-configuration.md
> +* Your external disk should be connected as `/dev/sda`.
Yep, I changed everything to "external drive", but the command here shows `disk` in the output, so I thought this might be more consistent.

2021-12-01 13:17 UTC, VajraOfIndra commented on bonus/raspberry-pi/boot-from-microsd-card.md
> +1. [System configuration](../../system-configuration.md):
It appears like this to me for now when using 'View file':
![image](https://user-images.githubusercontent.com/86242283/144241086-75040708-4d76-48c5-aca5-13b317f06fc4.png)

Is that normal and the number 2 will appear when published? Otherwise it could be an issue with the asterix items..? not sure

2021-12-01 13:22 UTC, VajraOfIndra commented on bonus/raspberry-pi/index.md
> +
I don't have strong opnions on this at all, I had just assumed it was conventional to not have blank lines between list items.
I'll do the same as you outlined above for now on (i.e. no blank line for short list items, a blank line for list with longer items).

2021-12-01 13:23 UTC, VajraOfIndra commented on system-configuration.md
> +* Your external disk should be connected as `/dev/sda`.
ah ok, makes sense, thanks!

2021-12-02 06:58 UTC, Stadicus commented on bonus/raspberry-pi/boot-from-microsd-card.md
> +1. [System configuration](../../system-configuration.md):
Hm, on the [branch published to github.io](https://stadicus.github.io/raspibolt-dev/bonus/raspberry-pi/boot-from-microsd-card.html#steps-required) it looks as expected. Probably an issue with the MD preview:

![image](https://user-images.githubusercontent.com/19550140/144373259-4a75aac6-abac-47f0-94f2-b31693d5d83a.png)

2021-12-02 07:08 UTC, Stadicus commented
Fixed the requested changes, PTAL

2021-12-02 08:58 UTC, VajraOfIndra commented on bonus/raspberry-pi/boot-from-microsd-card.md
> +1. [System configuration](../../system-configuration.md):
Ah great, good to know if it happens again.

2021-12-02 08:59 UTC, VajraOfIndra commented
> Fixed the requested changes, PTAL

LGTM!

2021-12-02 08:59 UTC, VajraOfIndra approved these changes

2021-12-02 09:21 UTC, merged