Split the 'Additional scripts' bonus guide into three bonus guides: Aliases, lnbalance and lnchannels
raspibolt/raspibolt pull request #841
Opened 2021-12-14 15:29 UTC by VajraOfIndra

#### What

This PR aims at three objectives:

* Split the 'Additional scripts' bonus guide into three separate guides as it contains guides that belong to both the +Raspberry Pi and + Lightning bonus sections
  * aliases.md in the '+Raspberry Pi' section -> Explains how to set up aliases to simplify command entry
  * lnbalance.md in the '+Lightning' section -> Explains how to install the lnbalance script
  * lnchannels.md in the '+Lightning' section -> Explains how to install the lnchannels script
* Updates the content of the guides to match v3 styling and remove outdated references (e.g. testnet)
* Add aliases suggestions by MarcosDub in this [Telegram post](https://t.me/raspibolt/4466)

### Why

This change of structure makes the three sub-guides much more visible and placed in their proper logical sections of the Bonus Section.
Also the guides were outdated and needed some updating both in content and style.
It also allows to add a contribution by MarcosDub re. additional aliases

#### How

Split the 'Additional scripts' guide intro three new bonus guide and deleted the original guide.
Tested on a v3 node (some but not all aliases have been tested)

#### Possible improvements

I placed the aliases.md guide in the 'System administration' heading within '+ Raspberry Pi' section... but I'm not too sure this sub-heading is the best, any better idea what kind of sub-heading to use under which setting up aliases would fall under..?

#### Scope

- [ ] significant change to core configuration
- [x] independent bonus guide
- [ ] simple bug fix

#### Test & maintenance

Test: Follow the three new bonus guides

Maintenance: None

#### Animated GIF (optional)

![chop](https://media.giphy.com/media/e6fx0NANL8520GGGdy/giphy-downsized.gif)

2022-01-14 07:24 UTC, Stadicus requested changes
Nice structure, I like how this makes these useful scripts more visible! :+1: 

I added comments for some minor changes to ensure consistency and scripting best practices.

2022-01-14 07:24 UTC, Stadicus commented on bonus/lightning/script-lnbalance.md
> +The following script was created by [RobClark56](https://github.com/robclark56){:target="_blank"} and help getting a better system overview.
maybe "helps to get a"

2022-01-14 07:24 UTC, Stadicus commented on bonus/lightning/script-lnbalance.md
> +  $ less balance
should be `less lnbalance`

2022-01-14 07:24 UTC, Stadicus commented on bonus/lightning/script-lnbalance.md
> +  > spiBolt channel balance display, by robclark56
this output seems to miss some characters, should be

```
#!/bin/bash
# RaspiBolt channel balance display, by robclark56
```

2022-01-14 07:24 UTC, Stadicus commented on bonus/lightning/script-lnbalance.md
> +  $ rm lnbalance
Instead of copying/deleting, we could just move the script:

```
sudo mv lnbalance /usr/local/bin
```

2022-01-14 07:24 UTC, Stadicus commented on bonus/lightning/script-lnbalance.md
> +  $ cd
This could just be a single command:

```
sudo rm /usr/local/bin/lnbalance
```

2022-01-14 07:24 UTC, Stadicus commented on bonus/lightning/script-lnchannels.md
> +  $ cd
See former comment about moving the script instead of copy/delete

2022-01-14 07:24 UTC, Stadicus commented on bonus/lightning/script-lnchannels.md
> +  $ cd
See former comment about using a single `rm` command

2022-01-14 07:24 UTC, Stadicus commented on bonus/raspberry-pi/aliases.md
> +  $ source /home/admin/.bashrc
We should source "bash_aliases" directly here, and use the shortcut for the user's home directory `~`, then the commands are universal for every user:

```
source ~/.bash_aliases
```

2022-01-14 07:24 UTC, Stadicus commented on bonus/raspberry-pi/aliases.md
> +
Maybe delete the first blank line?

2022-01-14 07:24 UTC, Stadicus commented on bonus/raspberry-pi/aliases.md
> +
This command does not provide the versions for Electrs and RTL. A quick fix, with some linebreaks for better readability, would be this:

```
alias showversion='echo The installed versions of the services are as follows: ; \
    bitcoind --version ; \
    lnd --version ; \
    echo "BTC RPC Explorer: $(head -n 3 /home/btcrpcexplorer/btc-rpc-explorer/package.json)" ; \
    echo "Electrs: version $(head -n 1 /home/admin/rust/electrs/RELEASE-NOTES.md)" ;
    tor --version ; \
    echo "RTL: $(head -n 3 /home/rtl/RTL/package.json)" ; \
    echo NPM: v`npm --version` ; \
    echo NodeJS: node -v ; \
    lntop --version ; \
    htop --version ; nginx -v'
```

2022-01-14 07:24 UTC, Stadicus commented on bonus/raspberry-pi/aliases.md
> +  $ rm .bash_aliases
This should be 

```
$ rm ~/.bash_aliases
```

2022-01-14 07:24 UTC, Stadicus commented on bonus/raspberry-pi/aliases.md
> +  $ source /home/admin/.bashrc
You can't "remove" the aliases, unless you overwrite them with a blank command. Sourcing the ".bashrc" does nothing useful here. The aliases will stay in memory.

I'd just comment that the aliases will be gone with the next login.

2022-01-14 07:24 UTC, Stadicus commented on bonus/raspberry-pi/aliases.md
> +  $ sudo nano ~/.bash_aliases
No `sudo` necessary if you're editing the file in your own home directory

2022-01-21 09:40 UTC, VajraOfIndra commented on bonus/lightning/script-lnbalance.md
> +The following script was created by [RobClark56](https://github.com/robclark56){:target="_blank"} and help getting a better system overview.
Fixed

2022-01-21 09:40 UTC, VajraOfIndra commented on bonus/lightning/script-lnbalance.md
> +  $ less balance
Well spotted, fixed!

2022-01-21 09:40 UTC, VajraOfIndra commented on bonus/lightning/script-lnbalance.md
> +  > spiBolt channel balance display, by robclark56
fixed

2022-01-21 09:54 UTC, VajraOfIndra commented on bonus/lightning/script-lnbalance.md
> +  $ rm lnbalance
My rationales at the time was that this 2-steps approach prevented the deletion of root folders by mistake (like by adding a space by mistake after /usr, for example). But it's probably being ovecuatious and complicate the guide by adding more commands so better going for the simplest option. Fixed.

2022-01-21 09:54 UTC, VajraOfIndra commented on bonus/lightning/script-lnbalance.md
> +  $ cd
fixed

2022-01-21 09:54 UTC, VajraOfIndra commented on bonus/lightning/script-lnchannels.md
> +  $ cd
fixed

2022-01-21 09:54 UTC, VajraOfIndra commented on bonus/lightning/script-lnchannels.md
> +  $ cd
fixed

2022-01-21 09:55 UTC, VajraOfIndra commented on bonus/raspberry-pi/aliases.md
> +  $ source /home/admin/.bashrc
Interesting! I changed accordingly.

2022-01-21 09:55 UTC, VajraOfIndra commented on bonus/raspberry-pi/aliases.md
> +
Ok, fixed.

2022-01-21 09:57 UTC, VajraOfIndra commented on bonus/raspberry-pi/aliases.md
> +
Excellent, I changd it accordingly. I also added a linebreak for the command below for better readability.

2022-01-21 09:57 UTC, VajraOfIndra commented on bonus/raspberry-pi/aliases.md
> +  $ rm .bash_aliases
Same as above. Fixed now.

2022-01-21 09:59 UTC, VajraOfIndra commented on bonus/raspberry-pi/aliases.md
> +  $ source /home/admin/.bashrc
Ok, I didn't know that, that;s good to know. I removed the source command and modified the commentary line above.

2022-01-21 10:00 UTC, VajraOfIndra commented on bonus/raspberry-pi/aliases.md
> +  $ sudo nano ~/.bash_aliases
Good point! fixed

2022-01-21 10:01 UTC, VajraOfIndra commented
> I added comments for some minor changes to ensure consistency and scripting best practices.

Excellent suggestions, I implemented all of them, PTAL!

2022-02-06 11:00 UTC, Stadicus approved these changes
One small nit, otherwise LGTM!

2022-02-06 11:03 UTC, Stadicus commented
Now, that we just removed `jq` from the general packages install... it would come in handy here. :rofl: 

The `showversion` alias could be improved like this:

```sh
alias showversion='echo The installed versions of the services are as follows: ; \
    bitcoind --version ; \
    lnd --version ; \
    echo "BTC RPC Explorer: $(jq '.version' < /home/btcrpcexplorer/btc-rpc-explorer/package.json)" ; \
    echo "Electrs: version $(head -n 1 /home/admin/rust/electrs/RELEASE-NOTES.md)" ;
    tor --version ; \
    echo "RTL: $(jq '.version' < /home/rtl/RTL/package.json)" ; \
    echo NPM: v`npm --version` ; \
    echo NodeJS: node -v ; \
    lntop --version ; \
    htop --version ; nginx -v'
```

Before: 
![image](https://user-images.githubusercontent.com/19550140/152677783-91017fb5-affa-4b41-a6c0-d704d24e57f7.png)

After:
![image](https://user-images.githubusercontent.com/19550140/152677790-9e9f3b00-8643-4738-9a7f-ba431a8660a1.png)

But that's just optics, maybe also for a future revision. The command works as intended.

2022-02-06 12:08 UTC, VajraOfIndra commented
> Now, that we just removed `jq` from the general packages install... it would come in handy here. rofl

It's used by quite a few bonus guides indeed. ..Would you prefer if we put it back in the main guide? or that we add an install line in each bonus guide that uses it? 

> The `showversion` alias could be improved like this:
> But that's just optics, maybe also for a future revision. The command works as intended.

Much better, I amended accordingly! PTAL

2022-02-06 13:32 UTC, VajraOfIndra commented
Apparently, there are conflicts that prevent to merge the PR... but I couldn't pinpoint them. So I created a new branch and PR with the exact same version of the files (inlcuding the latest changes I made following your last comments). This new PR #903 seems to not have conflicts so we shoudl be able to merge it without issues once you approve it. 

Not sure it's the cleanest way to deal with this but I didn't know how to solve the conflicts here.. so I went for a workaround..! :)

2022-02-06 19:08 UTC, RooSoft commented
> Apparently, there are conflicts that prevent to merge the PR... but I couldn't pinpoint them. So I created a new branch and PR with the exact same version of the files (inlcuding the latest changes I made following your last comments). This new PR #903 seems to not have conflicts so we shoudl be able to merge it without issues once you approve it.
> 
> Not sure it's the cleanest way to deal with this but I didn't know how to solve the conflicts here.. so I went for a workaround..! :)

#903 looks ready to go.. should we close this one once #903 is merged?

2022-02-07 09:07 UTC, VajraOfIndra commented
> > Apparently, there are conflicts that prevent to merge the PR... but I couldn't pinpoint them. So I created a new branch and PR with the exact same version of the files (inlcuding the latest changes I made following your last comments). This new PR #903 seems to not have conflicts so we shoudl be able to merge it without issues once you approve it.
> > Not sure it's the cleanest way to deal with this but I didn't know how to solve the conflicts here.. so I went for a workaround..! :)
> 
> #903 looks ready to go.. should we close this one once #903 is merged?

Yes, let's close it now!

2022-02-07 09:07 UTC, closed without merging