Update bitcoin-core.md: include warning and sudo when tailing debug.log
raspibolt/raspibolt pull request #866
Opened 2021-12-31 05:27 UTC by orenfromberg

#### What

Adding an expected warning as well as prepending a command to use sudo.

This PR fixes #864 and succeeds #865 based on [this comment](https://github.com/raspibolt/raspibolt/issues/864#issuecomment-1003272244) by @c-mannix 

### Why

This change will prevent future confusion by users inspecting the bitcoind service and tailing the debug.log file.

#### How

* Now including the warning in the output
* Explicitly directing use of `sudo` with tail command
* 
#### Scope

- [ ] significant change to core configuration
- [ ] independent bonus guide
- [x] simple bug fix

Fixes #864 

#### Test & maintenance

Test the command by running `tail -f /home/bitcoin/.bitcoin/debug.log` successfully.

#### Animated GIF (optional)

![](https://media.giphy.com/media/DJj4Bag0l7E3ZAcHHp/giphy.gif)

2021-12-31 12:20 UTC, VajraOfIndra requested changes
Thanks for following-up on this, it'd be useful to sort it out.

For the first change: LGTM. We could either make this change (adding the warning output) or else we could run the command with `sudo` and add the log outputs, WDYT?

The second change is not necessary I believe. The Bitcoin `debug.log` is owned by the "bitcoin" user and the user invoking the `tail` command is "admin" which is a member of the "bitcoin" group and therefore has read privilege. On my node, the `tail` command (without `sudo`) works fine.

Nice gif! :)

2021-12-31 14:42 UTC, c-mannix commented
> For the first change: LGTM. We could either make this change (adding the warning output) or else we could run the command with `sudo` and add the log outputs, WDYT?
> 

 Personally I don't like see warnings at all so perhaps we could show the command `systemctl status bitcoind.service` with `sudo`, if we leave the warning it might be good to also explain that  using `sudo` will remove the warning.

> The second change is not necessary I believe. The Bitcoin `debug.log` is owned by the "bitcoin" user and the user invoking the `tail` command is "admin" which is a member of the "bitcoin" group and therefore has read privilege. On my node, the `tail` command (without `sudo`) works fine.

 Having recently gone through the guide myself I ran into the same permission issue. Even though `admin` is part of the `bitcoin` group, invoking `tail -f /home/bitcoin/.bitcoin/debug.log` on my node without `sudo`  results in:
 
```
admin@raspibolt:~ $ tail -f /home/bitcoin/.bitcoin/debug.log
tail: cannot open '/home/bitcoin/.bitcoin/debug.log' for reading: Permission denied
tail: no files remaining
```

2021-12-31 17:26 UTC, VajraOfIndra commented
> Personally, I don't like seeing warnings at all so perhaps we could show the command systemctl status bitcoind.service with sudo, if we decide to leave the warning and not use sudo it might be good to also explain that using sudo will remove the warning.

Adding sudo sounds good to me (we'll need to add the few lines of output corresponding), @Stadicus WDYT?

> Having recently gone through the guide myself I ran into the same permission issue.

Ok, that's weird, I wonder where is the issue coming from.. 

Could you paste the output of the following 2 commands (from user "admin"):
1. `ls -la /home/bitcoin/.bitcoin/debug.log`
1. `grep bitcoin /etc/group`

2021-12-31 17:32 UTC, c-mannix commented
> Could you paste the output of the following 2 commands (from user "admin"):

>1. ls -la /home/bitcoin/.bitcoin/debug.log
```
admin@raspibolt:~ $ ls -la /home/bitcoin/.bitcoin/debug.log
-rw------- 1 bitcoin bitcoin 10292952 Dec 31 17:22 /home/bitcoin/.bitcoin/debug.log
```

> 2. grep bitcoin /etc/group
```
admin@raspibolt:~ $ grep bitcoin /etc/group
bitcoin:x:1002:admin,electrs,btcrpcexplorer
debian-tor:x:114:bitcoin
```

2022-01-01 10:56 UTC, VajraOfIndra commented
> bitcoin:x:1002:admin,electrs,btcrpcexplorer

So your "admin" user is indeed a member of "bitcoin", so that's good.

> -rw------- 1 bitcoin bitcoin 10292952 Dec 31 17:22 /home/bitcoin/.bitcoin/debug.log

But for whatever reason, your `debug.log` can only be read/write by the bitcoin user and there is no permissions at all for any member of the bitcoin group. In comparison, here is how my file looks:
`-rw-r--r-- 1 bitcoin bitcoin 2715693 Jan  1 10:46 /home/bitcoin/.bitcoin/debug.log`  

As you can see, on my node, the file can also be read by the "bitcoin" group and also by any other users.

I'm not sure what we've done differently though... maybe someone else will be able to find out.

2022-01-03 21:55 UTC, c-mannix commented
Yeah, not sure. I followed the guide twice and came up with the same result.

2022-01-04 19:46 UTC, RooSoft reviewed
I'd rather work to change the file's permission to allow read access to the bitcoin group... or try to access it with the bitcoin user, rather than using root to do this task.

2022-01-04 19:51 UTC, orenfromberg commented
Does anyone have an idea if this is related to [this recent change](https://github.com/raspibolt/raspibolt/commit/b845122d6e98b958d5aa6893fcef67599cdd0d57#diff-fce54494da861cdd676def495ef166aa3d6309ad930fe58975dd83ecb3aadf01R281) that replaces `Group=bitcoin` with `UMask=0027`?

2022-01-04 20:07 UTC, VajraOfIndra commented
Could it be that the latest version(s) of Bitcoin Core set up user-only permissions on this file? If so, that could explain the discrepency between newly created nodes (user-only permissions) vs older v2 nodes migrated to v3 (not sure if @Stadicus re-used its node's bitcoind data when writing v3..).

I can't weight on which is the best solutions though... (using `sudo` _vs_ changing the permissions for this file)

2022-01-11 19:51 UTC, Stadicus commented
> Does anyone have an idea if this is related to this recent change that replaces Group=bitcoin with UMask=0027?

Very interesting. I think that's a side effect of the recent change https://github.com/raspibolt/raspibolt/pull/846

Before:
* we used Bitcoin Core argument `sysperms` to set UMask `0027` (read-permissions for group) on newly created files, primarily the authentication cookie
* but this only works with the Bitcoin Core wallet disabled

After:
* to enable the Bitcoin Core wallet (for EPS, JoinMarket etc), this argument was removed. Bitcoin Core now creates new files with access rights for the user only. I did not think about the log file here.
* to make the authentication cookie group-accessible, we now execute a "chmod" command using `startupnotify` in the systemd unit.

Setting the logfile permissions once should be enough:

```sh
$ sudo chmod g+r /data/bitcoin/debug.log
```

That should be added to the guide after Bitcoin Core is started the first time, for example around here:
https://github.com/raspibolt/raspibolt/blob/32bdcbe4bd37116836ca31996de31fbc6afb4e4c/bitcoin-core.md?plain=1#L222

2022-01-11 19:54 UTC, Stadicus commented
> Adding sudo sounds good to me (we'll need to add the few lines of output corresponding), @Stadicus WDYT?

Sounds good!

2022-01-11 20:14 UTC, RooSoft approved these changes

2022-02-03 20:41 UTC, VajraOfIndra requested changes
Coming back to this pull request as I'm creating a new node, so very appropriate :)

The sudo are not needed I think.

Also, despite the changes, the systemctl status still shows the `Warning: some journal files were not opened due to insufficient permissions.` error message that I believe we wanted to get rid of or warn about: I suggest simply adding sudo in front of the `systemctl status bitcoind` command, wdyt?

2022-02-03 20:41 UTC, VajraOfIndra commented on bitcoin-core.md
> +  $ sudo chmod g+r /data/bitcoin/debug.log
```suggestion
  $ chmod g+r /data/bitcoin/debug.log
```
Since the command is invoked with the "bitcoin" user, we don't need to use `sudo` (not even sure we can). Simply using `chmod` should work there.

2022-02-03 20:41 UTC, VajraOfIndra commented on bitcoin-core.md
> +  $ sudo tail -f /home/bitcoin/.bitcoin/debug.log
```suggestion
  $ tail -f /home/bitcoin/.bitcoin/debug.log
```
Since debug.log is now readable by admin, `sudo` is not needed anymore. I tested it on my new node.

2022-02-03 20:50 UTC, VajraOfIndra commented
@orenfromberg Last change needed before we can merge is adding sudo to the `systemctl status bitcoind` command (the first command in the "Verification of bitcoind operations" sub-section) to get rid of the error message due to a lack of permissions (at least it still needed on my new node despite changing the permissions of the debug.log, so I assume  there are other log files)

2022-02-03 20:55 UTC, orenfromberg commented
@VajraOfIndra I'll defer to you since you are actually running the steps. :smile:

2022-02-04 13:52 UTC, VajraOfIndra approved these changes

2022-02-04 13:54 UTC, VajraOfIndra commented
> @VajraOfIndra I'll defer to you since you are actually running the steps. smile

tACK, LGTM! 
Let's merge it :)

2022-02-04 13:54 UTC, merged