Update rtl.md
raspibolt/raspibolt pull request #869
Opened 2022-01-02 09:42 UTC by shafan

Fix  "Add the NodeJS software repository"

#### What

What is the reason of this change?

### Why

Why is this change important?

#### How

How was this change accomplished?

#### Scope

- [ ] significant change to core configuration
- [ ] independent bonus guide
- [ ] simple bug fix

Fixes # (link issue)

#### Test & maintenance

How can the changes be tested? Is there ongoing maintenance effort? If this is a bonus guide: are you willing to update it from time to time?

#### Animated GIF (optional)

Add some snazz if you feel like it :)

2022-01-11 20:20 UTC, Stadicus approved these changes

2022-01-27 09:53 UTC, VajraOfIndra commented
We are using the command as the "root" user in the guide, so I don't think there is a need to add "sudo", correct?

Logging in as the "root" user is suggested in the comment above the command but not explicitly indicated with the command `sudo su -`... To avoid missing it out, maybe we shoud add this command?

2022-01-27 09:53 UTC, VajraOfIndra requested changes
We are using the command as the "root" user in the guide, so I don't think there is a need to add "sudo", correct?

Logging in as the "root" user is suggested in the comment above the command but not explicitly indicated with the command `sudo su -`... To avoid missing it out, maybe we shoud add this command?

2022-01-27 10:00 UTC, shafan commented
If I'm not mistaken, all commands are always with sudo and not as root.
By the way, the command just after to install nodejs is also with sudo :
$ sudo apt-get install nodejs
In my opinion, it is rather the comment that should be changed, no?

2022-01-27 10:10 UTC, VajraOfIndra commented
> If I'm not mistaken, all commands are always with sudo and not as root. By the way, the command just after to install nodejs is also with sudo : $ sudo apt-get install nodejs In my opinion, it is rather the comment that should be changed, no?

I'm not sure why using "root" was choosen in the first place... there could be a good reason but I don't know what it would be!

If we could stay with "admin" and use `sudo`, I agree that it would be a better option as it's simpler.

@Stadicus : any reason to use "root" rather than "admin" to add he Node.js pasckage repo?

2022-01-27 14:38 UTC, RooSoft commented
I agree with @VajraOfIndra about running task using the `admin` and `sudo`.

2022-01-27 15:34 UTC, shafan commented
Yes I agree with that.At first reading I agree with you.
The two times where NodeJS installations appear is for "Blockchain Explorer" and "Ride The Lightning". These are two optional elements.
But what I like about this tutorial is that it's very easy to read and you can follow the steps without having to switch from one place to another.
For only two times, I'm finally of the opinion to leave it as it is.

2022-01-27 16:02 UTC, Stadicus commented
I think mentioning user "root" is a relict from the past, it should never be used (only use `sudo` for this). The user is mentioned, but not reflected by the commands.

I'd change

> Starting with user “admin”, we switch to user “root” and add the Node JS package repository

to 

> > Starting with user “admin”, we add the Node JS package repository

My bad, sorry for the confusion

2022-01-27 17:25 UTC, VajraOfIndra requested changes

2022-01-27 17:25 UTC, VajraOfIndra commented on rtl.md
> +  $ curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -E -
Shouldn't it be `sudo -E bash -` rather than `sudo bash -E -` ? (see Node.js [instructions](https://github.com/nodesource/distributions/blob/master/README.md#installation-instructions))

2022-01-27 20:12 UTC, shafan commented on rtl.md
> +  $ curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -E -
It is the same but I can change to be more faithful to the nodejs doc

2022-01-27 20:58 UTC, RooSoft commented on rtl.md
> +  $ curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -E -
Unfortunately it's not... in the first version, -E is applied to the `sudo` command whereas in the second would be a `bash` argument that apparently doesn't exist.

2022-01-27 21:16 UTC, shafan commented on rtl.md
> +  $ curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -E -
Oops sorry you are right

2022-01-28 07:51 UTC, VajraOfIndra commented on rtl.md
> +  $ curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -E -
LGTM!

2022-01-28 07:51 UTC, VajraOfIndra approved these changes

2022-01-28 07:52 UTC, VajraOfIndra commented
LGTM, let's merge it.
Thanks @shafan for the contribution!

2022-01-28 07:53 UTC, merged