System overview with RTL
raspibolt/raspibolt pull request #883
Opened 2022-01-18 14:26 UTC by AsyncLuck

#### What
Add RTL status in system overview

### Why

RTL is standard part in raspibolt v3

#### How

Change the original system overview script
Someone needs to adapt the render output section. I don't know how to do it properly.
For the moment, you only have a new line at the end but without version color etc :(

#### Scope

- [ ] significant change to core configuration
- [ X] independent bonus guide
- [ ] simple bug fix

Fixes # (link issue)

2022-01-21 11:11 UTC, VajraOfIndra requested changes
All good except for a small change in a comment.

I also propose a solution below on how to display the RTL data.

---

We can't see the RTL progression in the progress bar, but I assume it's because it's very quick. Out of curiosity, why did you choose 81? I didn't figure out how the progress bar works yet :)

2022-01-21 11:11 UTC, VajraOfIndra commented on resources/20-raspibolt-welcome
> +"${rtlversion}" \
```suggestion
```

See in comments for a way to integrate the RTL data in the final display

2022-01-26 07:50 UTC, AsyncLuck commented on resources/20-raspibolt-welcome
>    # Electrs and RPC Explorer dont have a latest release, just tags
Done

2022-01-26 07:51 UTC, AsyncLuck commented on resources/20-raspibolt-welcome
>    # Electrs and RPC Explorer dont have a latest release, just tags
For the moment, I let the "tag method"

2022-01-26 07:51 UTC, AsyncLuck commented on resources/20-raspibolt-welcome
> +"${rtlversion}" \
Done

2022-01-26 07:57 UTC, AsyncLuck commented
@VajraOfIndra you spotted me, for the progressbar I choose 81 based on the last step incremment that is quick too => pure random choice.

Thx a lot for the render output method. It works well on my node too. (Last commit contains the modification)

2022-02-05 12:02 UTC, VajraOfIndra commented
> @VajraOfIndra you spotted me, for the progressbar I choose 81 based on the last step incremment that is quick too => pure random choice.
> 
> Thx a lot for the render output method. It works well on my node too. (Last commit contains the modification)

No worries! I think we need @Stadicus input for this.. @Stadicus, could you review the last changes? There are 2 small issues we might want to fix before merging:
* is the progress bar setting for RTL ok? it seems to appear too long on my node
* For the new RTL line in the display, it works well if RTL is up. But if it's uninstalled, or down, there is a big red line that follows "down" and continues to the next line. Not sure what causes this big red line though..

2022-02-06 10:43 UTC, Stadicus requested changes
Tested, and the script works as expected (with the issues laid out by @VajraOfIndra).

2022-02-06 10:43 UTC, Stadicus commented on resources/20-raspibolt-welcome
> +printf "%0.s#" {1..81}
The overall width of the welcome screen is 78 characters. This command prints 81 characters, causing the progress bar to be three characters too wide:

![image](https://user-images.githubusercontent.com/19550140/152676744-9e677a7f-70d2-4ca4-9763-f0983d0d77ed.png)

For here, we can just use a lower value (and maybe reduce the values of other sections accordingly). In the long run, we could increase the width of the welcome screen to 80 characters.


The lenght of the progress bar must not exceed `..79`

2022-02-06 10:43 UTC, Stadicus commented on resources/20-raspibolt-welcome
> +  rtl_color="${color_red}\e[7m"
FYI: the ANSI escape code `\e[7m` means "invert colors" (here, it's black text on red background). 
https://wiki.tcl-lang.org/page/Colors+in+Unix+Shells

2022-02-06 10:43 UTC, Stadicus commented on resources/20-raspibolt-welcome
> +                                                 ${rtlversion_color}%-24s
This line should start with `${color_red}` as well, to make sure colors are not inverted (see comment about `\e[7m` above). 

It could be any color, as it's not really used to print anything, it just needs to cancel potential inverted colors, but I'd keep the red for consistency.

2022-02-06 10:43 UTC, Stadicus commented on resources/20-raspibolt-welcome
> +
Extra blank line is not needed

2022-02-07 10:55 UTC, AsyncLuck commented on resources/20-raspibolt-welcome
> +                                                 ${rtlversion_color}%-24s
Thx, done (color red at the begining fo last line)

2022-02-07 10:56 UTC, AsyncLuck commented on resources/20-raspibolt-welcome
> +  rtl_color="${color_red}\e[7m"
Thx for info

2022-02-07 10:57 UTC, AsyncLuck commented on resources/20-raspibolt-welcome
> +printf "%0.s#" {1..81}
I changed the number for the last quick steps and put 78 for RTL (that was the old max value)

2022-02-07 10:58 UTC, AsyncLuck commented
Last commit contains correction from @Stadicus, hope I don't forget anything. (Seems to work on my node for the red color when RTL is down)

2022-02-09 14:22 UTC, VajraOfIndra commented
tACK
LGTM, I can confirm the red line has disappeared and the loading bar is ok.

2022-02-28 12:07 UTC, VajraOfIndra commented
> Tested, and the script works as expected (with the issues laid out by @VajraOfIndra).

@Stadicus I believe the requested changes have been made. Could you PTAL and approve the PR?

2022-03-02 11:14 UTC, VajraOfIndra commented
Thanks a lot for your contribution @AsyncLuck!  We're going to master :) :tada:

2022-03-02 11:15 UTC, merged

2022-03-02 16:22 UTC, AsyncLuck commented
@Stadicus & @VajraOfIndra happy to help a little and happy to be merged.