Update 64bit raspiOS link to official page
raspibolt/raspibolt pull request #899
Opened 2022-02-04 13:56 UTC by asvdf

#### What

As per title

### Why

Because Stadicus and Indra asked for it in the telegram group, obviously. Also, it is extremely important because it's my first PR.

#### How

With extreme skill.

#### Scope

- [ ] significant change to core configuration
- [ ] independent bonus guide
- [ ] simple bug fix
- [ x] updated link

#### Test & maintenance

Just click the link, you'll see.

#### Animated GIF (optional)

feelsgoodman.gif

2022-02-04 14:07 UTC, asvdf commented
Oh, that one, I've never used the imager before but I'll try updating the PR for it.
Just don't expect me to squash the commits as I'm doing everything from the webUI 😄

2022-02-04 14:14 UTC, asvdf commented
...done

2022-02-04 14:26 UTC, Stadicus requested changes
If you want to keep the bullet point, the following lines (that should also be part of that bullet paragraph) need to be indented with two spaces as well. 

As of now, the bullet is not shown. Which is ok, I think, but then we should remove it completely.

![image](https://user-images.githubusercontent.com/19550140/152545292-925f8116-0c04-4923-8cc2-79a0a5ca350f.png)

Also, I'd rather use double-quotes " instead of `code` formatting (which is commonly used for stuff you need to type).

2022-02-04 14:28 UTC, Stadicus commented
Another thing that might be worthwhile to update: instead of using the keyboard shortcut `Ctrl`+`Shift`+`X`, the Image now has a simple button (the "cogwheel") for this:

![image](https://user-images.githubusercontent.com/19550140/152545918-1cfb4869-87f5-4b4f-bcdb-5da6fb7d148b.png)

2022-02-04 14:42 UTC, asvdf commented
...and done

2022-02-04 14:56 UTC, VajraOfIndra commented
There is a minor conflict with the instructions below. I think, we could simply add the bullet points there actually:
![image](https://user-images.githubusercontent.com/86242283/152548983-feb9eb6a-56f3-452e-b62a-ef609af408e9.png)

* Instead of 'select "Use custom"' and 'Select the downloaded RasPi OS disk image' we could simply repalce it with 'select "Raspberry Pi OS (Other)" and then "Raspberry Pi OS Lite (64-bit)"' )

And then in the '# Get Raspeberry Pi OS' section above, we could simply the sentence starting with "Unfortunately,..." and the first bullet point "Download the latest..."

Wdyt?

2022-02-04 15:04 UTC, VajraOfIndra requested changes

2022-02-04 15:04 UTC, VajraOfIndra commented on operating-system.md
> +![image](https://user-images.githubusercontent.com/19550140/152545918-1cfb4869-87f5-4b4f-bcdb-5da6fb7d148b.png)
The image could be uploaded in "Images" directory in the root folder of the repo and then this URL can be used in the link.

Nitpicking here.., but at this stage the OS is likely not yet selected, so maybe the screenshot should be one with no OS selected yet.

2022-02-04 15:13 UTC, Stadicus commented on operating-system.md
> +![image](https://user-images.githubusercontent.com/19550140/152545918-1cfb4869-87f5-4b4f-bcdb-5da6fb7d148b.png)
We definitely must not use the image hosted on GitHub, but upload and reference it ourselves.

2022-02-04 15:15 UTC, Stadicus commented
BTW: I feel we're pinning @asvdf down with all our additional change requests. 

I think it's fine if you just do the simple change first, and someone else can then add all other things afterwards. We don't want to scare you away... :-P

2022-02-04 23:59 UTC, Stadicus approved these changes
tACK, let's go to master! :)

2022-02-05 11:55 UTC, VajraOfIndra approved these changes

2022-02-05 15:18 UTC, merged