Bitcoin & LND data migration: added -og flag to rsync command + LND chown command
raspibolt/raspibolt pull request #935
Opened 2022-02-22 10:17 UTC by VajraOfIndra

#### What

See discussion in #933. The PR adds presently missing guidelines concerning the ownership of the Bitcoin and LND data folders when migrating from v2 to v3.

### Why

To improve the change of users successfully migrating their data to a new node

#### Scope

- [ ] significant change to core configuration
- [ ] independent bonus guide
- [x] simple bug fix

Fixes #933 

![copy](https://media.giphy.com/media/YAy9NNu16pYYg/giphy.gif)

2022-02-22 19:43 UTC, visskiss approved these changes
Looks good.

2022-02-22 19:43 UTC, visskiss approved these changes

2022-02-23 17:46 UTC, Stadicus requested changes
One small comment, otherwise LGTM

2022-02-23 17:46 UTC, Stadicus commented on faq.md
> +  $ sudo chown -r lnd:lnd /data/lnd
I think the recursive attribute must be uppercase: `chown -R`

```sh
$ chown --help
  -R, --recursive        operate on files and directories recursively
```

2022-02-23 18:29 UTC, RooSoft requested changes
Aside from the `chown -r` which should be `chown -R`, it's all good to me

2022-02-23 18:29 UTC, RooSoft commented on faq.md
> +  $ sudo rsync -rhvPog --append-verify /mnt/ext/lnd /mnt/thumbdrive/
Wondered what those new switches were about, so I'll paste them here

-o, --owner                 preserve owner (super-user only)
-g, --group                 preserve group

Seems to make a lot of sense...

2022-02-23 23:25 UTC, VajraOfIndra commented on faq.md
> +  $ sudo chown -r lnd:lnd /data/lnd
Fixed, PTAL

2022-02-23 23:25 UTC, VajraOfIndra commented on faq.md
> +  $ sudo rsync -rhvPog --append-verify /mnt/ext/lnd /mnt/thumbdrive/
Fixed, PTAL

2022-02-24 00:04 UTC, RooSoft approved these changes
This is the way

2022-02-24 08:00 UTC, Stadicus approved these changes
LGTM

2022-02-24 08:27 UTC, merged