Create ups-nut.md
raspibolt/raspibolt pull request #937
Opened 2022-02-23 14:05 UTC by cryptotar

Initial draft of UPS NUT bonus guide for RPi section

#### What

To safely shutdown the node versus a sudden shutdown that can damage it

### Why

No-one wants to rebuild their node

#### How

Trial/error and duckduckgo

2022-03-24 22:01 UTC, mktech-gh requested changes
The review only refers to the variant MODE=standalone

I implemented this variant on my rasbibolt.

It's up and running. Thank you for your effort.

I don't want to implement the variant MODE=netserver on the RaspiBolt. Any additional service or additional external access weakens security.

Next I will test the variant MODE=netclient on the RaspiBolt. I will try to access a server/master installed on a Synology NAS.

2022-03-25 01:01 UTC, cryptotar commented on bonus/raspberry-pi/ups-nut.md
> +
I didn't experience any issues like that, but I also have a common UPS that appears to be the most common driver. I don't see an issue with putting in a warning for others though if all agree.

2022-03-25 08:28 UTC, mktech-gh commented on bonus/raspberry-pi/ups-nut.md
> +
OK. 
Do I need to delete my comment so you can continue? Sorry I'm a newbie.

2022-03-25 12:27 UTC, cryptotar reviewed
Initial changes after peer review.

2022-03-29 20:55 UTC, mktech-gh approved these changes
I set up/checked the variant MODE=netclient. The UPS master/server resides on a Synology NAS.
Everything OK. Well done.

I noticed that in the first part of the bonus guide, the commands are written between aprostrophs. In the second part no aprostrophs are used. That's not so nice.

2022-04-16 14:17 UTC, VajraOfIndra requested changes
I tested the single device part of the guide, it works great. I really enjoyed the explanations of what each commands does, excellent work.

Just a couple of minor things we should probably address before we can merge it, see reviews below.

2022-04-16 14:17 UTC, VajraOfIndra commented on bonus/raspberry-pi/ups-nut.md
> +
I ran into the same issue. I had to comment out `maxretry` to make it work. I didn't know about this comment so didn't know I could have placed the UPS lines _after_ maxretry.

I had to use an uncommon driver (`blazer_usb`)

Could you maybe add a line to warn about the bug and how to fix it?

2022-04-16 14:17 UTC, VajraOfIndra commented on bonus/raspberry-pi/ups-nut.md
> +Unplug the UPS from the wall and you should get an alert that the system is now running on battery power. If you plug it back in, you should get notified that it’s back “on line power”.
Where should the alert appear? I was not sure where I should look for one...

2022-04-20 23:48 UTC, cryptotar commented on bonus/raspberry-pi/ups-nut.md
> +Unplug the UPS from the wall and you should get an alert that the system is now running on battery power. If you plug it back in, you should get notified that it’s back “on line power”.
Good point. I'll specify that it'll be in the console or terminal and assumes you're logged in.

2022-04-20 23:52 UTC, cryptotar reviewed
All changes reviewed and 'approved.' Only area of concern I can see is the Difficulty is currently "Easy'ish" as I wasn't sure whether or not to consider it Moderate. I think it's pretty straight forward, but I guess it depends on the typical user/audience we're presenting to.

2022-04-21 09:11 UTC, VajraOfIndra commented on bonus/raspberry-pi/ups-nut.md
> +Unplug the UPS from the wall and you should get an alert that the system is now running on battery power. If you plug it back in, you should get notified that it’s back “on line power”.
Hum, ok, so maybe I didn't get that part working because I didn't see any messages appear in my terminal when I unplugged my UPS.

2022-04-21 09:17 UTC, VajraOfIndra commented
> All changes reviewed and 'approved.' Only area of concern I can see is the Difficulty is currently "Easy'ish" as I wasn't sure whether or not to consider it Moderate. I think it's pretty straight forward, but I guess it depends on the typical user/audience we're presenting to.

Yes, it's quite unclear what is meant by "Easy", "Medium", or "Hard". It'd be nice to clarify this one day to make the label choice easier and consistent across the guides. I feel a "Beginer", "Advanced", "Expert" label might make more sense... but even then, it's still somewhat subjective.

Both Easy or Medium would work well, up to you.

2022-04-21 09:21 UTC, VajraOfIndra commented on bonus/raspberry-pi/ups-nut.md
> +
@cryptotar did you change something in the guide to address this issue? Do you know where does the issue come from and what would be the best way to address it? (i.e. placing the config lines _after_ maxretry vs commenting out maxretry..)

2022-04-21 09:24 UTC, VajraOfIndra commented
> All changes reviewed and 'approved.'

I reopened the conversation about the maxretry issue. Both @mktech-gh and myself ran into it so it might be worth adding a warning and fix.

2022-04-21 10:00 UTC, mktech-gh commented on bonus/raspberry-pi/ups-nut.md
> +Unplug the UPS from the wall and you should get an alert that the system is now running on battery power. If you plug it back in, you should get notified that it’s back “on line power”.
I get the messages on all logged-in sessions. So I checked my configuration /etc/nut/upsmon.conf again:

Guide from line 94

1. I commented out everything with # in the NOTIFYFLAG. This means that all messages are displayed in the terminal session as well as in the syslog by default.
2. I have uncommented all u in the NOTIFYMSG section. In my opinion, this means that all messages are displayed according to the default setting of NOTIFYFLAG.

I will verify this statement on my RaspiBolt tonight.

2022-04-21 13:34 UTC, cryptotar commented on bonus/raspberry-pi/ups-nut.md
> +Unplug the UPS from the wall and you should get an alert that the system is now running on battery power. If you plug it back in, you should get notified that it’s back “on line power”.
Great, let me know. Perhaps we can just add in a "default" configuration suggestion and then a note to help people figure out any changes. Might also be worth linking to the manual for NUT somewhere in the guide.

2022-04-21 18:45 UTC, mktech-gh commented on bonus/raspberry-pi/ups-nut.md
> +Unplug the UPS from the wall and you should get an alert that the system is now running on battery power. If you plug it back in, you should get notified that it’s back “on line power”.
I tested a power failure with my settings (NOTIFYMSG and NOTIFYFLAG, see file notify. png).
Battery operation and restore was shown to me on the console. See console.png

I believe that all NOTIFYMSG can be enabled

![console](https://user-images.githubusercontent.com/102212594/164531585-54b672c7-4a1e-4daf-9f5f-038876c3492e.jpg)
![notify](https://user-images.githubusercontent.com/102212594/164531589-0e0f9731-01ae-45e5-86e7-984d7f45488a.png)
.

2022-04-25 15:29 UTC, cryptotar commented on bonus/raspberry-pi/ups-nut.md
> +
I'm researching this. Hoping to have a better understanding. Worse comes to worse, I'll add a note that it can be commented out and a link to the manual for NUT. Should have complete this week.

2022-05-25 02:53 UTC, cryptotar commented on bonus/raspberry-pi/ups-nut.md
> +
I believe this is addressed now.

2022-05-25 10:28 UTC, VajraOfIndra approved these changes
LGTM

2022-05-25 10:35 UTC, merged