Bonus guide: Lightning Terminal => Pool & Loop web UI, Faraday CLI, Web Terminal connection (replaces #861)
raspibolt/raspibolt pull request #971
Opened 2022-03-17 20:31 UTC by VajraOfIndra

This PR replaces #861, which was closed because of merging conflicts.
The guide is now a bonus guide and has been shortened a bit.

#### What

This is a proposal to add Lightning Terminal, with Loop, Pool and Faraday integrated, a Loop & Pool web UI and connection to the Web Terminal.

### Why

* Lightning Terminal can be run on top of LND as one single daemon that integrates the Loop, Pool and Faraday daemons.

  * **Loop** allows to loop sats in/out of channels (= submarine swaps) via Lightning Labs Loop node.
    * This tool can be very useful to end-users and merchants to quickly and easily manage their channel balances (merchants need to regualrly move sats to remote and onchain, while end-users might need to move back sats to the local side after spending an entire channel). The tool can also be used by routing node operators.

  * **Pool** is a channel marketplace. 
    * This tool can be very useful for merchants to get inbound liqudiity and for routers to earn an income.

  * **Faraday** is an accounting tool for advanced users (CLI-only, requires manipulation of JSON/CSV etc)

* It also provided a web UI than can be accessed inside a user LAN and offers a GUI for the Loop and Pool services.

* Running Lightning Terminal also allows to connect to the web Terminal via the recently developped Lighning Node Connect (LNC). This allows an operator to securely manage its node from anywhere.

* Running Lightning Terminal allows a user to loop in/out directely from the Ride The Lightning web UI

* The RaspiBolt is based on LND (for now) and Lightning Terminal is developped by the same people than LND. We should therefore expect continuous development of Lightning Terminal alongside LND and possibly added services in the future. Moreover, running LiT with LND remote avoids the bugs associated with running LiT with LND integrated (as was proposed before as an option in RaspiBolt v2).

TL;DR: Lightning Terminal gives access to very useful lightning services (i.e. Loop and Pool) that helps merchants, end-users and routers to manage their liquidity and also offers helpful dashboard that can be used locally or remotely. LiT should be maintained and improved upon in the future as it is developped by Lightning Labs, one of the main LN company.

#### How

* Created a new bonus guide and updated the lightning bonus index

#### Scope

- [ ] significant change to core configuration
- [x] independent bonus guide
- [ ] simple bug fix

#### Test & maintenance

Test this PR by following the guide and installing Lightning Terminal, visiting the web UIs and trying the first steps of the Pool and Loop examples.

2022-04-06 21:34 UTC, mktech-gh requested changes
I installed Lightning Terminal on my RaspiBolt. It's up and running. Thanks

2022-04-06 21:34 UTC, mktech-gh commented on guide/bonus/lightning/lightning-terminal.md
> +
```suggestion

* Display the links and check that they’re not shown in red (this would indicate an error)

$ ls -la
```

2022-04-06 21:34 UTC, mktech-gh commented on guide/bonus/lightning/lightning-terminal.md
> +  $ litd
```suggestion
 $ sudo su - lit
  $ litd
```

2022-04-06 21:34 UTC, mktech-gh commented on guide/bonus/lightning/lightning-terminal.md
> +  * Past the following URL in your browser: [https://raspibolt.local::8443/](https://raspibolt.local::8443/){:target="_blank"} (replace raspibolt.local by your node IP address if required)
```suggestion
  * Past the following URL in your browser: [https://raspibolt.local:8443/](https://raspibolt.local:8443/){:target="_blank"} (replace raspibolt.local by your node IP address if required)
```

2022-04-07 08:52 UTC, VajraOfIndra commented on guide/bonus/lightning/lightning-terminal.md
> +
Good idea, I added it.

2022-04-07 09:00 UTC, VajraOfIndra commented on guide/bonus/lightning/lightning-terminal.md
> +  $ litd
Instead of relogging, I deleted the previous command that was asking to exit the litd user session.

2022-04-07 09:00 UTC, VajraOfIndra commented on guide/bonus/lightning/lightning-terminal.md
> +  * Past the following URL in your browser: [https://raspibolt.local::8443/](https://raspibolt.local::8443/){:target="_blank"} (replace raspibolt.local by your node IP address if required)
Fixed

2022-04-07 09:04 UTC, VajraOfIndra commented
> I installed Lightning Terminal on my RaspiBolt. It's up and running. Thanks

Thanks for the reviews, I amended the guide accordingly, PTAL.

2022-04-07 15:53 UTC, mktech-gh commented on guide/bonus/lightning/lightning-terminal.md
> +  * Past the following URL in your browser: [https://raspibolt.local::8443/](https://raspibolt.local::8443/){:target="_blank"} (replace raspibolt.local by your node IP address if required)
I found a problem:

admin@raspibolt:~ $ lncli -version
lncli version 0.14.2-beta commit=lightning-terminal-v0.6.5-alpha




The script "Bonus guide: System overview " uses this command to determine the lnd version and now requests an update of the lnd:

.
.
up: 18:53       rx: 1.0GiB     2nd drive: none          available mem: 3132M
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
     .~~.   .~~.      ฿itcoin (mainnet)   up     Lightning (LND)     up
    '. \ ' ' / .'     v22.0.0                    **lightning-terminal-v0.6.5-alpha   Update!**
     .~ .~~~..~.      Sync    OK [#730857]       
.
.

2022-04-07 15:58 UTC, VajraOfIndra commented on guide/bonus/lightning/lightning-terminal.md
> +  * Past the following URL in your browser: [https://raspibolt.local::8443/](https://raspibolt.local::8443/){:target="_blank"} (replace raspibolt.local by your node IP address if required)
Right, I have the same issue.
But the issue is with the system overview script which should be corrected. Could you open an Issue to report this?

2022-04-26 15:21 UTC, RooSoft requested changes
Great PR as always....

Just a couple of minor tweaks here and there...

2022-04-26 15:21 UTC, RooSoft commented on guide/bonus/lightning/lightning-terminal.md
> +Now we’ll make sure Lightning Terminal starts as a service on the Raspberry Pi so it’s always running. In order to do that, we create a systemd unit that starts the service on boot directly after LND
It's technically called a `service` if I'm not mistaken

2022-04-26 15:21 UTC, RooSoft commented on guide/bonus/lightning/lightning-terminal.md
> +For now, softwares packaged in Lightning Terminal are all listening to the same port 8443. This is not the default behavior set in the code of these sofware so you must always indicate the RPC port a
Software alway is written in singular format: `software`

2022-04-26 15:21 UTC, RooSoft commented on guide/bonus/lightning/lightning-terminal.md
> +* Click on "Channel balance mode" and select the case that best corresponds to your usage of your LN node
Click on "Channel balance mode", make a selection according to your LN node type

* Merchant: "Receiving"
* Casual end user: "Sending"
* Routing node: "Routing"

2022-04-26 15:21 UTC, RooSoft commented on guide/bonus/lightning/lightning-terminal.md
> +  $ source .bashrc
Is sourcing `~/.bashrc` really refreshing the `~./bash_aliases` file?

Just unsure... never heard of the latter.

2022-04-26 15:21 UTC, RooSoft commented on guide/bonus/lightning/lightning-terminal.md
> +* Click on "Bitcoin Transaction URL" and replace the default URL (`https://mempool.space/tx/{txid}`) by your own explorer (`https://raspibolt.local:4000/tx/{txid}`, replace raspibolt.local by your no
A lot of parenthesis in the next couple of lines... I'd rephrase that...

2022-04-27 11:26 UTC, VajraOfIndra commented on guide/bonus/lightning/lightning-terminal.md
> +Now we’ll make sure Lightning Terminal starts as a service on the Raspberry Pi so it’s always running. In order to do that, we create a systemd unit that starts the service on boot directly after LND
Afaik, technically, we create a unit file that will manage the service.
E.g.: https://www.digitalocean.com/community/tutorials/understanding-systemd-units-and-unit-files
![image](https://user-images.githubusercontent.com/86242283/165508078-13763820-df73-47cf-8491-24b621e95f32.png)

I updated to "we create a systemd service unit file"

2022-04-27 11:28 UTC, VajraOfIndra commented on guide/bonus/lightning/lightning-terminal.md
> +* Click on "Channel balance mode" and select the case that best corresponds to your usage of your LN node
Much more concise, I like that, fixed!

2022-04-27 11:38 UTC, VajraOfIndra commented on guide/bonus/lightning/lightning-terminal.md
> +  $ source .bashrc
Because `~/.bashrc`  contains:
```
# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi
```

wouldn't sourcing it enable the aliases..?

I found a tutorial sourcing `.bashrc` and one sourcing `.bash_aliases `so... not too sure which one is best to source

2022-04-27 11:41 UTC, VajraOfIndra commented on guide/bonus/lightning/lightning-terminal.md
> +* Click on "Bitcoin Transaction URL" and replace the default URL (`https://mempool.space/tx/{txid}`) by your own explorer (`https://raspibolt.local:4000/tx/{txid}`, replace raspibolt.local by your no
I removed them all... :cry:    
:stuck_out_tongue_winking_eye:

2022-04-27 11:42 UTC, VajraOfIndra commented
> Great PR as always....

:heart: 

> Just a couple of minor tweaks here and there...

Thanks @RooSoft for the review! See my replies and updates above PTAL

2022-04-27 12:49 UTC, RooSoft commented on guide/bonus/lightning/lightning-terminal.md
> +  $ source .bashrc
You are right, nothing to change here... since `~/.bashrc` sources `~/.bash_aliases`, sourcing either of them works.

2022-04-27 12:49 UTC, RooSoft commented on guide/bonus/lightning/lightning-terminal.md
> +Now we’ll make sure Lightning Terminal starts as a service on the Raspberry Pi so it’s always running. In order to do that, we create a systemd unit that starts the service on boot directly after LND
Ok, `unit` is a higher level concept. A `service` a type of `unit` and thus is more specific.

I still stand by the fact that what you are creating is a `service`. Never heard of the term `unit` before. Thanks for the learning opportunity.

2022-04-27 12:50 UTC, RooSoft commented on guide/bonus/lightning/lightning-terminal.md
> +* Click on "Bitcoin Transaction URL" and replace the default URL (`https://mempool.space/tx/{txid}`) by your own explorer (`https://raspibolt.local:4000/tx/{txid}`, replace raspibolt.local by your no
Parenthesis are evil.

2022-04-27 12:52 UTC, RooSoft approved these changes
Approved it, but I'd still prefer a systemd service not being called a unit.

2022-04-28 09:12 UTC, VajraOfIndra commented
> Approved it, but I'd still prefer a systemd service not being called a unit.

Thanks. I removed the term "unit" and used "service" only.

2022-04-28 09:13 UTC, VajraOfIndra commented on guide/bonus/lightning/lightning-terminal.md
> +Now we’ll make sure Lightning Terminal starts as a service on the Raspberry Pi so it’s always running. In order to do that, we create a systemd unit that starts the service on boot directly after LND
Fixed, removed unit andusing service only now.

2022-04-28 09:13 UTC, merged