Several small bug fixes for Mempool bonus guide
raspibolt/raspibolt pull request #984
Opened 2022-04-11 00:29 UTC by VajraOfIndra

#### What

Several bug fixes for the Mempool bonus guide:
- Fixes #918 : states the requirement of running Mempool with a minimum of 4 GB of RAM
- Fixes #965 : add a Tor proxy in Mempool config to fetch prices privately
- Fixes #966 : fixed command typo: chown -> chmod 
- a couple of minor wording changes for improved clarity

#### Scope

- [ ] significant change to core configuration
- [ ] independent bonus guide
- [x] simple bug fix

2022-04-17 01:07 UTC, RooSoft requested changes
All makes sense, just want to know more about the SOCKS5PROXY setting...

2022-04-17 01:07 UTC, RooSoft commented on guide/bonus/bitcoin/mempool.md
> +    "SOCKS5PROXY": {
Can you elaborate on what this does and where does it come from?

2022-04-17 06:36 UTC, VajraOfIndra commented on guide/bonus/bitcoin/mempool.md
> +    "SOCKS5PROXY": {
This was proposed by @visskiss in #965 

The default settings can be found here in the source repo: https://github.com/mempool/mempool/blob/bdfe31c60115d4db1d29f78aa4ee63dd8e3efe71/backend/mempool-config.sample.json
```
  "SOCKS5PROXY": {
    "ENABLED": false,
    "HOST": "127.0.0.1",
    "PORT": 9050,
    "USERNAME": "",
    "PASSWORD": ""
  },
```

Do we need to modify the Tor config to use this?
torrc states that :
```
## Tor opens a socks proxy on port 9050 by default -- even if you don't
## configure one below. [...]
#SocksPort 9050 # Default: Bind to localhost:9050 for local connections.
```

Also, I didn't set up any username and password, but we might need them, I'm not sure....

2022-04-18 17:04 UTC, RooSoft approved these changes
All those settings work, just unsure how to check if privacy leaks are completely resolved...

2022-04-18 17:04 UTC, RooSoft commented on guide/bonus/bitcoin/mempool.md
> +    "SOCKS5PROXY": {
It is working, I have no idea how to make sure the leak is gone, though...

2022-04-18 17:24 UTC, merged

2022-04-18 18:29 UTC, visskiss commented
Just thought I'd chime in here. The settings for Tor don't need to be changed because, as you pointed out, Tor provides a default proxy. As for the mempool settings, they actually won't have any effect in the current release (2.3.1) and whoever is installing will need to install from Master branch for these settings to work. If you install from master you will find that the prices are no longer leaked over clearnet. You will also find that another leak that I found in mempool (a file containing pool data) has also been resolved. When 2.4.0 is released, it should include these changes.

2022-04-18 18:32 UTC, RooSoft commented
> If you install from master you will find that the prices are no longer leaked over clearnet

How can you test this?