Add bonus guide: ThunderHub
raspibolt/raspibolt pull request #990
Opened 2022-04-15 14:56 UTC by blckbx

#### What

Revisiting stuck PR #735 and adding left open comments. 

### Why

ThunderHub is a good looking web gui for node management with one of the best UIs out there. Therefore Raspibolt guide shouldn't miss out on this. 

#### How

Following installation instructions provided by ThunderHub's github repo and combining them with RTL's setup guide (admin.macaroon workaround).

#### Scope

- [ ] significant change to core configuration
- [x] independent bonus guide
- [ ] simple bug fix

2022-04-15 16:44 UTC, VajraOfIndra requested changes
Great guide, you nailed it :clap: 

I tested it on my node and it works great.

I found only one bug that requires attention, when copying the macaroon (see below).

Also a question about the Tor proxy server and a comment about some non-breaking errors I saw in my logs.

2022-04-15 16:44 UTC, VajraOfIndra commented on guide/bonus/lightning/thunderhub.md
> +  # Server Configs
Is the Tor proxy server on by default? If not, we should probably uncomment that line in that section for TH to use the Tor proxy when querying external websites.

`TOR_PROXY_SERVER=socks://127.0.0.1:9050`

Wdyt?

2022-04-15 16:44 UTC, VajraOfIndra commented on guide/bonus/lightning/thunderhub.md
> +      macaroonPath: '/home/thunderhub/thunderhub/admin.macaroon'
```suggestion
      macaroonPath: '/home/thunderhub/admin.macaroon'
```
See first comment above, otherwise ignore.

2022-04-15 16:44 UTC, VajraOfIndra commented on guide/bonus/lightning/thunderhub.md
> +  $ sudo journalctl -f -u thunderhub
TH took a few restart before successfully running, I'm not sure why.
Here are the error messages from the logs:

```
$ sudo journalctl -f -u thunderhub
-- Journal begins at Fri 2022-04-01 16:04:25 BST. --
Apr 04 23:22:41 raspibolt npm[6552]:   syscall: 'spawn nest',
Apr 04 23:22:41 raspibolt npm[6552]:   path: 'nest',
Apr 04 23:22:41 raspibolt npm[6552]:   spawnargs: [ 'start', '3010' ]
Apr 04 23:22:41 raspibolt npm[6552]: }
Apr 04 23:22:41 raspibolt systemd[1]: thunderhub.service: Main process exited, code=exited, status=1/FAILURE
Apr 04 23:22:41 raspibolt systemd[1]: thunderhub.service: Failed with result 'exit-code'.
Apr 04 23:22:41 raspibolt systemd[1]: thunderhub.service: Consumed 1.949s CPU time.
Apr 04 23:22:44 raspibolt systemd[1]: Stopped ThunderHub.
Apr 04 23:22:44 raspibolt systemd[1]: thunderhub.service: Consumed 1.949s CPU time.
-- Boot b986d02536914669898522464edda293 --
Apr 15 17:27:42 raspibolt systemd[1]: Started Thunderhub.


[...]


-- Journal begins at Fri 2022-04-01 16:04:25 BST. --
Apr 04 23:22:41 raspibolt npm[6552]:   syscall: 'spawn nest',
Apr 04 23:22:41 raspibolt npm[6552]:   path: 'nest',
Apr 04 23:22:41 raspibolt npm[6552]:   spawnargs: [ 'start', '3010' ]
Apr 04 23:22:41 raspibolt npm[6552]: }
Apr 04 23:22:41 raspibolt systemd[1]: thunderhub.service: Main process exited, code=exited, status=1/FAILURE
Apr 04 23:22:41 raspibolt systemd[1]: thunderhub.service: Failed with result 'exit-code'.
Apr 04 23:22:41 raspibolt systemd[1]: thunderhub.service: Consumed 1.949s CPU time.
Apr 04 23:22:44 raspibolt systemd[1]: Stopped ThunderHub.
Apr 04 23:22:44 raspibolt systemd[1]: thunderhub.service: Consumed 1.949s CPU time.
```

It worked after a few autimatic restart so no action required but just wanted to pointed this out in case it could be useful for later.

2022-04-15 17:36 UTC, blckbx commented on guide/bonus/lightning/thunderhub.md
> +  $ sudo chown thunderhub:thunderhub /home/thunderhub/thunderhub/admin.macaroon
good catch!

2022-04-15 17:37 UTC, blckbx commented on guide/bonus/lightning/thunderhub.md
> +  # Server Configs
indeed

2022-04-15 17:37 UTC, blckbx commented on guide/bonus/lightning/thunderhub.md
> +  $ sudo journalctl -f -u thunderhub
NODE_ENV=production in .env.local should fix this

2022-04-15 22:57 UTC, VajraOfIndra approved these changes

2022-04-16 19:21 UTC, VajraOfIndra commented on guide/bonus/lightning/thunderhub.md
> +  $ sudo journalctl -f -u thunderhub
Thanks, I'm using this now

2022-04-16 19:22 UTC, VajraOfIndra commented
Thanks a lot for this guide @blckbx 

Let's go to master! :tada:

2022-04-16 19:22 UTC, merged